{{ config(materialized='view') }}

SELECT DISTRIBUTION_CHANNEL_HKEY, HASHDIFF, BLOCKED_FOR_RECEIPT_INDICATOR, FINANCE_SUB_CHANNEL_CODE, GREEN_CHANNEL_INDICATOR, IMDFLAG, NEW_IMD_TYPE, REVISED_CHANNEL_CODE, SPECIAL_INTERMEDIARY_CODE, SUBIMD_YN, NULL AS SUB_IMD_CODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_intermediary__channel') }}
UNION ALL
SELECT DISTRIBUTION_CHANNEL_HKEY, HASHDIFF, BLOCKED_FOR_RECEIPT_INDICATOR, FINANCE_SUB_CHANNEL_CODE, GREEN_CHANNEL_INDICATOR, IMDFLAG, NEW_IMD_TYPE, REVISED_CHANNEL_CODE, SPECIAL_INTERMEDIARY_CODE, SUBIMD_YN, NULL AS SUB_IMD_CODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_intermediary_hist__channel') }}
UNION ALL
SELECT DISTRIBUTION_CHANNEL_HKEY, HASHDIFF, NULL AS BLOCKED_FOR_RECEIPT_INDICATOR, NULL AS FINANCE_SUB_CHANNEL_CODE, NULL AS GREEN_CHANNEL_INDICATOR, NULL AS IMDFLAG, NULL AS NEW_IMD_TYPE, NULL AS REVISED_CHANNEL_CODE, NULL AS SPECIAL_INTERMEDIARY_CODE, NULL AS SUBIMD_YN, SUB_IMD_CODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_clm_supp_extn__channel') }}
