{{ config(materialized='view') }}

-- Source 1: AZBJ_PARTNER_EXTN (8 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    ECS_MANDATE_STATUS, EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NUMBER_OF_DAUGHTERS, NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_azbj_partner_extn__party') }}

UNION ALL

-- Source 2: BJAZ_INTERMEDIARY (3 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_intermediary__party') }}

UNION ALL

-- Source 3: BJAZ_INTERMEDIARY_HIST (3 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_intermediary_hist__party') }}

UNION ALL

-- Source 4: BJAZ_AZBJ_PART_EXT_HIST (3 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_azbj_part_ext_hist__party') }}

UNION ALL

-- Source 5: BJAZ_EC_MEM_DTLS_EXTN (3 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, PREGNANT_MONTHS, PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_ec_mem_dtls_extn__party') }}

UNION ALL

-- Source 6: BJAZ_HCF_MEMBER_DTLS (1 col)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hcf_member_dtls__party') }}

UNION ALL

-- Source 7: BJAZ_SPP_MEMBER_DTLS (4 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, HEIGHT_FEET, HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_spp_member_dtls__party') }}

UNION ALL

-- Source 8: BJAZ_CP_PART_HIST (2 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_cp_part_hist__party') }}

UNION ALL

-- Source 9: BJAZ_HC_PART_EXTN (1 col)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hc_part_extn__party') }}

UNION ALL

-- Source 10: CP_PARTNERS (2 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_cp_partners__party') }}

UNION ALL

-- Source 11: BJAZ_CLM_SUPP_EXTN (6 cols)
SELECT PARTY_HKEY, HASHDIFF,
    ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, PAN_ACK_DT, PAN_APP_NO, PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_clm_supp_extn__party') }}

UNION ALL

-- Source 12: BJAZ_HM_MEMBER_DTLS (1 col)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    NULL AS IMPS_ACTIVE_DATE, NULL AS IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, NULL AS PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hm_member_dtls__party') }}

UNION ALL

-- Source 13: BJAZ_HM_HOSPITAL_MASTER (3 cols)
SELECT PARTY_HKEY, HASHDIFF,
    NULL AS ADHAAR_PAN_LINK_FLAG, NULL AS BMI, NULL AS BMI_FLAG, NULL AS CAUSE_OF_DEATH, NULL AS DATE_OF_BIRTH_M,
    NULL AS ECS_MANDATE_STATUS, NULL AS EXISTING_CUSTOMER_INDICATOR, NULL AS HEIGHT_FEET, NULL AS HEIGHT_INCHES, NULL AS HNI_FLAG,
    IMPS_ACTIVE_DATE, IMPS_END_DATE, NULL AS IT_RETURN_2YR, NULL AS IT_STATUS,
    NULL AS MARRIAGE_ANNIVERSARY_DATE, NULL AS MONTHLY_SALARY, NULL AS NUMBER_OF_DAUGHTERS, NULL AS NUMBER_OF_SONS,
    NULL AS OTHER_OCC, NULL AS PAN_AADHAR_LINKED, NULL AS PAN_ACK_DT, NULL AS PAN_APP_NO, NULL AS PAN_STATUS,
    NULL AS PARENT_ENTITY_REFERENCE, PAYMENT_MODE, NULL AS PREGNANT_MONTHS, NULL AS PRIOR_CLAIM_REASON,
    NULL AS PROOF_OF_DEATH_TYPE, NULL AS SMOKE_CONSUMP, NULL AS TWO_YR_ITR_FLAG, NULL AS WEBSITE_URL,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hm_hospital_master__party') }}
