{{ config(materialized='view') }}

SELECT POLICY_HKEY, HASHDIFF, MEMBER_SEQUENCE, NULL AS CUMMULATIVE_AMT, NULL AS CUMM_BONUS, NULL AS CUMM_BONUS_AMT_COMP, NULL AS CUMM_BONUS_AMT_WIDER, NULL AS CUMM_BONUS_COMP, NULL AS CUMM_BONUS_WIDER, NULL AS INCEPTION_DATE, PREVIOUS_CUM_AMOUNT, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hlt_ensure_mem_dtls__policy') }}
UNION ALL
SELECT POLICY_HKEY, HASHDIFF, MEMBER_SEQUENCE, NULL AS CUMMULATIVE_AMT, CUMM_BONUS, NULL AS CUMM_BONUS_AMT_COMP, NULL AS CUMM_BONUS_AMT_WIDER, NULL AS CUMM_BONUS_COMP, NULL AS CUMM_BONUS_WIDER, NULL AS INCEPTION_DATE, NULL AS PREVIOUS_CUM_AMOUNT, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_hm_member_dtls__policy') }}
UNION ALL
SELECT POLICY_HKEY, HASHDIFF, MEMBER_SEQUENCE, CUMMULATIVE_AMT, NULL AS CUMM_BONUS, CUMM_BONUS_AMT_COMP, CUMM_BONUS_AMT_WIDER, CUMM_BONUS_COMP, CUMM_BONUS_WIDER, NULL AS INCEPTION_DATE, NULL AS PREVIOUS_CUM_AMOUNT, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_pa_detl_extn__policy') }}
UNION ALL
SELECT POLICY_HKEY, HASHDIFF, MEMBER_SEQUENCE, NULL AS CUMMULATIVE_AMT, NULL AS CUMM_BONUS, NULL AS CUMM_BONUS_AMT_COMP, NULL AS CUMM_BONUS_AMT_WIDER, NULL AS CUMM_BONUS_COMP, NULL AS CUMM_BONUS_WIDER, INCEPTION_DATE, NULL AS PREVIOUS_CUM_AMOUNT, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_ec_mem_dtls_extn__policy') }}
UNION ALL
SELECT POLICY_HKEY, HASHDIFF, MEMBER_SEQUENCE, NULL AS CUMMULATIVE_AMT, NULL AS CUMM_BONUS, NULL AS CUMM_BONUS_AMT_COMP, NULL AS CUMM_BONUS_AMT_WIDER, NULL AS CUMM_BONUS_COMP, NULL AS CUMM_BONUS_WIDER, INCEPTION_DATE, NULL AS PREVIOUS_CUM_AMOUNT, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_sh_mem_dtls_extn__policy') }}
