demo_dbt:
  target: dev # default
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: snowflake_jwt
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: INGESTION_PREPROD_ROLE
      warehouse: BAGIC_DPM_MAXI_RAW_WH
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      threads: 7

    prod:
      type: snowflake
      role: EMPOWER_FOUNDATION_ROLE
      warehouse: BAGIC_DPM_MAXI_RAW_WH
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      account: 'not needed'
      user: 'not needed' 
      threads: 4