demo_dbt:
  target: dev # default
  outputs:
    dev:
      type: snowflake
      account: "_" # overwritten by Snowflake CLI connection (env var) at deploy time
      user: "_"    # overwritten by Snowflake CLI connection (env var) at deploy time
      role: INGESTION_PREPROD_ROLE
      warehouse: BAGIC_DPM_MAXI_RAW_WH
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      threads: 7

    prod:
      type: snowflake
      role: EMPOWER_FOUNDATION_ROLE
      warehouse: BAGIC_DPM_MAXI_RAW_WH
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      account: 'not needed'
      user: 'not needed' 
      threads: 4