demo_dbt:
  target: dev # default
  outputs:
    dev:
      type: snowflake
      role: INGESTION_PREPROD_ROLE  # need to be created
      warehouse: BAGIC_DPM_MAXI_RAW_WH # as per role set
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      account: 'your-account-identifier'   # Your Snowflake account
      user: 'your-username'      # Your Snowflake username
      threads: 7

    prod:
      type: snowflake
      role: EMPOWER_FOUNDATION_ROLE
      warehouse: BAGIC_DPM_MAXI_RAW_WH
      database: BAGIC_PREPROD_CURATED_DB
      schema: BGIL_DEV_DATA_MODEL
      account: 'not needed'
      user: 'not needed' 
      threads: 4