{{
    config(
        materialized='view'
    )
}}

-- Staging: MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES_PIVOT_VW_2_1
-- Source: raw_health_claim

WITH source AS (
    SELECT *
    FROM {{ source('raw_health_claim', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES_PIVOT_VW_2_1') }}
),

staged AS (
    SELECT
        -- Keys
        FOREIGN_KEY,

        -- Business columns
        APPLICABLE_COVER,
        PHARMACY_RETURN_DEDUCTED,
        REJECTED_AMOUNT,
        REJECTION_REASON,
        TIME_OF_DISCHARGE,
        CRITICAL_ILLNESS,
        TARIFF_RATE_PER_UNIT,
        TARIFF_INDC_TYPE,
        INCURRED_EXPENSES,
        MAXIMUM_NUMBER_OF_WEEKS_APPROVED,
        SHOW_EDIT_BUTTON,
        BENEFIT_TYPE_NAME,
        GST_AMOUNT,
        HOSPITAL_ITEM_CODE,
        BENEFIT_LIST_CIBE,
        NO_OF_WEEKS_OF_BENEFIT_PAID,
        BILL_NUMBER,
        BENEFIT_LIST_PTDC,
        QUANTITY,
        END_DATE,
        UNIT_TYPE,
        BILLED_AMOUNT,
        TOPUP_LIMIT,
        PAYMENT_RECEIVED,
        DOUBLE_SUM_INSURED,
        PER_SITTING_CHARGES,
        HSNSAC_CODE,
        BENEFIT_NAME,
        OUTSTANDING_LOAN_AMOUNT,
        TARIFF_AMOUNT,
        DURATION_OF_DISABLEMENT,
        APPROVED_QUANTITY,
        PHARMACY_RETURN,
        CRITICAL_ILL_MULTIPLIER,
        BENEFIT_CODE,
        BENEFIT_STATUS,
        COPAY_AMOUNT,
        ORIGINAL_APPROVED_AMOUNT,
        ILLNESS_CLAIMED_CIBE,
        OLD_APPROVED_AMOUNT,
        SERVICE_TYPE_DESCRIPTION,
        APPROVED_AMOUNT,
        DISCOUNT_AMOUNT,
        SEC_ID,
        NUMBER_OF_DAYS,
        SERVICE_DATE,
        NONMEDICAL_EXPENSES,
        UNIT,
        OVERRIDE_REMARKS,
        SHOW_BUTTONS,
        HOSPITAL_ITEM_DESCRIPTION,
        BENEFIT_LIMIT_PER_WEEK,
        TIME_OF_ADMISSION,
        ADDITIONAL_BILL_DISCOUNT,
        SERVICE_TYPE_CODE,
        SERVICE_NAME,
        I3_TARIFF_REMARKS,
        DURATION_IN_WEEKS,
        SHOW_DELETE_BUTTON,
        BENEFIT_PERCENTAGE,
        SECTION_CODE,
        RECHARGE_BENEFIT,
        ELIGIBLE_AMOUNT,
        IS_BENEFIT_ELIGIBLE,
        BENEFIT_TYPE_CODE,
        ELIGIBLE_DURATION_IN_WEEKS,
        TOTAL_BENEFIT_APPROVED,
        MANUAL_REJECTION,
        I3_TARIFF_PRICE,
        INVOICE_RAISED_AGAINST_BAGIC,
        BENEFIT_LIMIT,
        BENEFIT_LIST_LIDC,
        SERVICE_CODE,
        DEDUCTIBLE_CONSUMED,
        NO_OF_SITTINGS,
        GST_NUMBER,
        START_DATE,
        REJECTED_REASON,
        HOSPITAL_GST_AMOUNT,
        BENEFIT_LIST_FRBN,
        DURATION_OF_DISABLITY_IN_WEEKS,
        SYSTEM_CALCULATED_AMOUNT,
        APPLICABLE_SUM_INSURED,
        PROVIDER_DISCOUNT,
        NONMEDICAL_ITEMS,
        ROOM_TYPE,
        TARIFF_APPLICABLE,
        BENEFIT_LIST_DEATH,

        -- Metadata
        INC_JOB_CREATED_AT,
        REC_REFRESH_AT,
        CURRENT_TIMESTAMP() AS load_dt_tm,
        'MAXIMUS' AS record_source

    FROM source src
)

SELECT * FROM staged