{{
    config(
        materialized='view'
    )
}}

-- Staging: MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_COVER_SET_ATTRIBUTE_PIVOT_VW_2_1
-- Source: raw_health_claim

WITH source AS (
    SELECT *
    FROM {{ source('raw_health_claim', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_COVER_SET_ATTRIBUTE_PIVOT_VW_2_1') }}
),

staged AS (
    SELECT
        -- Keys
        FOREIGN_KEY,

        -- Business columns
        MATERNITY_EXPENSE_MHC,
        APPROVED_AMOUNT,
        OTHERS,
        PER_SITTING_CHARGES,
        LEAVE_PERIOD_TO,
        CRITICAL_ILLNESS_CLAIM,
        EXPECTED_AMOUNT,
        CAUSE_OF_DEATH,
        NO_OF_CHILDREN,
        MODE_OF_TREATMENT,
        G_GRAVIDA_ANY_PREGNANCY_REGARDLESS_OF_DURATION,
        LEAVE_PERIOD_FROM,
        DISABILITY_DESCRIPTION,
        START_DATE,
        COVER_NAME,
        DURATION_OF_LEAVE,
        P_NUMBER_OF_PRETERM_INFANTS_BORN_AFTER_20_WEEKS_AND_BEFORE_37_WEEKS,
        COVER,
        CRITICAL_ILLNESS_DETAILS,
        AYUSH_TREATEMENT,
        LAST_PAID_EMI_DATE,
        OUTSTANDING_LOAN_AMOUNT,
        NO_OF_SITTINGS,
        CRITICAL_ILLNESS_CATEGORY,
        OUT_PATIENT_EXPENSES,
        L_NUMBER_OF_CURRENT_LIVING_CHILDREN,
        ELIGIBLE_DAYS_FOR_BENEFIT,
        VECTOR_BORNE_DISEASES,
        PERCENTAGE_OF_SI_PAYBLE,
        PROCEDURE_NAME_MHC,
        DURATION_OF_DISABLMENT,
        DATE_OF_INJURY,
        CRITICAL_ILLNESS_CODE,
        FITNESS_DATE,
        PERCENTAGE_PAYABLE,
        BALANCE_SUM_INSURED,
        ASST_REPRODUCTIVE_PRO_TECH,
        TYPE_OF_DISABILITY,
        NO_OF_SURGEON_OPINION_TAKEN,
        DATE_OF_DIAGONOSIS,
        MATERNITY_EXPENSE_SURR,
        PHYSIOTHERAPY_CHARGES,
        DATE_OF_DIAGNOSIS,
        END_DATE,
        TYPE_SEVERE_COMORBIDITIES,
        BMI,
        A_PREGNANCIES_ENDING_IN_SPONTANEOUS_ABORTION_OR_THERAPEUTIC_ABORTION,

        -- Metadata
        INC_JOB_CREATED_AT,
        REC_REFRESH_AT,
        CURRENT_TIMESTAMP() AS load_dt_tm,
        'MAXIMUS' AS record_source

    FROM source src
)

SELECT * FROM staged