{{
    config(
        materialized='view'
    )
}}

-- Staging: MAXI_HLTH_UWR_VW_DATA_MEMBERS_BENEFITS_ATTRIBUTES_PIVOT_VW_2_1
-- Source: raw_health_policy

WITH source AS (
    SELECT *
    FROM {{ source('raw_health_policy', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_BENEFITS_ATTRIBUTES_PIVOT_VW_2_1') }}
),

staged AS (
    SELECT
        -- Keys
        FOREIGN_KEY,

        -- Business columns
        TYPE_OF_COVER,
        COVER_LIMIT_PERCENTAGE,
        WIDER_SUM_INSURED_LIMIT,
        MAX_COVER_LIMIT,
        PLAN_CODE,
        LIMIT_APPLICABILITY_FOR_SIR,
        NO_OF_DAYS,
        HYPOTHYROIDISM_INSH_CVR,
        MINIMUM_AGE_UNIT,
        MANDATORYOPTIONAL,
        MAXIMUM_AGE,
        HYPERTENSION_INSH_CVR,
        PER_DAY_BENEFIT,
        RESPECT_RIDER_PLAN,
        TIME_DEDUCTIBLE,
        MAXIMUM_COVER_LIMIT,
        COVER_LEVEL_BASE_CURRENCY,
        BUTTONS,
        SMART_WATCH_RETURNED_BY_CUSTOMER,
        LIDC_COVERAGE,
        COVER_LIMIT,
        COVER_BENEFIT,
        COVER_DESCRIPTION,
        BASIC_SUM_INSURED_LIMIT,
        MINIMUM_AGE,
        APPLICABLE_SUMINSURED,
        MEMBER_NAME,
        COVER_CODE,
        SERIAL_NO,
        NOTA_INSH_CVR,
        COVER_LIMIT_TYPE,
        NO_CLAIM_DISCOUNT,
        MEDICAL_COVER_GROUPS,
        MUTUALLY_EXCLUSIVE_COVERS,
        PLAN_NAME,
        HYPERLIPIDAEMIA_INSH_CVR,
        MANDATORYCOVERLIST,
        COVER_PREMIUM,
        COMPLETE_HOMERESIDENTIAL_ADDRESS,
        HIDE_CHECK_BOX,
        NO_OF_WEEK,
        WITH_COPAY,
        INSTA_SHIELD_FIRST_INCEPTION_DATE,
        MEMBER_CODE,
        OPTIONAL_PLAN,
        COVER_LEVEL_TRANSACTION_CURRENCY_FOR_SUM_INSURED,
        DIABETES_INSH_CVR,
        SHOW_CHILD_DETAIL_TYPE,
        COMPREHENSIVE_SUM_INSURED_LIMIT,
        ALTERNATESECONDARY_CONTACT_NUMBER,
        REGISTERED_CONTACT_NUMBER,
        HPR_BENEFITS_OPTION,
        POLICYRISKCOVERID,
        PER_WEEK_SI,
        MUTUALLY_INCLUSIVE_COVERS,
        NAME,
        PLAN_TYPE,
        MAXIMUM_AGE_UNIT,
        OBESITY_INSH_CVR,
        ASTHMA_INSH_CVR,
        DATA_SOURCE,
        COVER_NAME,
        CUMULATIVE_BONUS_USED,
        PIN_CODE,
        COVER_FIRST_EFFECTIVE_DATE,
        APPLICABLE_SUM_INSURED,
        SI_FOR_DEATH_COVER,
        COVER_LEVEL_TRANSACTION_CURRENCY,
        SI_FOR_PTD_COVER,
        COVER_EXPIRY_DATE,

        -- Metadata
        INC_JOB_CREATED_AT,
        REC_REFRESH_AT,
        CURRENT_TIMESTAMP() AS load_dt_tm,
        'MAXIMUS' AS record_source

    FROM source src
)

SELECT * FROM staged