{{
    config(
        materialized='view'
    )
}}

-- Staging: MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES_PIVOT_VW_2_1
-- Source: raw_health_policy

WITH source AS (
    SELECT *
    FROM {{ source('raw_health_policy', 'MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES_PIVOT_VW_2_1') }}
),

staged AS (
    SELECT
        -- Keys
        FOREIGN_KEY,

        -- Business columns
        PREVIOUS_POLICYPROPOSAL_NUMBER,
        ICD_DESCRIPTION,
        DISCOUNT_LOADING_TYPE,
        IF_OTHERS_PLEASE_SPECIFY,
        RELATIONSHIP_WITH_PROPOSER,
        POLICY_STATUS,
        INSURER,
        DISCOUNT_LOADING_RATE,
        TYPE_OF_ENDORSEMENT,
        LOADING_RATE,
        CONTINUITY_INDICATOR_APPROVED,
        DATE_OF_BIRTH,
        AGE,
        LOADING_DISCOUNT_REASON_POLICY,
        NUMBER_OF_CLAIMS_LODGED,
        CUMULATIVE_BONUS_IN_PREVIOUS_POLICY,
        EMAIL_ID,
        PROPOSER_NAME,
        PREVIOUS_POLICY_EXPIRY_DATE,
        DISCOUNT_AND_LOADING_REASON,
        LOADING_WAIVE_OFF,
        APPLICABLE_LEVEL,
        ADDRESS_OF_NOMINEE,
        POLICY_RISK_EXPIRY_DATE,
        MEMBER_CODE,
        OTHER_BAGIC_POLICY_NUMBER,
        PARTY_NAME,
        APPOINTEE_NAME,
        RELATIONSHIP_OF_APPOINTEE_WITH_THE_NOMINEE,
        DISCOUNT_RATE,
        NOMINEE_NAME,
        PLAN_OF_POLICY,
        NET_PREMIUM,
        REMARKS,
        ICD_CODE,
        DISCOUNT_LOADING_TYPE_POLICY,
        GENDER,
        INSURER_CODE,
        NOMINEE_DATE_OF_BIRTH,
        PREVIOUS_POLICY_START_DATE,
        TYPE_OF_PREVIOUS_INSURANCE,
        APPLICABLE_FOR_OTHER_MEMBER,
        SUM_INSURED_IN_PREVIOUS_POLICY,
        NOMINEE_,

        -- Metadata
        INC_JOB_CREATED_AT,
        REC_REFRESH_AT,
        CURRENT_TIMESTAMP() AS load_dt_tm,
        'MAXIMUS' AS record_source

    FROM source src
)

SELECT * FROM staged