-- Staging model for source table BJAZ_TRV_LOADER_LOG_TABLE_MV (Travel LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health/Partner LOB builds.
-- Types read from OPUS_TRAVEL_SCHEMA_with_DATA_TYPE.csv (real Snowflake DESCRIBE-style
-- metadata, supplied by the mapper) -- not inferred.

with source as (

    select
    nullif(trim(to_varchar("AGE")), '') as age,
    nullif(trim(to_varchar("ASSIGNEE")), '') as assignee,
    nullif(trim(to_varchar("BUILDING")), '') as building,
    nullif(trim(to_varchar("CC")), '') as cc,
    nullif(trim(to_varchar("CHASSISNO")), '') as chassisno,
    nullif(trim(to_varchar("CITY")), '') as city,
    nullif(trim(to_varchar("COMPANYNAME")), '') as companyname,
    nullif(trim(to_varchar("CONTRACTID")), '') as contractid,
    nullif(trim(to_varchar("COORGUNIT")), '') as coorgunit,
    nullif(trim(to_varchar("COUNTRY")), '') as country,
    nullif(trim(to_varchar("COVERNOTEDATE")), '') as covernotedate,
    nullif(trim(to_varchar("COVERNOTENO")), '') as covernoteno,
    nullif(trim(to_varchar("DATEOFBIRTH")), '') as dateofbirth,
    nullif(trim(to_varchar("DEALERCODE")), '') as dealercode,
    nullif(trim(to_varchar("DESIGNATION")), '') as designation,
    nullif(trim(to_varchar("DESTINATION")), '') as destination,
    nullif(trim(to_varchar("DISCOUNT")), '') as discount,
    nullif(trim(to_varchar("DISTANCE")), '') as distance,
    nullif(trim(to_varchar("DRIVERYN")), '') as driveryn,
    nullif(trim(to_varchar("EMAIL")), '') as email,
    nullif(trim(to_varchar("EMPNO")), '') as empno,
    nullif(trim(to_varchar("EMPSTATUS")), '') as empstatus,
    nullif(trim(to_varchar("ENGINENO")), '') as engineno,
    nullif(trim(to_varchar("FAMILYFLAG")), '') as familyflag,
    nullif(trim(to_varchar("FAX")), '') as fax,
    nullif(trim(to_varchar("FIRSTNAME")), '') as firstname,
    nullif(trim(to_varchar("GROSSPREMIUM")), '') as grosspremium,
    nullif(trim(to_varchar("INTERMEDIARY")), '') as intermediary,
    nullif(trim(to_varchar("LOADING")), '') as loading,
    nullif(trim(to_varchar("LOCATIONCODE")), '') as locationcode,
    nullif(trim(to_varchar("MAKE")), '') as make,
    nullif(trim(to_varchar("MARITALSTATUS")), '') as maritalstatus,
    nullif(trim(to_varchar("MIDDLENAME")), '') as middlename,
    nullif(trim(to_varchar("MOBILENUMBER")), '') as mobilenumber,
    nullif(trim(to_varchar("MODEL")), '') as model,
    nullif(trim(to_varchar("PAREAPLAN")), '') as pareaplan,
    nullif(trim(to_varchar("PARTNERID")), '') as partnerid,
    nullif(trim(to_varchar("PASSPORTNO")), '') as passportno,
    nullif(trim(to_varchar("PAYMENTMODE")), '') as paymentmode,
    nullif(trim(to_varchar("PINCODE")), '') as pincode,
    nullif(trim(to_varchar("PLANID")), '') as planid,
    nullif(trim(to_varchar("PMASTERPOLICYNUMBER")), '') as pmasterpolicynumber,
    nullif(trim(to_varchar("POLICYISSUEDATE")), '') as policyissuedate,
    nullif(trim(to_varchar("POLICYNUMBER")), '') as policynumber,
    nullif(trim(to_varchar("PREMIUMPAYERFLAG")), '') as premiumpayerflag,
    nullif(trim(to_varchar("PREMIUMPAYERID")), '') as premiumpayerid,
    nullif(trim(to_varchar("PRODUCT")), '') as product,
    nullif(trim(to_varchar("REGISTRATIONNO")), '') as registrationno,
    nullif(trim(to_varchar("RELATION")), '') as relation,
    nullif(trim(to_varchar("RURALFLAG")), '') as ruralflag,
    nullif(trim(to_varchar("SCHEMECODE")), '') as schemecode,
    nullif(trim(to_varchar("SEATINGCAPACITY")), '') as seatingcapacity,
    nullif(trim(to_varchar("SERVICECHARGE")), '') as servicecharge,
    nullif(trim(to_varchar("SERVICETAX")), '') as servicetax,
    nullif(trim(to_varchar("SEX")), '') as sex,
    nullif(trim(to_varchar("SPCONDITION")), '') as spcondition,
    nullif(trim(to_varchar("SPDISCOUNT")), '') as spdiscount,
    nullif(trim(to_varchar("SPDISCOUNTAMT")), '') as spdiscountamt,
    nullif(trim(to_varchar("STARTDATE")), '') as startdate,
    nullif(trim(to_varchar("STATE")), '') as state,
    nullif(trim(to_varchar("STREETNAME")), '') as streetname,
    nullif(trim(to_varchar("SUBAGENTCODE")), '') as subagentcode,
    nullif(trim(to_varchar("SUBTYPE")), '') as subtype,
    nullif(trim(to_varchar("SUMINSURED")), '') as suminsured,
    nullif(trim(to_varchar("SURNAME")), '') as surname,
    nullif(trim(to_varchar("TELEPHONE")), '') as telephone,
    nullif(trim(to_varchar("TITLE")), '') as title,
    nullif(trim(to_varchar("TODATE")), '') as todate,
    nullif(trim(to_varchar("TOTALPREMIUM")), '') as totalpremium,
    nullif(trim(to_varchar("TRANSITFROM")), '') as transitfrom,
    nullif(trim(to_varchar("TRANSITTO")), '') as transitto,
    nullif(trim(to_varchar("TRAVELPLAN")), '') as travelplan,
    nullif(trim(to_varchar("YEAROFMFG")), '') as yearofmfg
    from {{ source('travel_raw', 'BJAZ_TRV_LOADER_LOG_TABLE_MV') }}

)

select * from source
