-- Staging model for source table BJAZ_TRV_LOADER_DATA_MV (Travel LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health/Partner LOB builds.
-- Types read from OPUS_TRAVEL_SCHEMA_with_DATA_TYPE.csv (real Snowflake DESCRIBE-style
-- metadata, supplied by the mapper) -- not inferred.

with source as (

    select
    nullif(trim(to_varchar("ACCHOSPEXP")), '') as acchospexp,
    nullif(trim(to_varchar("ADHARCARDNO")), '') as adharcardno,
    nullif(trim(to_varchar("ADVENTURESPORTBENEFIT")), '') as adventuresportbenefit,
    nullif(trim(to_varchar("AGENTEMAILID")), '') as agentemailid,
    nullif(trim(to_varchar("ALTITUDE")), '') as altitude,
    nullif(trim(to_varchar("AREAPLAN")), '') as areaplan,
    nullif(trim(to_varchar("BAGICECODE")), '') as bagicecode,
    nullif(trim(to_varchar("BANKCUSTID")), '') as bankcustid,
    nullif(trim(to_varchar("BANKECODE")), '') as bankecode,
    nullif(trim(to_varchar("BANKRMCODE")), '') as bankrmcode,
    nullif(trim(to_varchar("BOUNCEDHOTEL")), '') as bouncedhotel,
    nullif(trim(to_varchar("BUILDING")), '') as building,
    nullif(trim(to_varchar("CAAMT")), '') as caamt,
    nullif(trim(to_varchar("CADATE")), '') as cadate,
    nullif(trim(to_varchar("CANO")), '') as cano,
    nullif(trim(to_varchar("COMMISSIONRATE")), '') as commissionrate,
    nullif(trim(to_varchar("COMPANYNAME")), '') as companyname,
    nullif(trim(to_varchar("COMPVISITFAMILYMEMBER")), '') as compvisitfamilymember,
    nullif(trim(to_varchar("CUSTCONSENT")), '') as custconsent,
    nullif(trim(to_varchar("CUSTOMERTYPE")), '') as customertype,
    nullif(trim(to_varchar("DATEOFBIRTH")), '') as dateofbirth,
    nullif(trim(to_varchar("DELAYOFCHECKEDBAGGAGE")), '') as delayofcheckedbaggage,
    nullif(trim(to_varchar("DEPARTUREDATE")), '') as departuredate,
    nullif(trim(to_varchar("DISCOUNT")), '') as discount,
    nullif(trim(to_varchar("EIANO")), '') as eiano,
    nullif(trim(to_varchar("EMAIL")), '') as email,
    nullif(trim(to_varchar("EMERGENCYHOTELEXTENSION")), '') as emergencyhotelextension,
    nullif(trim(to_varchar("EMERMEDICALEVAC")), '') as emermedicalevac,
    nullif(trim(to_varchar("EMPLOYMENTSTATUS")), '') as employmentstatus,
    nullif(trim(to_varchar("FAMILYFLAG")), '') as familyflag,
    nullif(trim(to_varchar("FAX")), '') as fax,
    nullif(trim(to_varchar("FIRSTNAME")), '') as firstname,
    nullif(trim(to_varchar("GSTIN_UIN")), '') as gstin_uin,
    nullif(trim(to_varchar("HOMEBURGLARYINSURANCE")), '') as homeburglaryinsurance,
    nullif(trim(to_varchar("HOSPDAILYALLOW")), '') as hospdailyallow,
    nullif(trim(to_varchar("INTERMEDIARY")), '') as intermediary,
    nullif(trim(to_varchar("LANNO")), '') as lanno,
    nullif(trim(to_varchar("LOADING")), '') as loading,
    nullif(trim(to_varchar("LOCATION")), '') as location,
    nullif(trim(to_varchar("LOSSOFBAGGAGE")), '') as lossofbaggage,
    nullif(trim(to_varchar("LOSSOFCHECKEDBAGGAGE")), '') as lossofcheckedbaggage,
    nullif(trim(to_varchar("MARITALSTATUS")), '') as maritalstatus,
    nullif(trim(to_varchar("MEMBER1ASSIGNEE")), '') as member1assignee,
    nullif(trim(to_varchar("MEMBER1DESEASE")), '') as member1desease,
    nullif(trim(to_varchar("MEMBER1DOB")), '') as member1dob,
    nullif(trim(to_varchar("MEMBER1GENDER")), '') as member1gender,
    nullif(trim(to_varchar("MEMBER1NAME")), '') as member1name,
    nullif(trim(to_varchar("MEMBER1PASSPORTNO")), '') as member1passportno,
    nullif(trim(to_varchar("MEMBER1RELATION")), '') as member1relation,
    nullif(trim(to_varchar("MEMBER2ASSIGNEE")), '') as member2assignee,
    nullif(trim(to_varchar("MEMBER2DESEASE")), '') as member2desease,
    nullif(trim(to_varchar("MEMBER2DOB")), '') as member2dob,
    nullif(trim(to_varchar("MEMBER2GENDER")), '') as member2gender,
    nullif(trim(to_varchar("MEMBER2NAME")), '') as member2name,
    nullif(trim(to_varchar("MEMBER2PASSPORTNO")), '') as member2passportno,
    nullif(trim(to_varchar("MEMBER2RELATION")), '') as member2relation,
    nullif(trim(to_varchar("MEMBER3ASSIGNEE")), '') as member3assignee,
    nullif(trim(to_varchar("MEMBER3DESEASE")), '') as member3desease,
    nullif(trim(to_varchar("MEMBER3DOB")), '') as member3dob,
    nullif(trim(to_varchar("MEMBER3GENDER")), '') as member3gender,
    nullif(trim(to_varchar("MEMBER3NAME")), '') as member3name,
    nullif(trim(to_varchar("MEMBER3PASSPORTNO")), '') as member3passportno,
    nullif(trim(to_varchar("MEMBER3RELATION")), '') as member3relation,
    nullif(trim(to_varchar("MEMBER4ASSIGNEE")), '') as member4assignee,
    nullif(trim(to_varchar("MEMBER4DESEASE")), '') as member4desease,
    nullif(trim(to_varchar("MEMBER4DOB")), '') as member4dob,
    nullif(trim(to_varchar("MEMBER4GENDER")), '') as member4gender,
    nullif(trim(to_varchar("MEMBER4NAME")), '') as member4name,
    nullif(trim(to_varchar("MEMBER4PASSPORTNO")), '') as member4passportno,
    nullif(trim(to_varchar("MEMBER4RELATION")), '') as member4relation,
    nullif(trim(to_varchar("MEMBER5ASSIGNEE")), '') as member5assignee,
    nullif(trim(to_varchar("MEMBER5DESEASE")), '') as member5desease,
    nullif(trim(to_varchar("MEMBER5DOB")), '') as member5dob,
    nullif(trim(to_varchar("MEMBER5GENDER")), '') as member5gender,
    nullif(trim(to_varchar("MEMBER5NAME")), '') as member5name,
    nullif(trim(to_varchar("MEMBER5PASSPORTNO")), '') as member5passportno,
    nullif(trim(to_varchar("MEMBER5RELATION")), '') as member5relation,
    nullif(trim(to_varchar("MIDDLENAME")), '') as middlename,
    nullif(trim(to_varchar("MISSEDCONNECTION")), '') as missedconnection,
    nullif(trim(to_varchar("MOBILENUMBER")), '') as mobilenumber,
    nullif(trim(to_varchar("MODEOFTRANSPORT")), '') as modeoftransport,
    nullif(trim(to_varchar("NOMINEENAME")), '') as nomineename,
    nullif(trim(to_varchar("NOMINEERELATIONSHIP")), '') as nomineerelationship,
    nullif(trim(to_varchar("NOOFFAMILYMEMBERS")), '') as nooffamilymembers,
    nullif(trim(to_varchar("NOOFJOURNEYDAYS")), '') as noofjourneydays,
    nullif(trim(to_varchar("PART_ID")), '') as part_id,
    nullif(trim(to_varchar("PASSPORTNO")), '') as passportno,
    nullif(trim(to_varchar("PAYMENTMODE")), '') as paymentmode,
    nullif(trim(to_varchar("PERSONALLIABILITY")), '') as personalliability,
    nullif(trim(to_varchar("PINCODE")), '') as pincode,
    nullif(trim(to_varchar("PLAN")), '') as plan,
    nullif(trim(to_varchar("PLANSI")), '') as plansi,
    "POLICY_PREMIUM"::number as policy_premium,
    nullif(trim(to_varchar("POLICY_REF")), '') as policy_ref,
    nullif(trim(to_varchar("PREMIUMPAYERID")), '') as premiumpayerid,
    nullif(trim(to_varchar("PRJOURNEY")), '') as prjourney,
    nullif(trim(to_varchar("PROPASTRAVELLER")), '') as propastraveller,
    nullif(trim(to_varchar("PROPOSERDEASES")), '') as proposerdeases,
    nullif(trim(to_varchar("RECEIPTNO")), '') as receiptno,
    nullif(trim(to_varchar("REPATONOFREMAINS")), '') as repatonofremains,
    nullif(trim(to_varchar("RETURNDATE")), '') as returndate,
    nullif(trim(to_varchar("RURALFLAG")), '') as ruralflag,
    nullif(trim(to_varchar("SCRUTINY_NO")), '') as scrutiny_no,
    nullif(trim(to_varchar("SEX")), '') as sex,
    nullif(trim(to_varchar("SPDISCOUNT")), '') as spdiscount,
    nullif(trim(to_varchar("STATE")), '') as state,
    nullif(trim(to_varchar("STREETNAME")), '') as streetname,
    nullif(trim(to_varchar("SUBAREACITY")), '') as subareacity,
    nullif(trim(to_varchar("SUBIMD")), '') as subimd,
    nullif(trim(to_varchar("SURNAME")), '') as surname,
    nullif(trim(to_varchar("TELEPHONE")), '') as telephone,
    nullif(trim(to_varchar("TOTALPREMIUM")), '') as totalpremium,
    nullif(trim(to_varchar("TRANSACTIONID")), '') as transactionid,
    nullif(trim(to_varchar("TRAVELPLANCATEGORY")), '') as travelplancategory,
    nullif(trim(to_varchar("TRIPCANCELLATION")), '') as tripcancellation,
    nullif(trim(to_varchar("TRIPCURTAILMENT")), '') as tripcurtailment,
    nullif(trim(to_varchar("TRIPDELAYBYSCHEDULEDAIRCRAFT")), '') as tripdelaybyscheduledaircraft,
    "INC_JOB_UPDATED_AT"::timestamp_ntz as inc_job_updated_at
    from {{ source('travel_raw', 'BJAZ_TRV_LOADER_DATA_MV') }}

)

select * from source
