-- Staging model for source table BJAZ_HM_HCM_EXTRACT (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("ACCOUNT_NO"::varchar), '') as account_no,
    "ACTUAL_DOA"::timestamp_ntz as actual_doa,
    "ACTUAL_DOD"::timestamp_ntz as actual_dod,
    "AGE"::number as age,
    "AMBULANCE"::number as ambulance,
    "APPROVAL_DATE"::timestamp_ntz as approval_date,
    "APPROVED_AMT"::number as approved_amt,
    nullif(trim("ASSESSMENT_EXCLAUSE"::varchar), '') as assessment_exclause,
    "ASSSEMENT_DATE"::timestamp_ntz as asssement_date,
    nullif(trim("AUTHORIZATION_REMARKS"::varchar), '') as authorization_remarks,
    "AUTH_AMOUNT"::number as auth_amount,
    "AUTH_DATE"::timestamp_ntz as auth_date,
    nullif(trim("AVAILED_ROOM_CATEGORY"::varchar), '') as availed_room_category,
    nullif(trim("AVAILED_ROOM_CATEGORY_H"::varchar), '') as availed_room_category_h,
    nullif(trim(to_varchar("BANK_AC_NO")), '') as bank_ac_no,
    nullif(trim("BANK_NAME"::varchar), '') as bank_name,
    "BSI_AMT"::number as bsi_amt,
    nullif(trim("CHEQUE_DATE"::varchar), '') as cheque_date,
    nullif(trim("CHEQUE_DIS_DATE"::varchar), '') as cheque_dis_date,
    nullif(trim(to_varchar("CHEQUE_NO")), '') as cheque_no,
    nullif(trim("CHEQUE_REC_DATE"::varchar), '') as cheque_rec_date,
    "CLAIMED_AMT"::number as claimed_amt,
    nullif(trim("CLAIM_CLOSE_STATUS"::varchar), '') as claim_close_status,
    nullif(trim(to_varchar("CLAIM_NO")), '') as claim_no,
    nullif(trim("CLAIM_STATUS"::varchar), '') as claim_status,
    nullif(trim("CLAIM_TYPE"::varchar), '') as claim_type,
    nullif(trim(to_varchar("CLID")), '') as clid,
    "CLOSE_DATE"::timestamp_ntz as close_date,
    "CO_PAYMENT"::number as co_payment,
    "CRITI_UNIT_ROOM_RENT_PER_DAY"::number as criti_unit_room_rent_per_day,
    "CRITI_UNIT_ROOM_RENT_PER_DAY_H"::number as criti_unit_room_rent_per_day_h,
    nullif(trim("DEBIT_CARD_NO"::varchar), '') as debit_card_no,
    nullif(trim("DENIAL_REASON"::varchar), '') as denial_reason,
    nullif(trim("DIAGNOSIS_DETAIL"::varchar), '') as diagnosis_detail,
    nullif(trim("DIG_PROCEDURE"::varchar), '') as dig_procedure,
    "DISCOUNT"::number as discount,
    "DOCUMENT_RECEIVE_DATE"::timestamp_ntz as document_receive_date,
    "DOC_RECEIVE_DATE_MAX"::timestamp_ntz as doc_receive_date_max,
    "DOJ"::timestamp_ntz as doj,
    nullif(trim("DR_REQUIREMENT_HOSPITAL"::varchar), '') as dr_requirement_hospital,
    nullif(trim("DR_REQUIREMENT_INSURED"::varchar), '') as dr_requirement_insured,
    nullif(trim("DR_REQUIREMENT_OTHERS"::varchar), '') as dr_requirement_others,
    nullif(trim("ELIGIBLE_ROOM_CATEGORY"::varchar), '') as eligible_room_category,
    nullif(trim("ELIGIBLE_ROOM_CATEGORY_H"::varchar), '') as eligible_room_category_h,
    "ELIGIBLE_ROOM_RENT"::number as eligible_room_rent,
    "ELIGIBLE_ROOM_RENT_H"::number as eligible_room_rent_h,
    nullif(trim("EMPLOYEE_NAME"::varchar), '') as employee_name,
    "EXPECTED_DOD"::timestamp_ntz as expected_dod,
    nullif(trim("FAX"::varchar), '') as fax,
    nullif(trim("FINAL_DIAGNOSIS"::varchar), '') as final_diagnosis,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("GENERAL_REMARKS"::varchar), '') as general_remarks,
    nullif(trim("HOSPITAL"::varchar), '') as hospital,
    nullif(trim("HOSPITAL_BILL_NO"::varchar), '') as hospital_bill_no,
    "HOSPITAL_DISALLOWED_AMT"::number as hospital_disallowed_amt,
    nullif(trim("HOSPITAL_DISALLOW_AMT_REASON"::varchar), '') as hospital_disallow_amt_reason,
    nullif(trim(to_varchar("HOSPITAL_ID")), '') as hospital_id,
    nullif(trim("HOSPITAL_TYPE"::varchar), '') as hospital_type,
    nullif(trim("ICD_CODE"::varchar), '') as icd_code,
    "ICU_CHARGES"::number as icu_charges,
    nullif(trim("ID_CARD"::varchar), '') as id_card,
    nullif(trim(to_varchar("IMD_CODE")), '') as imd_code,
    "IMPLANT_CHARGES"::number as implant_charges,
    nullif(trim("INSURED"::varchar), '') as insured,
    nullif(trim("IP_NO"::varchar), '') as ip_no,
    "MEDICAL_MGT_DATE"::timestamp_ntz as medical_mgt_date,
    nullif(trim("MEDICAL_OR_SURGICAL"::varchar), '') as medical_or_surgical,
    "MISCELLANEOUS"::number as miscellaneous,
    nullif(trim("MOBILE_NO"::varchar), '') as mobile_no,
    nullif(trim("MODE_OF_PAYMENT"::varchar), '') as mode_of_payment,
    nullif(trim("NAME_DR"::varchar), '') as name_dr,
    "NURSING_CHARGES"::number as nursing_charges,
    "OTHER_DEDUCTION"::number as other_deduction,
    "OT_CHARGES"::number as ot_charges,
    "PACKAGE_CHARGES"::number as package_charges,
    nullif(trim("PAN_NO"::varchar), '') as pan_no,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    nullif(trim("PATIENT"::varchar), '') as patient,
    nullif(trim("PATIENT_ADDRESS"::varchar), '') as patient_address,
    nullif(trim("ADD1"::varchar), '') as add1,
    nullif(trim("ADD2"::varchar), '') as add2,
    nullif(trim("CITY"::varchar), '') as city,
    nullif(trim("STATE"::varchar), '') as state,
    nullif(trim("PIN"::varchar), '') as pin,
    nullif(trim("PAYABLE_TO_HOSPITAL"::varchar), '') as payable_to_hospital,
    nullif(trim("PAYABLE_TO_INSURED"::varchar), '') as payable_to_insured,
    nullif(trim("PAYABLE_TO_INVESTIGATOR"::varchar), '') as payable_to_investigator,
    nullif(trim("PAY_STATUS"::varchar), '') as pay_status,
    "PHARMACY"::number as pharmacy,
    nullif(trim("PHONE"::varchar), '') as phone,
    nullif(trim(to_varchar("PID")), '') as pid,
    nullif(trim(to_varchar("POLICY")), '') as policy,
    nullif(trim(to_varchar("POLICY_LOCATION")), '') as policy_location,
    "POST_HOSP_CHARGES"::number as post_hosp_charges,
    nullif(trim("PREAUTH_EXCLAUSE"::varchar), '') as preauth_exclause,
    "PREMIUM"::number as premium,
    "PRE_AUTH_AMT"::number as pre_auth_amt,
    "PRE_AUTH_DATE"::timestamp_ntz as pre_auth_date,
    "PRE_HOSP_CHARGES"::number as pre_hosp_charges,
    nullif(trim("PROCESSOR"::varchar), '') as processor,
    "RED"::timestamp_ntz as red,
    "REGISTRATION_DATE"::timestamp_ntz as registration_date,
    "REPUDIATION_DT"::timestamp_ntz as repudiation_dt,
    nullif(trim("REPUDIATION_REASON"::varchar), '') as repudiation_reason,
    "RESERVE_AMT"::number as reserve_amt,
    "RID"::timestamp_ntz as rid,
    nullif(trim("ROOM_CATEGORY"::varchar), '') as room_category,
    "ROOM_CHARGES"::number as room_charges,
    nullif(trim("SERVICE_TAX"::varchar), '') as service_tax,
    nullif(trim("SERVICE_TAX_AMOUNT"::varchar), '') as service_tax_amount,
    nullif(trim("SERVICE_TAX_RATE"::varchar), '') as service_tax_rate,
    nullif(trim("STD"::varchar), '') as std,
    "SUM_INSURED"::number as sum_insured,
    "SURGEON_CHARGES"::number as surgeon_charges,
    nullif(trim("TDS_AMOUNT"::varchar), '') as tds_amount,
    nullif(trim("TDS_RATE"::varchar), '') as tds_rate,
    nullif(trim("TELEPHONE"::varchar), '') as telephone,
    "TOTAL_BILL"::number as total_bill,
    nullif(trim("TREATMENT_TYPE"::varchar), '') as treatment_type,
    nullif(trim("TYPE_OF_LOSS"::varchar), '') as type_of_loss,
    nullif(trim(to_varchar("UTR_NO")), '') as utr_no
    from {{ source('health_raw', 'BJAZ_HM_HCM_EXTRACT') }}

)

select * from source
