-- Staging model for source table BJAZ_HG_POL_DTLS (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("AADHAAR_NO"::varchar), '') as aadhaar_no,
    nullif(trim("ADDRESS_LINE1"::varchar), '') as address_line1,
    nullif(trim("ADDRESS_LINE2"::varchar), '') as address_line2,
    "AGGREGATE_DEDUCTIBLE"::number as aggregate_deductible,
    nullif(trim("AIR_AMBULANCE_YN"::varchar), '') as air_ambulance_yn,
    nullif(trim("AREA"::varchar), '') as area,
    nullif(trim("AUTH_CODE"::varchar), '') as auth_code,
    "BANK_CHARGES"::number as bank_charges,
    nullif(trim(to_varchar("BUSINESS_SOURCE")), '') as business_source,
    nullif(trim("CAL_PREM"::varchar), '') as cal_prem,
    "CGST_AMT"::number as cgst_amt,
    nullif(trim("CITY"::varchar), '') as city,
    nullif(trim(to_varchar("COMPANY_ORG_UNIT")), '') as company_org_unit,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    nullif(trim("COUNTRY_CODE"::varchar), '') as country_code,
    nullif(trim(to_varchar("COVER_CODE")), '') as cover_code,
    nullif(trim("CURR_PINCODE"::varchar), '') as curr_pincode,
    "DATE_OF_BIRTH"::timestamp_ntz as date_of_birth,
    nullif(trim(to_varchar("DEPARTMENT_CODE")), '') as department_code,
    "DISCOUNT"::number as discount,
    nullif(trim("DISP_ADDRESS_LINE1"::varchar), '') as disp_address_line1,
    nullif(trim("DISP_ADDRESS_LINE2"::varchar), '') as disp_address_line2,
    nullif(trim("DISP_AREA"::varchar), '') as disp_area,
    nullif(trim("DISP_CITY"::varchar), '') as disp_city,
    nullif(trim("DISP_OTHER_AREA"::varchar), '') as disp_other_area,
    nullif(trim("DISP_STATE"::varchar), '') as disp_state,
    nullif(trim("EMAIL"::varchar), '') as email,
    nullif(trim("EMAIL_CUST"::varchar), '') as email_cust,
    nullif(trim("FIRST_NAME"::varchar), '') as first_name,
    "GROSS_PREMIUM"::number as gross_premium,
    "IGST_AMT"::number as igst_amt,
    nullif(trim("LAST_NAME"::varchar), '') as last_name,
    "MAILING_PINCODE"::number as mailing_pincode,
    nullif(trim(to_varchar("MAIN_AGENT_CODE")), '') as main_agent_code,
    nullif(trim("MEM_COVERED_POL_YN"::varchar), '') as mem_covered_pol_yn,
    nullif(trim("MERCHANT_CODE"::varchar), '') as merchant_code,
    "MOBILE_NO"::number as mobile_no,
    "NCC_AMT"::number as ncc_amt,
    nullif(trim("OTHER_AREA"::varchar), '') as other_area,
    nullif(trim("PAN_NUMBER"::varchar), '') as pan_number,
    nullif(trim("PARTNER_GSTN"::varchar), '') as partner_gstn,
    nullif(trim(to_varchar("PART_ID")), '') as part_id,
    nullif(trim("PAYMENT_BANK_NAME"::varchar), '') as payment_bank_name,
    nullif(trim("PAYMENT_GATEWAY"::varchar), '') as payment_gateway,
    nullif(trim("PAYMENT_MODE"::varchar), '') as payment_mode,
    nullif(trim("PAYMENT_RECEIVED_YN"::varchar), '') as payment_received_yn,
    "PAYMENT_REQ_DATE_TIME"::timestamp_ntz as payment_req_date_time,
    "PAYMENT_RES_DATE_TIME"::timestamp_ntz as payment_res_date_time,
    nullif(trim("PLAN_DESC"::varchar), '') as plan_desc,
    nullif(trim(to_varchar("POLICY_REF")), '') as policy_ref,
    "POLICY_TYPE"::number as policy_type,
    nullif(trim("POL_BENEFIT_TRAN_YN"::varchar), '') as pol_benefit_tran_yn,
    "POL_PERIOD"::number as pol_period,
    nullif(trim("POSTCODE"::varchar), '') as postcode,
    nullif(trim("PREV_ACCIDENT_YN"::varchar), '') as prev_accident_yn,
    nullif(trim("PREV_DISEASE_COVERED_DESC"::varchar), '') as prev_disease_covered_desc,
    nullif(trim("PREV_DISEASE_COVERED_YN"::varchar), '') as prev_disease_covered_yn,
    nullif(trim("PREV_POLICY_NO"::varchar), '') as prev_policy_no,
    "PREV_SUM_INSURED"::number as prev_sum_insured,
    nullif(trim(to_varchar("PRODUCT_4DIGIT_CODE")), '') as product_4digit_code,
    nullif(trim(to_varchar("PROSPECT_ID")), '') as prospect_id,
    nullif(trim(to_varchar("QUOTE_REF_NO")), '') as quote_ref_no,
    nullif(trim("QUOTE_STATUS"::varchar), '') as quote_status,
    nullif(trim("RECEIPT_NO"::varchar), '') as receipt_no,
    nullif(trim("RISK_CLASS"::varchar), '') as risk_class,
    "SGST_AMT"::number as sgst_amt,
    nullif(trim("STATE"::varchar), '') as state,
    nullif(trim("SUB_AGENT_CODE"::varchar), '') as sub_agent_code,
    "TELEPHONE"::number as telephone,
    "TERM_END_DATE"::timestamp_ntz as term_end_date,
    "TERM_START_DATE"::timestamp_ntz as term_start_date,
    "TOTAL_MEM_CNT"::number as total_mem_cnt,
    "TOTAL_SUM_INSURED"::number as total_sum_insured,
    nullif(trim("TRACE_NUMBER"::varchar), '') as trace_number,
    "VOLUNTARY_CO_PAY"::number as voluntary_co_pay,
    nullif(trim("ZONE"::varchar), '') as zone
    from {{ source('health_raw', 'BJAZ_HG_POL_DTLS') }}

)

select * from source
