-- Staging model for source table BJAZ_TPA_CLAIM_DETAILS_WS (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("ACCOUNT_NO"::varchar), '') as account_no,
    nullif(trim("ACCOUNT_TYPE"::varchar), '') as account_type,
    nullif(trim("ADDRESS"::varchar), '') as address,
    nullif(trim("AGENT_CODE"::varchar), '') as agent_code,
    "AMBULANCE_CHARGES"::number as ambulance_charges,
    "ANESTHESIA_FEES"::number as anesthesia_fees,
    "APPROVED_AMOUNT"::number as approved_amount,
    nullif(trim("BANK_NAME"::varchar), '') as bank_name,
    nullif(trim("BENEFIT_TYPE"::varchar), '') as benefit_type,
    nullif(trim(to_varchar("BJAZ_CLAIM_ID")), '') as bjaz_claim_id,
    nullif(trim("BJAZ_CLAIM_STATUS"::varchar), '') as bjaz_claim_status,
    nullif(trim("BONUS"::varchar), '') as bonus,
    nullif(trim("BRANCH_IFSC_CODE"::varchar), '') as branch_ifsc_code,
    nullif(trim("BRANCH_MICR_CODE"::varchar), '') as branch_micr_code,
    nullif(trim("CHEQUE_DATE"::varchar), '') as cheque_date,
    nullif(trim(to_varchar("CHEQUE_NO")), '') as cheque_no,
    "CLAIM_AMOUNT"::number as claim_amount,
    nullif(trim("CLAIM_CATEGORY"::varchar), '') as claim_category,
    nullif(trim("CLAIM_TYPE"::varchar), '') as claim_type,
    "COMPULSARY_DEDUCTION"::number as compulsary_deduction,
    nullif(trim(to_varchar("CONTROLLING_OFFICE")), '') as controlling_office,
    "CORPORATE_BUFFER"::number as corporate_buffer,
    "CO_PAY_AMOUNT"::number as co_pay_amount,
    nullif(trim(to_varchar("CUSTOMER_ID")), '') as customer_id,
    nullif(trim("DATE_OF_DOC_REC"::varchar), '') as date_of_doc_rec,
    "DEDUCTED_AMOUNT"::number as deducted_amount,
    nullif(trim("DEDUCTION_REASON"::varchar), '') as deduction_reason,
    nullif(trim("DEVELOPMENT_CODE"::varchar), '') as development_code,
    nullif(trim("DIAGNOSIS"::varchar), '') as diagnosis,
    nullif(trim("DIAGNOSIS_CODE_LEVEL1"::varchar), '') as diagnosis_code_level1,
    nullif(trim("DISC_DATAILS"::varchar), '') as disc_datails,
    nullif(trim("DOA"::varchar), '') as doa,
    nullif(trim("DOD"::varchar), '') as dod,
    nullif(trim("EMAIL_ID_1"::varchar), '') as email_id_1,
    "ESTIMATE_AMT"::number as estimate_amt,
    nullif(trim("FLOAT_DATE"::varchar), '') as float_date,
    nullif(trim("FLOAT_NO"::varchar), '') as float_no,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("HOSPITAL_CITY"::varchar), '') as hospital_city,
    nullif(trim(to_varchar("HOSPITAL_CODE")), '') as hospital_code,
    nullif(trim("HOSPITAL_DISC_DATE"::varchar), '') as hospital_disc_date,
    nullif(trim("HOSPITAL_FINAL_REMINDER_DATE"::varchar), '') as hospital_final_reminder_date,
    nullif(trim("HOSPITAL_NAME"::varchar), '') as hospital_name,
    nullif(trim("HOSPITAL_REMINDER_DATE"::varchar), '') as hospital_reminder_date,
    nullif(trim("HOSPITAL_REPLY_RECIEVED_DATE"::varchar), '') as hospital_reply_recieved_date,
    nullif(trim("HOSPITAL_STATE"::varchar), '') as hospital_state,
    "ICUCHARGES"::number as icucharges,
    nullif(trim("INSURANCE_COMPANY"::varchar), '') as insurance_company,
    nullif(trim("INSURED_DISC_DATE"::varchar), '') as insured_disc_date,
    nullif(trim("INSURED_FINAL_REMINDER_DATE"::varchar), '') as insured_final_reminder_date,
    nullif(trim("INSURED_REMINDER_DATE"::varchar), '') as insured_reminder_date,
    nullif(trim("INSURED_REPLY_RECIEVED_DATE"::varchar), '') as insured_reply_recieved_date,
    nullif(trim("INSURER_DISC_DATE"::varchar), '') as insurer_disc_date,
    nullif(trim("INSURER_FINAL_REMINDER_DATE"::varchar), '') as insurer_final_reminder_date,
    nullif(trim("INSURER_REMINDER_DATE"::varchar), '') as insurer_reminder_date,
    nullif(trim("INSURER_REPLY_RECIEVED_DATE"::varchar), '') as insurer_reply_recieved_date,
    nullif(trim("INS_CITY"::varchar), '') as ins_city,
    nullif(trim("INS_STATE"::varchar), '') as ins_state,
    nullif(trim("INTIMATION_DATE"::varchar), '') as intimation_date,
    "INVESTIGATION_CHARGES"::number as investigation_charges,
    nullif(trim("LOSS_DATE"::varchar), '') as loss_date,
    "MEDICINES"::number as medicines,
    "MISC"::number as misc,
    nullif(trim("MOB_NO"::varchar), '') as mob_no,
    nullif(trim("NEFT_BANK_STATUS"::varchar), '') as neft_bank_status,
    "NET_PAYBLE_AMT"::number as net_payble_amt,
    "NURSING_FEES"::number as nursing_fees,
    "OPERATING_CODE"::number as operating_code,
    nullif(trim(to_varchar("OPERATING_OFFICE")), '') as operating_office,
    "OTCHARGES"::number as otcharges,
    nullif(trim("PAN_NO"::varchar), '') as pan_no,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    "PATIENT_AGE"::number as patient_age,
    nullif(trim("PATIENT_NAME"::varchar), '') as patient_name,
    "PAYBLE_AMOUNT"::number as payble_amount,
    nullif(trim("PAYEE_ADDRESS"::varchar), '') as payee_address,
    nullif(trim("PAYMENT_DATE"::varchar), '') as payment_date,
    nullif(trim("POLICY_FROM"::varchar), '') as policy_from,
    nullif(trim(to_varchar("POLICY_NO")), '') as policy_no,
    nullif(trim("POLICY_TYPE"::varchar), '') as policy_type,
    nullif(trim("POLICY_UPTO"::varchar), '') as policy_upto,
    "PRE_AUTH_AMOUNT"::number as pre_auth_amount,
    nullif(trim("PRE_AUTH_APPROVED_ON"::varchar), '') as pre_auth_approved_on,
    nullif(trim("PRE_AUTH_LETTER_NO"::varchar), '') as pre_auth_letter_no,
    nullif(trim("PRE_AUTH_RECEIVED_ON"::varchar), '') as pre_auth_received_on,
    nullif(trim("PRE_AUTH_STATUS"::varchar), '') as pre_auth_status,
    nullif(trim("PROCEDURE_CODES_LEVEL1"::varchar), '') as procedure_codes_level1,
    nullif(trim("PROCEDURE_DESCRIPTION_LEVEL1"::varchar), '') as procedure_description_level1,
    nullif(trim("PRODUCT_NAME"::varchar), '') as product_name,
    nullif(trim("PROPOSER_NAME"::varchar), '') as proposer_name,
    "RECOMMEND_AMOUNT"::number as recommend_amount,
    nullif(trim("RECOMMEND_ON"::varchar), '') as recommend_on,
    nullif(trim("REJECTION_REASON"::varchar), '') as rejection_reason,
    nullif(trim("RELATION"::varchar), '') as relation,
    "ROOM_CHARGES"::number as room_charges,
    "SERVICE_TAX_AMOUNT"::number as service_tax_amount,
    nullif(trim("SERVICE_TAX_NO"::varchar), '') as service_tax_no,
    nullif(trim("SETTELEMENT_DATE"::varchar), '') as settelement_date,
    nullif(trim("SETTELEMENT_TYPE"::varchar), '') as settelement_type,
    nullif(trim("STATUS"::varchar), '') as status,
    nullif(trim("SUM_INSURED"::varchar), '') as sum_insured,
    "SURGEON_CHARGES"::number as surgeon_charges,
    "TDS_AMOUNT"::number as tds_amount,
    nullif(trim(to_varchar("TPA_CLAIM_NO")), '') as tpa_claim_no,
    nullif(trim("TPA_ID"::varchar), '') as tpa_id,
    nullif(trim(to_varchar("TPA_TRANS_KEY")), '') as tpa_trans_key,
    nullif(trim("TREATMENT"::varchar), '') as treatment
    from {{ source('health_raw', 'BJAZ_TPA_CLAIM_DETAILS_WS') }}

)

select * from source
