/* =====================================================================================
   DM-K3  |  Key checks  |  "No null / blank business keys"
   Sign-off: No null or blank business keys loaded without a default or ghost value;
             ghost / -1 record present per hub.
   Pass:     null_key_status = PASS and ghost_record_status = PASS for every hub (1-19).
             Section 20 is drill-down detail for any FAIL.

   The queries below are IDENTICAL to those in DM-K3.docx (generated by tools/gen_dm_k3.py --
   edit the generator, not this file).

   Ghost record = hash key TO_BINARY(REPEAT('0', 32), 'HEX') OR business key in ('-1', '-2').
   KNOWN GAP: no ghost records / null-key defaults are configured in either project, so
   ghost_record_status is expected to be FAIL until one is added or the gap is accepted
   as a documented exception.

   Schemas used:
     Vault        BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL
     Maximus RAW  BAGIC_PROD_MIRROR_DB.MAXI_RAW
     Opus RAW     BAGIC_PREPROD_CURATED_DB.UTILS   (test; prod = BAGIC_PROD_MIRROR_DB.OPUS_GG_DWHSTAGE)
   ===================================================================================== */

----------------------------------------------------------------------------------------
-- 1. MAXIMUS — HUB_PARTY
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_PARTY' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and PARTY_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(PARTY_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PARTY;

----------------------------------------------------------------------------------------
-- 2. MAXIMUS — HUB_STAKE_CODE
-- Business key column is STAKE_CODE_BK (not PARENT_BK).
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_STAKE_CODE' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and STAKE_CODE_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(STAKE_CODE_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(STAKE_CODE_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(STAKE_CODE_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(STAKE_CODE_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_STAKE_CODE;

----------------------------------------------------------------------------------------
-- 3. MAXIMUS — HUB_LOCATION
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_LOCATION' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and LOCATION_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(LOCATION_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_LOCATION;

----------------------------------------------------------------------------------------
-- 4. MAXIMUS — HUB_PAYMENT_INSTRUMENT
-- PARENT_BK is stored already prefixed ('HUB_PAYMENT_INSTRUMENT|<FOREIGN_KEY>'); a
-- bare prefix with no key value would be a blank key in effect -- counted in
-- prefix_only_bk.
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_PAYMENT_INSTRUMENT' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and PAYMENT_INSTRUMENT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and trim(PARENT_BK) = 'HUB_PAYMENT_INSTRUMENT|')  as prefix_only_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(PAYMENT_INSTRUMENT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0 and prefix_only_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PAYMENT_INSTRUMENT;

----------------------------------------------------------------------------------------
-- 5. MAXIMUS — HUB_PRODUCT
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_PRODUCT' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and PRODUCT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(PRODUCT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PRODUCT;

----------------------------------------------------------------------------------------
-- 6. MAXIMUS — HUB_FINANCIAL_ACCOUNT
-- account_code is cast(null) in staging, so this hub should hold no Maximus rows;
-- rows_in_scope = 0 is expected.
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_FINANCIAL_ACCOUNT' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and FINANCIAL_ACCOUNT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(FINANCIAL_ACCOUNT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_FINANCIAL_ACCOUNT;

----------------------------------------------------------------------------------------
-- 7. MAXIMUS — HUB_DOCUMENT
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_DOCUMENT' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and DOCUMENT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(DOCUMENT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DOCUMENT;

----------------------------------------------------------------------------------------
-- 8. MAXIMUS — HUB_POLICY
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_POLICY' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and POLICY_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(POLICY_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_POLICY;

----------------------------------------------------------------------------------------
-- 9. MAXIMUS — HUB_DISTRIBUTION_CHANNEL
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_DISTRIBUTION_CHANNEL' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and DISTRIBUTION_CHANNEL_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(DISTRIBUTION_CHANNEL_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DISTRIBUTION_CHANNEL;

----------------------------------------------------------------------------------------
-- 10. MAXIMUS — HUB_ORG_UNIT
----------------------------------------------------------------------------------------
select 'MAXIMUS' as project, 'HUB_ORG_UNIT' as hub,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and ORG_UNIT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'MAXIMUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(ORG_UNIT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_ORG_UNIT;

----------------------------------------------------------------------------------------
-- 11. OPUS — HUB_PARTY
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_PARTY' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and PARTY_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(PARTY_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PARTY;

----------------------------------------------------------------------------------------
-- 12. OPUS — HUB_AGENT
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_AGENT' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and AGENT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(AGENT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_AGENT;

----------------------------------------------------------------------------------------
-- 13. OPUS — HUB_AGREEMENT
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_AGREEMENT' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and AGREEMENT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(AGREEMENT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_AGREEMENT;

----------------------------------------------------------------------------------------
-- 14. OPUS — HUB_CLAIM
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_CLAIM' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and CLAIM_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(CLAIM_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_CLAIM;

----------------------------------------------------------------------------------------
-- 15. OPUS — HUB_DISTRIBUTION_CHANNEL
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_DISTRIBUTION_CHANNEL' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and DISTRIBUTION_CHANNEL_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(DISTRIBUTION_CHANNEL_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DISTRIBUTION_CHANNEL;

----------------------------------------------------------------------------------------
-- 16. OPUS — HUB_LOCATION
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_LOCATION' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and LOCATION_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(LOCATION_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_LOCATION;

----------------------------------------------------------------------------------------
-- 17. OPUS — HUB_POLICY
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_POLICY' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and POLICY_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(POLICY_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_POLICY;

----------------------------------------------------------------------------------------
-- 18. OPUS — HUB_PRODUCT
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_PRODUCT' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and PRODUCT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(PRODUCT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PRODUCT;

----------------------------------------------------------------------------------------
-- 19. OPUS — HUB_RISK_OBJECT
----------------------------------------------------------------------------------------
select 'OPUS' as project, 'HUB_RISK_OBJECT' as hub,
       count_if(startswith(RECORD_SOURCE, 'OPUS_'))                                          as rows_in_scope,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and RISK_OBJECT_HKEY is null)                       as null_hkey,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and nullif(trim(PARENT_BK), '') is null)        as null_or_blank_bk,
       count_if(startswith(RECORD_SOURCE, 'OPUS_') and upper(trim(PARENT_BK)) in ('NULL', 'NONE', 'NA', 'N/A', 'UNKNOWN', '0')) as placeholder_bk_info,
       count_if(RISK_OBJECT_HKEY = TO_BINARY(REPEAT('0', 32), 'HEX') or trim(PARENT_BK) in ('-1', '-2'))   as ghost_rows,
       iff(null_hkey = 0 and null_or_blank_bk = 0, 'PASS', 'FAIL')                as null_key_status,
       iff(ghost_rows > 0, 'PASS', 'FAIL')                                                  as ghost_record_status
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_RISK_OBJECT;

----------------------------------------------------------------------------------------
-- 20. MAXIMUS + OPUS — Null / blank key detail (all hubs)
-- Drill-down evidence, not a separate criterion. Expected 0 rows when every
-- null_key_status above is PASS.
----------------------------------------------------------------------------------------
-- Lists every null / blank key row behind a FAIL in sections 1-19.
select 'MAXIMUS' as project, 'HUB_PARTY' as hub, PARTY_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PARTY
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (PARTY_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_STAKE_CODE' as hub, STAKE_CODE_HKEY as hkey, STAKE_CODE_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_STAKE_CODE
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (STAKE_CODE_HKEY is null or nullif(trim(STAKE_CODE_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_LOCATION' as hub, LOCATION_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_LOCATION
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (LOCATION_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_PAYMENT_INSTRUMENT' as hub, PAYMENT_INSTRUMENT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PAYMENT_INSTRUMENT
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (PAYMENT_INSTRUMENT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_PRODUCT' as hub, PRODUCT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PRODUCT
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (PRODUCT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_FINANCIAL_ACCOUNT' as hub, FINANCIAL_ACCOUNT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_FINANCIAL_ACCOUNT
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (FINANCIAL_ACCOUNT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_DOCUMENT' as hub, DOCUMENT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DOCUMENT
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (DOCUMENT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_POLICY' as hub, POLICY_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_POLICY
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (POLICY_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_DISTRIBUTION_CHANNEL' as hub, DISTRIBUTION_CHANNEL_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DISTRIBUTION_CHANNEL
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (DISTRIBUTION_CHANNEL_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'MAXIMUS' as project, 'HUB_ORG_UNIT' as hub, ORG_UNIT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_ORG_UNIT
 where startswith(RECORD_SOURCE, 'MAXIMUS_') and (ORG_UNIT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_PARTY' as hub, PARTY_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PARTY
 where startswith(RECORD_SOURCE, 'OPUS_') and (PARTY_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_AGENT' as hub, AGENT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_AGENT
 where startswith(RECORD_SOURCE, 'OPUS_') and (AGENT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_AGREEMENT' as hub, AGREEMENT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_AGREEMENT
 where startswith(RECORD_SOURCE, 'OPUS_') and (AGREEMENT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_CLAIM' as hub, CLAIM_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_CLAIM
 where startswith(RECORD_SOURCE, 'OPUS_') and (CLAIM_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_DISTRIBUTION_CHANNEL' as hub, DISTRIBUTION_CHANNEL_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_DISTRIBUTION_CHANNEL
 where startswith(RECORD_SOURCE, 'OPUS_') and (DISTRIBUTION_CHANNEL_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_LOCATION' as hub, LOCATION_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_LOCATION
 where startswith(RECORD_SOURCE, 'OPUS_') and (LOCATION_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_POLICY' as hub, POLICY_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_POLICY
 where startswith(RECORD_SOURCE, 'OPUS_') and (POLICY_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_PRODUCT' as hub, PRODUCT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_PRODUCT
 where startswith(RECORD_SOURCE, 'OPUS_') and (PRODUCT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
union all
select 'OPUS' as project, 'HUB_RISK_OBJECT' as hub, RISK_OBJECT_HKEY as hkey, PARENT_BK as bk, RECORD_SOURCE, LOAD_DATETIME
  from BAGIC_PREPROD_CURATED_DB.BGIL_DATA_MODEL.HUB_RISK_OBJECT
 where startswith(RECORD_SOURCE, 'OPUS_') and (RISK_OBJECT_HKEY is null or nullif(trim(PARENT_BK), '') is null)
order by project, hub;
