-- Staging model for source table BJAZ_GRP_HLT_DTLS (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("ALTERNATE_RESPONSIBLE"::varchar), '') as alternate_responsible,
    nullif(trim(to_varchar("BRANCH")), '') as branch,
    nullif(trim("BUSINESS_TYPE"::varchar), '') as business_type,
    nullif(trim("CATEGORY"::varchar), '') as category,
    nullif(trim("CHANNEL"::varchar), '') as channel,
    "CHILDREN_LIMIT"::number as children_limit,
    nullif(trim("COVERAGE"::varchar), '') as coverage,
    nullif(trim(to_varchar("DEPARTMENT")), '') as department,
    nullif(trim("DISCOUNTED_PREMIUM"::varchar), '') as discounted_premium,
    "EFFECTIVE_DATE"::timestamp_ntz as effective_date,
    nullif(trim("EMPR_EMP_RELATION"::varchar), '') as empr_emp_relation,
    nullif(trim("EXCLUSIONS"::varchar), '') as exclusions,
    "EXPIRY_DATE"::timestamp_ntz as expiry_date,
    "EXPIRY_DATE_GPG"::timestamp_ntz as expiry_date_gpg,
    "FINAL_PRM_EX_STAX"::number as final_prm_ex_stax,
    nullif(trim("FLAG_SME"::varchar), '') as flag_sme,
    nullif(trim("HEALTH_PRIME_RIDER_FAM_DEF"::varchar), '') as health_prime_rider_fam_def,
    nullif(trim("HEALTH_PRIME_RIDER_OPT"::varchar), '') as health_prime_rider_opt,
    "HO_DISCOUNT"::number as ho_discount,
    nullif(trim("HPR_DISCLAIMER1"::varchar), '') as hpr_disclaimer1,
    nullif(trim("HPR_DISCLAIMER10"::varchar), '') as hpr_disclaimer10,
    nullif(trim("HPR_DISCLAIMER11"::varchar), '') as hpr_disclaimer11,
    nullif(trim("HPR_DISCLAIMER2"::varchar), '') as hpr_disclaimer2,
    nullif(trim("HPR_DISCLAIMER3"::varchar), '') as hpr_disclaimer3,
    nullif(trim("HPR_DISCLAIMER4"::varchar), '') as hpr_disclaimer4,
    nullif(trim("HPR_DISCLAIMER5"::varchar), '') as hpr_disclaimer5,
    nullif(trim("HPR_DISCLAIMER6"::varchar), '') as hpr_disclaimer6,
    nullif(trim("HPR_DISCLAIMER7"::varchar), '') as hpr_disclaimer7,
    nullif(trim("HPR_DISCLAIMER8"::varchar), '') as hpr_disclaimer8,
    nullif(trim("HPR_DISCLAIMER9"::varchar), '') as hpr_disclaimer9,
    nullif(trim("INDUSTRY_PROFILE"::varchar), '') as industry_profile,
    nullif(trim("INDUSTRY_PROFILE_GPG"::varchar), '') as industry_profile_gpg,
    nullif(trim("INDUSTRY_TYPE"::varchar), '') as industry_type,
    nullif(trim("MEMBER_EMP_HEADER"::varchar), '') as member_emp_header,
    nullif(trim("NME_WAIVER"::varchar), '') as nme_waiver,
    nullif(trim("ORIGINATOR"::varchar), '') as originator,
    nullif(trim("OTHER_CONDITIONS"::varchar), '') as other_conditions,
    nullif(trim("PERSON_RESP"::varchar), '') as person_resp,
    nullif(trim("PER_PERSON_PREM_TYPE"::varchar), '') as per_person_prem_type,
    nullif(trim(to_varchar("POLICY_NO")), '') as policy_no,
    "POLICY_PERIOD"::number as policy_period,
    nullif(trim("POLICY_TYPE"::varchar), '') as policy_type,
    nullif(trim("PP_SUMINSURED"::varchar), '') as pp_suminsured,
    "PREM_QUOTED"::number as prem_quoted,
    nullif(trim("PREV_POL_REF"::varchar), '') as prev_pol_ref,
    nullif(trim("PRE_INSURER_NAME"::varchar), '') as pre_insurer_name,
    nullif(trim(to_varchar("PRODUCT")), '') as product,
    nullif(trim("PRODUCT_NAME"::varchar), '') as product_name,
    nullif(trim("PRV_POLICY_NO"::varchar), '') as prv_policy_no,
    nullif(trim(to_varchar("QUOTE_NO")), '') as quote_no,
    nullif(trim(to_varchar("QUOTE_REF_NO")), '') as quote_ref_no,
    "QUOTE_STATUS"::number as quote_status,
    nullif(trim("QUOTE_STATUS_DESC"::varchar), '') as quote_status_desc,
    nullif(trim(to_varchar("QUOTE_SUB_NO")), '') as quote_sub_no,
    "REGISTER_DATE"::timestamp_ntz as register_date,
    nullif(trim(to_varchar("REG_NO")), '') as reg_no,
    nullif(trim("REMARKS"::varchar), '') as remarks,
    nullif(trim("RISK_DESCRIPTION"::varchar), '') as risk_description,
    nullif(trim(to_varchar("SCRUTINY_NO")), '') as scrutiny_no,
    nullif(trim("SI_COVERAGES"::varchar), '') as si_coverages,
    nullif(trim("STAKE_HOLDER_NAME"::varchar), '') as stake_holder_name,
    "START_DATE"::timestamp_ntz as start_date,
    nullif(trim("STATUS"::varchar), '') as status,
    "TENTATIVE_RISK"::timestamp_ntz as tentative_risk,
    "TOTAL_NO_PROPOSED"::number as total_no_proposed,
    nullif(trim("USER_NAME"::varchar), '') as user_name
    from {{ source('health_raw', 'BJAZ_GRP_HLT_DTLS') }}

)

select * from source
