-- Staging model for source table BJAZ_HM_HOSP_MASTER_EXTN1 (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("ADMINEMAIL"::varchar), '') as adminemail,
    nullif(trim("ADMINMOBILENO"::varchar), '') as adminmobileno,
    nullif(trim("AREA"::varchar), '') as area,
    nullif(trim("BILLINGEMAIL"::varchar), '') as billingemail,
    nullif(trim("BILLINGMOBILENO"::varchar), '') as billingmobileno,
    nullif(trim("BIOMEDWASTE"::varchar), '') as biomedwaste,
    nullif(trim("BLACKLISTREASON"::varchar), '') as blacklistreason,
    nullif(trim("BOYLEAPPR"::varchar), '') as boyleappr,
    nullif(trim("BURN"::varchar), '') as burn,
    nullif(trim("CARDIOLOGY"::varchar), '') as cardiology,
    nullif(trim("CENTROXY"::varchar), '') as centroxy,
    nullif(trim("CENTRSTERIL"::varchar), '') as centrsteril,
    nullif(trim("CEOEMAIL"::varchar), '') as ceoemail,
    nullif(trim("CEOMOBILENO"::varchar), '') as ceomobileno,
    nullif(trim("CODINGPROC"::varchar), '') as codingproc,
    nullif(trim("CRITICALCARE"::varchar), '') as criticalcare,
    nullif(trim("DAYCARE"::varchar), '') as daycare,
    nullif(trim("DELISTEDHOSP"::varchar), '') as delistedhosp,
    nullif(trim("DELISTEDHOSPREASON"::varchar), '') as delistedhospreason,
    nullif(trim("DENTAL"::varchar), '') as dental,
    nullif(trim("DERMATOLOGY"::varchar), '') as dermatology,
    nullif(trim("DIAGCENTER"::varchar), '') as diagcenter,
    nullif(trim("DIPLOMATRAINING"::varchar), '') as diplomatraining,
    nullif(trim("DNBTRAINING"::varchar), '') as dnbtraining,
    nullif(trim("DOCAVAILBLEND"::varchar), '') as docavailblend,
    nullif(trim("DOCAVAILMBBS"::varchar), '') as docavailmbbs,
    nullif(trim("DOCAVAILMDMS"::varchar), '') as docavailmdms,
    nullif(trim("DOCAVAILMEDICINE"::varchar), '') as docavailmedicine,
    nullif(trim("ENDOCRINOLOGY"::varchar), '') as endocrinology,
    nullif(trim("ENT"::varchar), '') as ent,
    nullif(trim("FDAPHARMA"::varchar), '') as fdapharma,
    nullif(trim("FIRESAFETY"::varchar), '') as firesafety,
    nullif(trim("GASTROENTROLOGY"::varchar), '') as gastroentrology,
    nullif(trim("GENERALMEDICINE"::varchar), '') as generalmedicine,
    nullif(trim("GENERALSURGERY"::varchar), '') as generalsurgery,
    nullif(trim("GENITOURINARY"::varchar), '') as genitourinary,
    nullif(trim(to_varchar("HOSID")), '') as hosid,
    nullif(trim("HOSNUNDERNEGO"::varchar), '') as hosnundernego,
    nullif(trim("HOSPCATG"::varchar), '') as hospcatg,
    nullif(trim("HOSPVISITEDBY"::varchar), '') as hospvisitedby,
    nullif(trim("HOSPVISITEDDATE"::varchar), '') as hospvisiteddate,
    nullif(trim("HOSPVISITEDREMARK"::varchar), '') as hospvisitedremark,
    nullif(trim("HOTA"::varchar), '') as hota,
    nullif(trim("ICD10"::varchar), '') as icd10,
    nullif(trim("INCUBATOR"::varchar), '') as incubator,
    nullif(trim("INFECTIOUSDISEASE"::varchar), '') as infectiousdisease,
    nullif(trim("INFECTNCTRL"::varchar), '') as infectnctrl,
    nullif(trim("IPHS"::varchar), '') as iphs,
    nullif(trim("ISO"::varchar), '') as iso,
    nullif(trim("JCI"::varchar), '') as jci,
    nullif(trim("LAMINARFLOW"::varchar), '') as laminarflow,
    nullif(trim("LAPAROSCOPICSURGERY"::varchar), '') as laparoscopicsurgery,
    nullif(trim("MEDDIREMAIL"::varchar), '') as meddiremail,
    nullif(trim("MEDDIRMOB"::varchar), '') as meddirmob,
    nullif(trim("MEDICALAUDIT"::varchar), '') as medicalaudit,
    nullif(trim("MEDICALESTCOV"::varchar), '') as medicalestcov,
    nullif(trim("MEDICALRECORD"::varchar), '') as medicalrecord,
    nullif(trim("MEDSUPERNAMEEMAIL"::varchar), '') as medsupernameemail,
    nullif(trim("MEDSUPERNAMEMOBNO"::varchar), '') as medsupernamemobno,
    nullif(trim("MKTHEADEMAIL"::varchar), '') as mktheademail,
    nullif(trim("MKTHEADMOBILENO"::varchar), '') as mktheadmobileno,
    nullif(trim("MTP"::varchar), '') as mtp,
    nullif(trim("NABHCERTIFIED"::varchar), '') as nabhcertified,
    nullif(trim("NABL"::varchar), '') as nabl,
    nullif(trim("NEPHROLOGY"::varchar), '') as nephrology,
    nullif(trim("NEUROLOGY"::varchar), '') as neurology,
    nullif(trim("NICUBEDS"::varchar), '') as nicubeds,
    nullif(trim("NOACCR"::varchar), '') as noaccr,
    nullif(trim("NOTRAINING"::varchar), '') as notraining,
    nullif(trim("NTOPRATIO"::varchar), '') as ntopratio,
    nullif(trim("NURSEAVAILANM"::varchar), '') as nurseavailanm,
    nullif(trim("NURSEAVAILBLEND"::varchar), '') as nurseavailblend,
    nullif(trim("NURSEAVAILREG"::varchar), '') as nurseavailreg,
    "NURSE_NO_ICU"::number as nurse_no_icu,
    nullif(trim("NURSINGSCH"::varchar), '') as nursingsch,
    nullif(trim("OBSGYNECOLOGY"::varchar), '') as obsgynecology,
    nullif(trim("ONCOLOGY"::varchar), '') as oncology,
    nullif(trim("ONLINEHOSPREF"::varchar), '') as onlinehospref,
    nullif(trim("OPERATINGHRS"::varchar), '') as operatinghrs,
    nullif(trim("OPTHAMOLOGY"::varchar), '') as opthamology,
    nullif(trim("ORTHOPEDICS"::varchar), '') as orthopedics,
    nullif(trim("PCATGHOSP"::varchar), '') as pcatghosp,
    nullif(trim("PEDIATRIC"::varchar), '') as pediatric,
    nullif(trim("PLASTICSURGERY"::varchar), '') as plasticsurgery,
    nullif(trim("PNDT"::varchar), '') as pndt,
    nullif(trim("PORTABLEECG"::varchar), '') as portableecg,
    nullif(trim("PORTABLEXRAY"::varchar), '') as portablexray,
    nullif(trim("POWERBKUP"::varchar), '') as powerbkup,
    nullif(trim("PULMONOLOGY"::varchar), '') as pulmonology,
    nullif(trim("RECOVERYROOMS"::varchar), '') as recoveryrooms,
    nullif(trim("RHEUMATOLOGY"::varchar), '') as rheumatology,
    nullif(trim("SEMITWIN"::varchar), '') as semitwin,
    nullif(trim("STAT_LVL_NQAS"::varchar), '') as stat_lvl_nqas,
    nullif(trim("STEPDWNRMRENT"::varchar), '') as stepdwnrmrent,
    nullif(trim("STERIAREA"::varchar), '') as steriarea,
    nullif(trim("SUIT"::varchar), '') as suit,
    nullif(trim("SUSPENDFOREXT"::varchar), '') as suspendforext,
    nullif(trim("SUSPFRAUD"::varchar), '') as suspfraud,
    "TOT_MBBS_DOCT"::number as tot_mbbs_doct,
    "TOT_NO_DOCT"::number as tot_no_doct,
    "TOT_NO_NURSE"::number as tot_no_nurse,
    "TOT_NO_SURGEN"::number as tot_no_surgen,
    nullif(trim("TPAEMAIL"::varchar), '') as tpaemail,
    nullif(trim("TRAUMA"::varchar), '') as trauma,
    nullif(trim("TRFVALFROM"::varchar), '') as trfvalfrom,
    nullif(trim("TRFVALTO"::varchar), '') as trfvalto,
    nullif(trim("TRIPPLESHARING"::varchar), '') as tripplesharing,
    nullif(trim("ULTRASOUDREG"::varchar), '') as ultrasoudreg,
    "VISIT_CONSLNT"::number as visit_conslnt,
    nullif(trim("WELLCENTER"::varchar), '') as wellcenter
    from {{ source('health_raw', 'BJAZ_HM_HOSP_MASTER_EXTN1') }}

)

select * from source
