-- Staging model for source table BA_HCP_DT_PREMIUM (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    "ADDITIONAL_LOAD_AMT"::number as additional_load_amt,
    "ADDITIONAL_LOAD_RATE"::number as additional_load_rate,
    "ADDON_COV_DISC_AMT"::number as addon_cov_disc_amt,
    "ADDON_COV_DISC_RATE"::number as addon_cov_disc_rate,
    nullif(trim("BUSS_TYPE"::varchar), '') as buss_type,
    "CD_AMT"::number as cd_amt,
    "CD_RATE"::number as cd_rate,
    "CLAIM_FREE_RENEWAL_DISC_AMT"::number as claim_free_renewal_disc_amt,
    "CLAIM_FREE_RENEWAL_DISC_RATE"::number as claim_free_renewal_disc_rate,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    "CUMULATIVE_BONUS_AMT"::number as cumulative_bonus_amt,
    "CUMULATIVE_BONUS_RATE"::number as cumulative_bonus_rate,
    "DIRECT_CUST_DISC_AMT"::number as direct_cust_disc_amt,
    "DIRECT_CUST_DISC_RATE"::number as direct_cust_disc_rate,
    "DISC_IN_LIEU_AGENCY_COMM_AMT"::number as disc_in_lieu_agency_comm_amt,
    "DISC_IN_LIEU_AGENCY_COMM_RATE"::number as disc_in_lieu_agency_comm_rate,
    nullif(trim("EMI_CESS1"::varchar), '') as emi_cess1,
    nullif(trim("EMI_CESS2"::varchar), '') as emi_cess2,
    nullif(trim("EMI_CESS3"::varchar), '') as emi_cess3,
    nullif(trim("EMI_CGST"::varchar), '') as emi_cgst,
    nullif(trim("EMI_COLLECTED_AMOUNT"::varchar), '') as emi_collected_amount,
    nullif(trim("EMI_EDU_CESS"::varchar), '') as emi_edu_cess,
    nullif(trim("EMI_IGST"::varchar), '') as emi_igst,
    nullif(trim("EMI_KKC"::varchar), '') as emi_kkc,
    nullif(trim("EMI_NCC"::varchar), '') as emi_ncc,
    nullif(trim("EMI_NET_PREM_SELECTED"::varchar), '') as emi_net_prem_selected,
    nullif(trim("EMI_SB_TAX"::varchar), '') as emi_sb_tax,
    nullif(trim("EMI_SER_TAX"::varchar), '') as emi_ser_tax,
    nullif(trim("EMI_SGST"::varchar), '') as emi_sgst,
    nullif(trim("EMI_TOTAL_PREM_SELECTED"::varchar), '') as emi_total_prem_selected,
    nullif(trim("EMI_UTGST"::varchar), '') as emi_utgst,
    "EMP_DISC_AMT"::number as emp_disc_amt,
    "EMP_DISC_RATE"::number as emp_disc_rate,
    "FAMILY_DISC_AMT"::number as family_disc_amt,
    "FAMILY_DISC_RATE"::number as family_disc_rate,
    "GOOD_HEALTH_DISC_AMT"::number as good_health_disc_amt,
    "GOOD_HEALTH_DISC_RATE"::number as good_health_disc_rate,
    nullif(trim(to_varchar("HCP_SEQNO")), '') as hcp_seqno,
    nullif(trim("INST_BASE_AMT"::varchar), '') as inst_base_amt,
    nullif(trim("INST_DATE"::varchar), '') as inst_date,
    nullif(trim("INST_NO"::varchar), '') as inst_no,
    nullif(trim("INST_PAID_AMT"::varchar), '') as inst_paid_amt,
    nullif(trim("INST_TOTAL_PENDING_AMT"::varchar), '') as inst_total_pending_amt,
    "LOADING_AMT"::number as loading_amt,
    "LOADING_RATE"::number as loading_rate,
    "LONG_TERM_POLICY_DISC"::number as long_term_policy_disc,
    "LONG_TERM_POLICY_DISC_AMT"::number as long_term_policy_disc_amt,
    nullif(trim("MEMBER_COMBO"::varchar), '') as member_combo,
    nullif(trim("NEXT_INST_AMT"::varchar), '') as next_inst_amt,
    "ONLINE_DISC_AMT"::number as online_disc_amt,
    "ONLINE_DISC_RATE"::number as online_disc_rate,
    nullif(trim("POL_GROSS_PREM_AMT"::varchar), '') as pol_gross_prem_amt,
    nullif(trim("POL_NET_PREM_AMT"::varchar), '') as pol_net_prem_amt,
    nullif(trim(to_varchar("PRODUCT_CODE")), '') as product_code,
    nullif(trim("SERVICE_TAX_EXEMPTION"::varchar), '') as service_tax_exemption,
    "SP_DISC_AMT"::number as sp_disc_amt,
    "SP_DISC_RATE"::number as sp_disc_rate,
    nullif(trim("TOTAL_MEMBER_NOS"::varchar), '') as total_member_nos,
    "TOTAL_PREM_ON_BASE_COV"::number as total_prem_on_base_cov,
    "TOTAL_PREM_ON_BASE_COV_ADDON"::number as total_prem_on_base_cov_addon,
    nullif(trim(to_varchar("USER_ID")), '') as user_id,
    "UW_LOADING_AMT"::number as uw_loading_amt,
    "UW_LOADING_RATE"::number as uw_loading_rate,
    "VOLUNTARY_DEDUCT_AMT"::number as voluntary_deduct_amt,
    "VOLUNTARY_DEDUCT_RATE"::number as voluntary_deduct_rate
    from {{ source('health_raw', 'BA_HCP_DT_PREMIUM') }}

)

select * from source
