-- Staging model for source table BA_HCP_PROD_8433_FHC_LOADER (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("EXCLUSION_WORDING"::varchar), '') as exclusion_wording,
    nullif(trim("GSTIN_UIN"::varchar), '') as gstin_uin,
    nullif(trim("HEALTH_QUESTION_1"::varchar), '') as health_question_1,
    nullif(trim("HEALTH_QUESTION_2"::varchar), '') as health_question_2,
    nullif(trim("MD_ASTHMA"::varchar), '') as md_asthma,
    nullif(trim("MD_BMI"::varchar), '') as md_bmi,
    nullif(trim("MD_CHOLESTEROL_DISORDERS"::varchar), '') as md_cholesterol_disorders,
    nullif(trim("MD_DATE_OF_BIRTH"::varchar), '') as md_date_of_birth,
    nullif(trim("MD_DIABETES"::varchar), '') as md_diabetes,
    nullif(trim("MD_FAMILY_MEM_COMBINATION"::varchar), '') as md_family_mem_combination,
    nullif(trim("MD_FIRST_NAME"::varchar), '') as md_first_name,
    nullif(trim("MD_GENDER"::varchar), '') as md_gender,
    nullif(trim("MD_GROSS_MONTHLY_INCOME"::varchar), '') as md_gross_monthly_income,
    nullif(trim("MD_HEART_DISEASES"::varchar), '') as md_heart_diseases,
    nullif(trim("MD_HEIGHT_CM"::varchar), '') as md_height_cm,
    nullif(trim("MD_HYPERTENSION"::varchar), '') as md_hypertension,
    nullif(trim("MD_IS_PROPOSER_YES_NO"::varchar), '') as md_is_proposer_yes_no,
    nullif(trim("MD_LAST_NAME"::varchar), '') as md_last_name,
    nullif(trim("MD_MIDDLE_NAME"::varchar), '') as md_middle_name,
    nullif(trim("MD_NOMINEE_RELATION"::varchar), '') as md_nominee_relation,
    nullif(trim("MD_OBESITY"::varchar), '') as md_obesity,
    nullif(trim("MD_OCCUPATION"::varchar), '') as md_occupation,
    nullif(trim("MD_PRE_EXIST_DISEASE_DIS_INF"::varchar), '') as md_pre_exist_disease_dis_inf,
    nullif(trim("MD_RELATION"::varchar), '') as md_relation,
    nullif(trim(to_varchar("MD_SEQ_NO")), '') as md_seq_no,
    nullif(trim("MD_SMOKER_TOBACCO_CHEWER"::varchar), '') as md_smoker_tobacco_chewer,
    nullif(trim("MD_WEIGHT_KG"::varchar), '') as md_weight_kg,
    nullif(trim("PD_ADDRESS_LINE_1"::varchar), '') as pd_address_line_1,
    nullif(trim("PD_ADDRESS_LINE_2"::varchar), '') as pd_address_line_2,
    nullif(trim("PD_ADHAR_CARD_NO"::varchar), '') as pd_adhar_card_no,
    nullif(trim("PD_AGENT_EMAIL_ID"::varchar), '') as pd_agent_email_id,
    nullif(trim("PD_AREA_AS_PER_PF"::varchar), '') as pd_area_as_per_pf,
    nullif(trim("PD_AREA_POST_OFFICE"::varchar), '') as pd_area_post_office,
    nullif(trim(to_varchar("PD_BAGIC_RM_E_CODE")), '') as pd_bagic_rm_e_code,
    nullif(trim("PD_BAGIC_RM_NAME"::varchar), '') as pd_bagic_rm_name,
    nullif(trim(to_varchar("PD_BANK_REF_NO1_LAC_SAC")), '') as pd_bank_ref_no1_lac_sac,
    nullif(trim("PD_BUSINESS_TYPE"::varchar), '') as pd_business_type,
    nullif(trim("PD_CITY"::varchar), '') as pd_city,
    nullif(trim("PD_COUNTRY"::varchar), '') as pd_country,
    nullif(trim("PD_CUSTOMER_CONSENT"::varchar), '') as pd_customer_consent,
    nullif(trim("PD_ELECTRONIC_INSUR_ACCOUNT_NO"::varchar), '') as pd_electronic_insur_account_no,
    nullif(trim("PD_EMAIL"::varchar), '') as pd_email,
    nullif(trim("PD_FAX"::varchar), '') as pd_fax,
    nullif(trim(to_varchar("PD_IMD_CODE")), '') as pd_imd_code,
    nullif(trim(to_varchar("PD_IMD_RM_E_CODE")), '') as pd_imd_rm_e_code,
    nullif(trim("PD_IMD_RM_NAME"::varchar), '') as pd_imd_rm_name,
    nullif(trim(to_varchar("PD_LOCATION_CODE")), '') as pd_location_code,
    nullif(trim("PD_MOBILE_NUMBER"::varchar), '') as pd_mobile_number,
    nullif(trim("PD_PAN_NO"::varchar), '') as pd_pan_no,
    nullif(trim(to_varchar("PD_PARTNER_ID")), '') as pd_partner_id,
    nullif(trim("PD_PARTNER_TYPE"::varchar), '') as pd_partner_type,
    nullif(trim("PD_PAYMENT_MODE"::varchar), '') as pd_payment_mode,
    nullif(trim("PD_PIN_CODE"::varchar), '') as pd_pin_code,
    nullif(trim("PD_POLICY_PERIOD"::varchar), '') as pd_policy_period,
    nullif(trim("PD_PREMIUM_INCLUDING_ST"::varchar), '') as pd_premium_including_st,
    nullif(trim(to_varchar("PD_PREMIUM_PAYER_ID")), '') as pd_premium_payer_id,
    nullif(trim(to_varchar("PD_PRODUCT_CODE")), '') as pd_product_code,
    nullif(trim("PD_RECEIPT_NO"::varchar), '') as pd_receipt_no,
    nullif(trim("PD_RISK_END_DATE"::varchar), '') as pd_risk_end_date,
    nullif(trim("PD_RISK_INCEPTION_DATE"::varchar), '') as pd_risk_inception_date,
    nullif(trim("PD_RISK_INCEPTION_TIME_HHMM"::varchar), '') as pd_risk_inception_time_hhmm,
    nullif(trim(to_varchar("PD_SCRUTINY_NUMBER")), '') as pd_scrutiny_number,
    nullif(trim("PD_STATE"::varchar), '') as pd_state,
    nullif(trim("PD_SUB_IMD_CODE"::varchar), '') as pd_sub_imd_code,
    nullif(trim("PD_TELEPHONE"::varchar), '') as pd_telephone,
    nullif(trim("PLAN_NAME"::varchar), '') as plan_name,
    nullif(trim("PLAN_OPTION"::varchar), '') as plan_option,
    nullif(trim("PLC_CB_AMOUNT"::varchar), '') as plc_cb_amount,
    nullif(trim("PLC_CB_PER"::varchar), '') as plc_cb_per,
    nullif(trim("PLC_HOSP_CASH_PER_DAY_BENEFIT"::varchar), '') as plc_hosp_cash_per_day_benefit,
    nullif(trim("PLC_HOSP_CASH_SI"::varchar), '') as plc_hosp_cash_si,
    nullif(trim("PLC_INPAT_HOSP_TREAT_PLAN"::varchar), '') as plc_inpat_hosp_treat_plan,
    nullif(trim("PLC_INPAT_HOSP_TREAT_SI"::varchar), '') as plc_inpat_hosp_treat_si,
    nullif(trim("PLC_INSTITUTION_NAME"::varchar), '') as plc_institution_name,
    nullif(trim("PLC_RE_INSURANCE"::varchar), '') as plc_re_insurance,
    nullif(trim("PLC_SPECIAL_TERMS_CONDITIONS"::varchar), '') as plc_special_terms_conditions,
    nullif(trim(to_varchar("POLICY_REF")), '') as policy_ref,
    nullif(trim(to_varchar("POL_SERIAL_NO")), '') as pol_serial_no
    from {{ source('health_raw', 'BA_HCP_PROD_8433_FHC_LOADER') }}

)

select * from source
