-- Staging model for source table BJAZ_HM_HOSPITAL_MASTER_EXTN (Health LOB).
-- Casting: VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP -> TIMESTAMP_NTZ.
-- Key columns (hub/link/composite-key components) -> canonical trimmed VARCHAR regardless of
-- native type, for stable hashing. See docs/HEALTH_DV_BUILD_NOTES.md "Key normalisation".

with source as (

    select
    nullif(trim("ACCOUNT_NO"::varchar), '') as account_no,
    nullif(trim("ACCOUNT_TYPE"::varchar), '') as account_type,
    "AGREEMENT_EXP_DATE"::timestamp_ntz as agreement_exp_date,
    nullif(trim("AMBULANCE"::varchar), '') as ambulance,
    nullif(trim("BANK_NAME"::varchar), '') as bank_name,
    nullif(trim("BILL_REC_TIME"::varchar), '') as bill_rec_time,
    nullif(trim("BIOCHEMISTRY"::varchar), '') as biochemistry,
    nullif(trim("BLOOD_BANK"::varchar), '') as blood_bank,
    nullif(trim("BRONCHOSCOPY_LAB"::varchar), '') as bronchoscopy_lab,
    nullif(trim("BR_MICR_CODE"::varchar), '') as br_micr_code,
    nullif(trim("CATH_LAB"::varchar), '') as cath_lab,
    nullif(trim("CHEMOTHERAPY_UNIT"::varchar), '') as chemotherapy_unit,
    nullif(trim("CHEQUE_IN_FAVOUR"::varchar), '') as cheque_in_favour,
    "CITY_CLASS"::number as city_class,
    nullif(trim("CLAIM_PYMT_TAT"::varchar), '') as claim_pymt_tat,
    nullif(trim("CLINIC_PATHOLOGY"::varchar), '') as clinic_pathology,
    nullif(trim("CLOSURE_BY"::varchar), '') as closure_by,
    nullif(trim("COBALT_UNIT"::varchar), '') as cobalt_unit,
    nullif(trim("COUNTRY_NAME"::varchar), '') as country_name,
    "CREDIT_PERIOD"::number as credit_period,
    nullif(trim("CR_CARD_ACCEPTED"::varchar), '') as cr_card_accepted,
    nullif(trim("CT_SCAN"::varchar), '') as ct_scan,
    "DELUXE_BEDS"::number as deluxe_beds,
    nullif(trim("DIALYSIS_UNIT"::varchar), '') as dialysis_unit,
    nullif(trim(to_varchar("DISTRIBUTION_PARTNER")), '') as distribution_partner,
    nullif(trim("DSA"::varchar), '') as dsa,
    nullif(trim("ECG"::varchar), '') as ecg,
    nullif(trim("ECHO"::varchar), '') as echo,
    nullif(trim("EEG"::varchar), '') as eeg,
    nullif(trim("EMAIL_FIN_DEPT"::varchar), '') as email_fin_dept,
    nullif(trim("EMERGENCY"::varchar), '') as emergency,
    nullif(trim("EMG"::varchar), '') as emg,
    nullif(trim("FAX_NO2"::varchar), '') as fax_no2,
    "FRAUD_TYPE"::number as fraud_type,
    nullif(trim("GAMMA_KNIFE"::varchar), '') as gamma_knife,
    "GENERAL_WARD_BEDS"::number as general_ward_beds,
    nullif(trim("HEMATOLOGY"::varchar), '') as hematology,
    nullif(trim("HOLTER"::varchar), '') as holter,
    nullif(trim(to_varchar("HOSID")), '') as hosid,
    nullif(trim("HOSPITAL_GRADE"::varchar), '') as hospital_grade,
    "ICU_BEDS"::number as icu_beds,
    nullif(trim("IFSC_CODE_NEFT"::varchar), '') as ifsc_code_neft,
    nullif(trim("INHOUSE_PHARMACY"::varchar), '') as inhouse_pharmacy,
    nullif(trim("INITIATED_BY"::varchar), '') as initiated_by,
    nullif(trim("INTEREST_CLAUSE"::varchar), '') as interest_clause,
    nullif(trim("IRDA_UNIQUE_ID"::varchar), '') as irda_unique_id,
    nullif(trim("ISOLATION_WARDS"::varchar), '') as isolation_wards,
    nullif(trim("LANDMARK_1"::varchar), '') as landmark_1,
    nullif(trim("LASERS"::varchar), '') as lasers,
    nullif(trim("LATITUDE"::varchar), '') as latitude,
    nullif(trim("LEGAL_CONST"::varchar), '') as legal_const,
    nullif(trim("LONGITUDE"::varchar), '') as longitude,
    nullif(trim("LR_ACCELERATOR"::varchar), '') as lr_accelerator,
    "MOBILE_NO"::number as mobile_no,
    "MOB_FIN_OFFICER"::number as mob_fin_officer,
    "MOU_FROM_DATE"::timestamp_ntz as mou_from_date,
    "MOU_REVISION_DATE"::timestamp_ntz as mou_revision_date,
    "MOU_TO_DATE"::timestamp_ntz as mou_to_date,
    nullif(trim("MRI"::varchar), '') as mri,
    nullif(trim("NAME_BANK_ACCOUNT"::varchar), '') as name_bank_account,
    "NO_OPRN_THEATRES"::number as no_oprn_theatres,
    nullif(trim("PACKAGE_RATES"::varchar), '') as package_rates,
    nullif(trim("PFT_SPIROMETRY"::varchar), '') as pft_spirometry,
    nullif(trim("PHONE_NO2"::varchar), '') as phone_no2,
    nullif(trim("PHOTOTHERAPY"::varchar), '') as phototherapy,
    nullif(trim("PHYSIOTHERAPY"::varchar), '') as physiotherapy,
    "PPN_TYPE"::number as ppn_type,
    "PP_DISCOUNT1"::number as pp_discount1,
    "PP_DISCOUNT10"::number as pp_discount10,
    "PP_DISCOUNT11"::number as pp_discount11,
    "PP_DISCOUNT12"::number as pp_discount12,
    "PP_DISCOUNT2"::number as pp_discount2,
    "PP_DISCOUNT3"::number as pp_discount3,
    "PP_DISCOUNT4"::number as pp_discount4,
    "PP_DISCOUNT5"::number as pp_discount5,
    "PP_DISCOUNT6"::number as pp_discount6,
    "PP_DISCOUNT7"::number as pp_discount7,
    "PP_DISCOUNT8"::number as pp_discount8,
    "PP_DISCOUNT9"::number as pp_discount9,
    nullif(trim("PP_DISC_SERVICES1"::varchar), '') as pp_disc_services1,
    nullif(trim("PP_DISC_SERVICES10"::varchar), '') as pp_disc_services10,
    nullif(trim("PP_DISC_SERVICES11"::varchar), '') as pp_disc_services11,
    nullif(trim("PP_DISC_SERVICES12"::varchar), '') as pp_disc_services12,
    nullif(trim("PP_DISC_SERVICES2"::varchar), '') as pp_disc_services2,
    nullif(trim("PP_DISC_SERVICES3"::varchar), '') as pp_disc_services3,
    nullif(trim("PP_DISC_SERVICES4"::varchar), '') as pp_disc_services4,
    nullif(trim("PP_DISC_SERVICES5"::varchar), '') as pp_disc_services5,
    nullif(trim("PP_DISC_SERVICES6"::varchar), '') as pp_disc_services6,
    nullif(trim("PP_DISC_SERVICES7"::varchar), '') as pp_disc_services7,
    nullif(trim("PP_DISC_SERVICES8"::varchar), '') as pp_disc_services8,
    nullif(trim("PP_DISC_SERVICES9"::varchar), '') as pp_disc_services9,
    nullif(trim("RAD_IMM_ASSAY_RIA"::varchar), '') as rad_imm_assay_ria,
    nullif(trim("REFERRAL_BY"::varchar), '') as referral_by,
    nullif(trim("REG_NO"::varchar), '') as reg_no,
    nullif(trim("ROHINI_CODE"::varchar), '') as rohini_code,
    "SINGLE_AC_BEDS"::number as single_ac_beds,
    "SINGLE_NONAC_BEDS"::number as single_nonac_beds,
    nullif(trim("SUSPFRAUD"::varchar), '') as suspfraud,
    nullif(trim("TAN_NO"::varchar), '') as tan_no,
    "TARIFF_FROM_DATE"::timestamp_ntz as tariff_from_date,
    "TARIFF_TO_DATE"::timestamp_ntz as tariff_to_date,
    "TOTAL_BEDS"::number as total_beds,
    nullif(trim("TREAD_MILL_TEST"::varchar), '') as tread_mill_test,
    nullif(trim("TYPE_OF_MOU"::varchar), '') as type_of_mou,
    nullif(trim("ULTRASOUND"::varchar), '') as ultrasound,
    nullif(trim("X_KNIFE"::varchar), '') as x_knife,
    nullif(trim("X_RAY"::varchar), '') as x_ray,
    "YEAR_EMPANELMENT"::timestamp_ntz as year_empanelment,
    nullif(trim("ZONE_NAME"::varchar), '') as zone_name
    from {{ source('health_raw', 'BJAZ_HM_HOSPITAL_MASTER_EXTN') }}

)

select * from source
