////////////////////////////////////////// UTILS /////////////////////////////////////////////////
SELECT CONCAT('SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.',table_name, ' LIMIT 1;')
FROM BAGIC_PROD_MIRROR_DB.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'MAXI_RAW'
AND table_name LIKE 'MAXI_HLTH_UWR_VW_DATA%';


SELECT query_id,
       query_text,
       total_elapsed_time,
       execution_time,
       queued_overload_time,
       queued_provisioning_time,
       queued_repair_time
FROM snowflake.account_usage.query_history
WHERE parent_query_id = '01c23352-0001-8b98-0006-86021eda0b22';
CREATE OR REPLACE VIEW BAGIC_PROD_STAGING_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW AS SELECT * FROM ( SELECT s.*, ROW_NUMBER() OVER ( PARTITION BY s.DATA:policyDetails.quotationNumber::STRING ORDER BY s.FILE_TIMESTAMP DESC ) AS rn FROM BAGIC_PROD_STAGING_DB.MAXI_RAW.NONHLTH_TRV_UWR s WHERE s.FILE_TIMESTAMP > (SELECT LAST_MODIFIED_DATE FROM EMPOWER_DB.UTILS.MAXI_RAW_STATE_TABLE WHERE TABLE_NAME = 'NONHLTH_TRV_UWR') AND s.DATA:policyDetails.quotationNumber IS NOT NULL ) WHERE rn = 1;

select count(*)from BAGIC_PROD_mirror_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_data  where date(inc_job_created_at) = '2026-02-05';

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

-- LAST VALIDATED ON  13-04-2026

-- NONHLTH_TRV_CLM

-- OLD KEYS : claimDetails.claimAttribute.properties,claimDetails.claimEventFollowup,claimDetails.claimPayment.paymentproperty,claimDetails.claimReserve,claimDetails.claimCover.multiSetDetail.property,claimDetails.claimRisk.riskAttribute.multiSetProperty,claimDetails.claimRisk.riskAttribute.multiSetProperty.multiSetDetail.property,claimDetails.claimRisk.riskAttribute.properties,claimDetails.claimRiskParty,claimDetails.documentDetails,claimDetails.claimHistory,claimDetails.claimParty,claimDetails.claimAttribute.multiSetProperty.multiSetDetail.property


-- NEWLY ADDED VARIANT KEYS : 

-- INVALID VARIANT KEYS : 1.(getting empty list = []) --> claimDetails.claimNotes,claimDetails.claimNotificationDetails,claimDetails.claimSurveyorDeputation,claimDetails.claimTriggerDetails,claimDetails.claimParty.ptyattr.properties,claimDetails.claimRiskParty.ptyattr.properties

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_METADATA LIMIT 1

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA limit 100;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS WHERE  ARRAY_SIZE("CLAIM_NOTES") > 0 OR ARRAY_SIZE("CLAIM_NOTIFICATION_DETAILS") OR ARRAY_SIZE("CLAIM_SURVEYOR_DEPUTATION") > 0 OR ARRAY_SIZE("CLAIM_TRIGGER_DETAILS") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PARTY WHERE ARRAY_SIZE(TRY_PARSE_JSON(PTYATTR:properties)) > 0
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_HISTORY limit 100;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS WHERE CLAIM_TRIGGER_DETAILS != '[]'
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_EVENT_FOLLOWUP
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PAYMENT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PAYMENT_PAYMENTPROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RESERVE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY WHERE ARRAY_SIZE(TRY_PARSE_JSON(PTYATTR:properties)) > 0
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_DOCUMENT_DETAILS

-- AFTER CODE REVIEW DELETE IT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER_MULTI_SET_DETAIL_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_METADATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_CLM_VW_DATA_METADATA

////////////////////////////////////////////////////

-- LAST VALIDATED ON : 13-04-2026

-- NONHLTH_TRV_UWR

-- OLD KEYS : premiumDetails,policyDetails.dispatchDetails,policyDetails.endorsementDetails,policyDetails.policyPaymentInformation,policyDetails.documentDetails,policyDetails.policyRelation,policyDetails.teleVerificationDetails,policyDetails.workItemDetails,policyDetails.previousPolicyDetails,policyDetails.policyProperty.simpleProperty,policyDetails.proposerDetails.documentDetail,policyDetails.proposerDetails.partyRelation,policyDetails.officeDetails.officeAddress.addressProperty,policyDetails.insuredDetails.documentDetails,policyDetails.insuredDetails.memberDetails.documentDetail,policyDetails.insuredDetails.memberDetails.partyRelation,policyDetails.insuredDetails.memberDetails.partyAddress.addressProperty,policyDetails.insuredDetails.memberDetails.partyProperty.simpleProperty,policyDetails.insuredDetails.memberDetails.partyProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.riskProperty.simpleProperty,policyDetails.insuredDetails.riskProperty.multiSetProperty.multiSetDetail.property,policyDetails.policyProperty.multiSetProperty.multiSetDetail.property,policyDetails.proposerDetails.partyAddress.addressProperty,policyDetails.proposerDetails.partyProperty.simpleProperty,policyDetails.proposerDetails.partyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.riskList.riskProperty.ruleList,quoteParamDetails.riskList.riskCover.riskCoverProperty.ruleList,quoteParamDetails.policyProperty.ruleList,quoteParamDetails.policyProperty.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.coverDetails.coverProperty.simpleProperty,quoteParamDetails.riskList.multiSetPropertyInput.multiSetDetailInput.property

-- NEWLY ADDED KEYS  : 

-- INVALID VARIANT KEYS : 1.(getting empty list = []) --> policyDetails.insuredDetails.memberDetails.relatedParty,policyDetails.proposerDetails.relatedParty

-- GETTING ALL ROWS NULL : quoteParamDetails.partyDetails,quoteParamDetails.polPropPropList,quoteParamDetails.riskList.partyDetails,quoteParamDetails.additionalPartyList,quoteParamDetails.buildingDetails

SELECT AVG(TOTAL_RECORDS) , MIN(TOTAL_RECORDS), MAX(TOTAL_RECORDS)  FROM(
SELECT DATE(FILE_TIMESTAMP), COUNT(*) AS TOTAL_RECORDS FROM BAGIC_PROD_STAGING_DB.MAXI_RAW.NONHLTH_TRV_UWR GROUP BY DATE(FILE_TIMESTAMP) ORDER BY DATE(FILE_TIMESTAMP) DESC);

SELECT AVG(TOTAL_RECORDS) , MIN(TOTAL_RECORDS), MAX(TOTAL_RECORDS)  FROM(
SELECT DATE(FILE_TIMESTAMP), COUNT(*) AS TOTAL_RECORDS FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA GROUP BY DATE(FILE_TIMESTAMP) ORDER BY DATE(FILE_TIMESTAMP) DESC);

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY WHERE FOREIGN_KEY = '11-9910-0015687863-00'


SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_DISPATCH_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_DOCUMENT_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_ENDORSEMENT_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS WHERE nvl(SUM_INSURED, 'null') != 'null' ;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_SIMPLE_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_MULTI_SET_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_DOCUMENT_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS WHERE ARRAY_SIZE(RELATED_PARTY) > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_CLONE_20260119092042451
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_DOCUMENT_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_ADDRESS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_RELATION;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_SIMPLE_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS_ADDRESS_PROPERTY; 
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PAYMENT_INFORMATION;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_SIMPLE_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_RELATION;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PREVIOUS_POLICY_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS WHERE ARRAY_SIZE(RELATED_PARTY)>0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_DOCUMENT_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_RELATION;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_TELE_VERIFICATION_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_WORK_ITEM_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_PREMIUM_DETAILS WHERE TYPEOF(PREMCALC_DETAIL) != 'NULL_VALUE' OR TYPEOF(TAX_DETAIL) != 'NULL_VALUE';
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS WHERE nvl(ADDITIONAL_PARTY_LIST, 'null') != 'null' OR nvl(BUILDING_DETAILS, 'null') != 'null' OR nvl(PARTY_DETAILS, 'null') != 'null' OR nvl(POL_PROP_PROP_LIST, 'null') != 'null';
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_RULE_LIST;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY_RULE_LIST;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY_RULE_LIST;

/////////////////////////////////////////////////////////////////////////////////////////////////

-- BUSINESS_PARTNERS

-- ALL POSSIBLE VARIANT KEYS ADEED

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_METADATA  WHERE KEY_TYPE = 'VARIANT';

SELECT distinct date_trunc('day', inc_job_created_at), date_trunc('day', rec_refresh_at) FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA where date_trunc('day', inc_job_created_at) != date_trunc('day', rec_refresh_at)

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_DOCUMENT_DETAIL LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_ADDRESS LIMIT 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_ADDRESS_ADDRESS_PROPERTY LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_MULTI_SET_PROPERTY LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_SIMPLE_PROPERTY LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_RELATION LIMIT 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_RELATED_PARTY LIMIT 10

///////////////////////////////////////////////////////////

-- LAST VALIDATED ON : 13-04-2026

-- MAXI_CAT_CLM

-- OLD VARIANT KEYS : claimDetails.claimAttribute.multiSetProperty,claimDetails.claimAttribute.properties,claimDetails.claimEventFollowup,claimDetails.claimParty.ptyattr,claimDetails.claimReserve,claimDetails.claimRisk.riskAttribute.multiSetProperty,claimDetails.claimRisk.riskAttribute.properties,claimDetails.documentDetails

-- NEWLY ADDED KEYS : claimDetails.claimPayment.paymentproperty,claimDetails.claimRiskParty.ptyattr

-- INVALID VARIANT KEYS : 1.(getting empty list = []) --> claimDetails.claimCover.multiSetDetail.property,claimDetails.claimHistory,claimDetails.claimNotes,claimDetails.claimSurveyorDeputation,claimDetails.claimNotificationDetails,claimDetails.claimTriggerDetails,claimDetails.claimAttribute.multiSetProperty.multiSetDetail.property,claimDetails.claimParty.ptyattr.properties,claimDetails.claimRiskParty.ptyattr.properties

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_METADATA WHERE KEY_TYPE = 'VARIANT';

SELECT distinct foreign_key FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS WHERE ARRAY_SIZE("CLAIM_COVER") > 0 OR ARRAY_SIZE("CLAIM_HISTORY") > 0 OR ARRAY_SIZE("CLAIM_NOTES") > 0 OR ARRAY_SIZE("CLAIM_SURVEYOR_DEPUTATION") > 0 OR ARRAY_SIZE("CLAIM_NOTIFICATION_DETAILS") > 0 OR ARRAY_SIZE("CLAIM_TRIGGER_DETAILS") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_EVENT_FOLLOWUP
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PARTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY_PTYATTR;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY_PTYATTR WHERE ARRAY_SIZE("PROPERTIES") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RESERVE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY WHERE 
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY WHERE ARRAY_SIZE("MULTI_SET_DETAIL") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_CLM_VW_DATA_CLAIM_DETAILS_DOCUMENT_DETAILS LIMIT 100
 
///////////////////////////////////////////////////////////

-- MAXI_CAT_UWR 

-- OLD VARIANT KEYS : policyDetails.dispatchDetails,policyDetails.documentDetails,policyDetails.endorsementDetails,policyDetails.insuredDetails.documentDetails,policyDetails.insuredDetails.memberDetails,policyDetails.officeDetails,policyDetails.teleVerificationDetails,policyDetails.workItemDetails,premiumDetails,quoteParamDetails,policyDetails.policyPaymentInformation,policyDetails.policyRelation,policyDetails.previousPolicyDetails,policyDetails.policyProperty.simpleProperty,policyDetails.proposerDetails.documentDetail,policyDetails.proposerDetails.partyRelation,policyDetails.officeDetails.officeAddress.addressProperty,policyDetails.insuredDetails.riskProperty.simpleProperty,policyDetails.proposerDetails.partyAddress.addressProperty,policyDetails.proposerDetails.partyProperty.simpleProperty,policyDetails.proposerDetails.partyProperty.multiSetProperty,quoteParamDetails.riskList.riskProperty.ruleList,quoteParamDetails.riskList.riskCover.riskCoverProperty.ruleList,quoteParamDetails.policyProperty.ruleList,policyDetails.insuredDetails.coverDetails.coverProperty.simpleProperty

-- NEWLY ADDED VARIANT KEYS : policyDetails.insuredDetails.memberDetails.documentDetail,policyDetails.insuredDetails.memberDetails.partyRelation,policyDetails.insuredDetails.memberDetails.partyAddress.addressProperty,policyDetails.insuredDetails.riskProperty.multiSetProperty,policyDetails.proposerDetails.partyProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty,policyDetails.insuredDetails.memberDetails.partyProperty.multiSetProperty,policyDetails.insuredDetails.memberDetails.partyProperty.simpleProperty,quoteParamDetails.riskList.multiSetPropertyInput,quoteParamDetails.policyProperty.multiSetPropertyInput,policyDetails.policyProperty.multiSetProperty

-- INVALID VARIANT KEYS : 
-- 1.(getting empty list = []) -->  policyDetails.insuredDetails.riskProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty.multiSetDetail,policyDetails.policyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.policyProperty.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.memberDetails.relatedParty,policyDetails.proposerDetails.relatedParty,
-- 2.(getting all null) --> policyDetails.insuredDetails.memberDetails.partyProperty.simpleProperty,policyDetails.insuredDetails.memberDetails.partyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.partyDetails,quoteParamDetails.polPropPropList,quoteParamDetails.additionalPartyList,quoteParamDetails.buildingDetails,quoteParamDetails.riskList.partyDetails


SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_METADATA WHERE  key_path like 'quoteParamDetails.riskList.%';

SELECT distinct foreign_key FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_DISPATCH_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_ENDORSEMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS limit 10
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS_ADDRESS_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_POLICY_PAYMENT_INFORMATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_POLICY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PREVIOUS_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_DOCUMENT_DETAIL LIMIT 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_TELE_VERIFICATION_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_POLICY_DETAILS_WORK_ITEM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_PREMIUM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_RULE_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY_RULE_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_CAT_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY_RULE_LIST


////////////////////////////////////////////////////////////////////////////

-- MAXI_SUR_BND_UWR

-- OLD VARIANT KEYS : policyDetails.dispatchDetails,policyDetails.documentDetails,policyDetails.endorsementDetails,policyDetails.insuredDetails.coverDetails,policyDetails.insuredDetails.documentDetails,policyDetails.insuredDetails.memberDetails,policyDetails.insuredDetails.riskProperty,policyDetails.officeDetails.officeAddress,policyDetails.policyProperty,policyDetails.proposerDetails,policyDetails.teleVerificationDetails,policyDetails.workItemDetails,premiumDetails,quoteParamDetails.policyProperty,quoteParamDetails.riskList.riskCover,quoteParamDetails.riskList.riskProperty

-- NEWLY ADDED VARIANT KEYS : policyDetails.policyPaymentInformation,policyDetails.policyRelation,policyDetails.previousPolicyDetails,policyDetails.policyProperty.simpleProperty,policyDetails.proposerDetails.documentDetail,policyDetails.proposerDetails.partyRelation,policyDetails.officeDetails.officeAddress.addressProperty,policyDetails.insuredDetails.riskProperty.simpleProperty,policyDetails.policyProperty.multiSetProperty.multiSetDetail.property,policyDetails.proposerDetails.partyAddress.addressProperty,policyDetails.proposerDetails.partyProperty.simpleProperty,policyDetails.proposerDetails.partyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.riskList.riskProperty.ruleList,quoteParamDetails.riskList.riskCover.riskCoverProperty.ruleList,quoteParamDetails.policyProperty.ruleList,quoteParamDetails.policyProperty.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.insuredDetails.coverDetails.coverProperty.simpleProperty,

-- INVALID VARIANT KEYS : 
-- 1.(getting empty list = []) --> policyDetails.insuredDetails.memberDetails.documentDetail,policyDetails.insuredDetails.memberDetails.partyRelation,policyDetails.insuredDetails.memberDetails.partyAddress.addressProperty,policyDetails.insuredDetails.riskProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.riskList.multiSetPropertyInput,quoteParamDetails.riskList.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.insuredDetails.memberDetails.relatedParty,policyDetails.proposerDetails.relatedParty,
-- 2.(getting all null) --> policyDetails.insuredDetails.memberDetails.partyProperty.simpleProperty,policyDetails.insuredDetails.memberDetails.partyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.partyDetails,quoteParamDetails.polPropPropList,quoteParamDetails.riskList.partyDetails,quoteParamDetails.additionalPartyList,quoteParamDetails.buildingDetails
 

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_METADATA WHERE KEY_TYPE = 'VARIANT';

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA
SELECT distinct foreign_key FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_DISPATCH_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_ENDORSEMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_ENDORSEMENT_DETAILS_CLONE_20260116045823299
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS_ADDRESS_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PAYMENT_INFORMATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_POLICY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PREVIOUS_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_DOCUMENT_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_TELE_VERIFICATION_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_POLICY_DETAILS_WORK_ITEM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_PREMIUM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_RULE_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY_RULE_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY_RULE_LIST

////////////////////////////////////////////////////////////////////////////

-- LAST VALIDATED ON 13-04-2026

-- MAXI_SUR_BND_CLM

-- OLD VARIANT KEYS : claimDetails.claimAttribute.multiSetProperty,claimDetails.claimAttribute.properties,claimDetails.claimEventFollowup,claimDetails.claimParty.ptyattr,claimDetails.claimPayment.paymentproperty,claimDetails.claimReserve,claimDetails.claimRisk.riskAttribute.multiSetProperty.multiSetDetail.property,claimDetails.claimRisk.riskAttribute.properties,claimDetails.claimRiskParty.ptyattr,claimDetails.documentDetails

-- INVALID VARIANT KEYS :
-- 1.(getting empty list = []) --> claimDetails.claimAttribute.multiSetProperty.multiSetDetail,claimDetails.claimCover,claimDetails.claimHistory,claimDetails.claimNotes,claimDetails.claimNotificationDetails,claimDetails.claimSurveyorDeputation,claimDetails.claimTriggerDetails,claimDetails.claimParty.ptyattr.properties,claimDetails.claimRiskParty.ptyattr.properties

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_METADATA WHERE KEY_TYPE = 'VARIANT';

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS WHERE ARRAY_SIZE("CLAIM_COVER") > 0 OR ARRAY_SIZE("CLAIM_HISTORY") > 0 OR ARRAY_SIZE("CLAIM_NOTES") > 0 OR ARRAY_SIZE("CLAIM_SURVEYOR_DEPUTATION") > 0 OR ARRAY_SIZE("CLAIM_NOTIFICATION_DETAILS") > 0 OR ARRAY_SIZE("CLAIM_TRIGGER_DETAILS") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY LIMIT 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_EVENT_FOLLOWUP;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PARTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PARTY_PTYATTR WHERE ARRAY_SIZE("PROPERTIES") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PAYMENT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PAYMENT_PAYMENTPROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RESERVE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_PARTY_PTYATTR WHERE ARRAY_SIZE("PROPERTIES") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_PROPERTIES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_DATA_CLAIM_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_SUR_BND_CLM_VW_METADATA

////////////////////////////////////////////////////////////////////////////

-- LAST VALIDATED ON : 13-04-2026

-- MAXI_PROP_UWR

-- OLD VARIANT KEYS : policyDetails.dispatchDetails,policyDetails.documentDetails,policyDetails.endorsementDetails,policyDetails.insuredDetails.coverDetails,policyDetails.insuredDetails.documentDetails,policyDetails.insuredDetails.memberDetails,policyDetails.teleVerificationDetails,policyDetails.workItemDetails,premiumDetails,policyDetails.policyPaymentInformation,policyDetails.policyRelation,policyDetails.previousPolicyDetails,policyDetails.policyProperty.simpleProperty,policyDetails.proposerDetails.documentDetail,policyDetails.proposerDetails.partyRelation,policyDetails.officeDetails.officeAddress.addressProperty,policyDetails.insuredDetails.riskProperty.simpleProperty,policyDetails.proposerDetails.partyAddress.addressProperty,policyDetails.proposerDetails.partyProperty.simpleProperty,quoteParamDetails.riskList.riskCover.riskCoverProperty.ruleList,quoteParamDetails.riskList.riskProperty.ruleList,quoteParamDetails.policyProperty.ruleList,policyDetails.insuredDetails.riskProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.policyProperty.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.policyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.riskList.multiSetPropertyInput.multiSetDetailInput.property,policyDetails.insuredDetails.coverDetails.coverProperty.simpleProperty

-- NEWLY ADDED VARIANT KEYS : policyDetails.proposerDetails.partyProperty.multiSetProperty.multiSetDetail.property,

-- INVALID VARIANT KEYS : 1. getting empty array --> [] : policyDetails.insuredDetails.memberDetails.documentDetail,policyDetails.insuredDetails.memberDetails.partyRelation,policyDetails.insuredDetails.memberDetails.partyAddress.addressProperty,policyDetails.insuredDetails.coverDetails.coverProperty.multiSetProperty.multiSetDetail.property,policyDetails.insuredDetails.memberDetails.relatedParty,policyDetails.proposerDetails.relatedParty,quoteParamDetails.partyDetails,quoteParamDetails.polPropPropList,quoteParamDetails.additionalPartyList,quoteParamDetails.buildingDetails
-- 2. getting all null values --> policyDetails.insuredDetails.memberDetails.partyProperty.simpleProperty,policyDetails.insuredDetails.memberDetails.partyProperty.multiSetProperty.multiSetDetail.property,quoteParamDetails.riskList.partyDetails


SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_METADATA  WHERE KEY_TYPE = 'VARIANT';

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA 
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_DISPATCH_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_DOCUMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_ENDORSEMENT_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY,LATERAL FLATTEN(input =>MULTI_SET_PROPERTY) ms WHERE ms.value:multiSetDetail IS NOT NULL AND ms.value:multiSetDetail != '[]' AND ARRAY_SIZE(ms.value:multiSetDetail) > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_DOCUMENT_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS WHERE ARRAY_SIZE("DOCUMENT_DETAIL") > 0 OR ARRAY_SIZE("PARTY_RELATION") > 0  OR ARRAY_SIZE("RELATED_PARTY") > 0 OR ARRAY_SIZE("PARTY_ADDRESS") > 0 OR NVL("PARTY_PROPERTY", 'null') != 'null' ;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS_ADDRESS_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PAYMENT_INFORMATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_POLICY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PREVIOUS_POLICY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS where ARRAY_SIZE("RELATED_PARTY") > 0
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_DOCUMENT_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY,LATERAL FLATTEN(input =>MULTI_SET_PROPERTY) ms WHERE ms.value:multiSetDetail IS NOT NULL AND ms.value:multiSetDetail != '[]' AND ARRAY_SIZE(ms.value:multiSetDetail) > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_RELATION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_TELE_VERIFICATION_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_POLICY_DETAILS_WORK_ITEM_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_PREMIUM_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS where nvl("PARTY_DETAILS" , 'null') != 'null' or nvl("BUILDING_DETAILS", 'null') != 'null' or nvl("ADDITIONAL_PARTY_LIST" , 'null') != 'null' or nvl("POL_PROP_PROP_LIST" , 'null') != 'null' ;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_RULE_LIST;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST where nvl("PARTY_DETAILS" , 'null') != 'null';
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY limit 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY_RULE_LIST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_PROP_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY_RULE_LIST

        
////////////////////////////////////////////////////////////////////////////

-- LAST VALIDATED ON : 13-04-2026 claimDetail.relations.party.partyDetails.attributes

-- MAXI_HLTH_CLM claimDetail.claimParty

-- OLD KEYS : authorizationRemarks.multisetAttribute.attributes,PolicyClaimHistory.multisetAttribute.attributes,ClaimPolicyHistory.multisetAttribute.attributes,claimDetail.claimAdjust,claimDetail.claimCopayDetails.attributes,claimDetail.claimPartydetails,claimDetail.claimPayment.claimPaymentDetail.attributes,claimDetail.claimPayment.paymentCycle.paymentCycleDetails,claimDetail.claimReserve.attributes,claimDetail.claimReserveHistory.attributes,claimDetail.claimbenefitlimit,claimDetail.claimdetailAttribute.multisetAttribute.attributes.multisetAttribute.attributes,claimDetail.claiminwdDocuments,claimDetail.claimtransition.attributes,claimDetail.documents.document,claimDetail.followup.attributes,claimDetail.listOfCovers.coverSetAttribute,claimDetail.listOfCovers.entityHeads.entityGridRows.rowAttributes.multisetAttribute,claimDetail.notes.attributes,claimDetail.packageandservice,claimDetail.previousinsurancedetail,claimDetail.previousinsurancedetail,claimDetail.previousinsurancedetails,claimDetail.queryDetails,claimDetail.relations,claimDetail.relations.party.contactDetails,claimDetail.relations.party.partyDetails,claimDetail.relations.relationAttribute,claimDetail.requirements,penalInterest.multisetAttribute.attributes

-- NEWLY ADDED : claimDetail.queryDetails.rows.columns.childRows.rows.columns,claimDetail.claiminwdDocuments.rows.columns,claimDetail.requirements.rows.columns.childRows.rows.columns,claimDetail.listOfCovers.entityHeads.entityGridRows.rowAttributes.multisetAttribute.attributes,claimDetail.relations.party.partyDetails.attributes

-- invalid:

-- 1.(getting empty list = []) --> claimDetail.relations.party.partyDetails.multiSetAttribute


SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_METADATA where KEY_TYPE = 'VARIANT'

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_AUTHORIZATION_REMARKS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_AUTHORIZATION_REMARKS_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_AUTHORIZATION_REMARKS_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMBENEFITLIMIT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMINWD_DOCUMENTS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMINWD_DOCUMENTS_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMINWD_DOCUMENTS_ROWS_COLUMNS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMTRANSITION
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMTRANSITION_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_ADJUST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_COPAY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_COPAY_DETAILS_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PARTYDETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_CLAIM_PAYMENT_DETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_CLAIM_PAYMENT_DETAIL_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_PAYMENT_CYCLE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_PAYMENT_CYCLE_PAYMENT_CYCLE_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE_HISTORY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE_HISTORY_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_DOCUMENTS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_DOCUMENTS_DOCUMENT
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_FOLLOWUP
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_FOLLOWUP_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_COVER_SET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS 
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES_MULTISET_ATTRIBUTE_ATTRIBUTES LIMIT 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_NOTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_NOTES_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PACKAGEANDSERVICE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PREVIOUSINSURANCEDETAIL
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PREVIOUSINSURANCEDETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_PARTY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_PARTY_CONTACT_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_PARTY_PARTY_DETAILS WHERE ARRAY_SIZE("MULTI_SET_ATTRIBUTE") > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_PARTY_PARTY_DETAILS_ATTRIBUTES LIMIT 100
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_RELATION_ATTRIBUTE;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_POLICY_HISTORY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_POLICY_HISTORY_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_POLICY_HISTORY_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_PENAL_INTEREST
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_PENAL_INTEREST_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_PENAL_INTEREST_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_POLICY_CLAIM_HISTORY
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_POLICY_CLAIM_HISTORY_MULTISET_ATTRIBUTE
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_POLICY_CLAIM_HISTORY_MULTISET_ATTRIBUTE_ATTRIBUTES
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS_CHILD_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS_CHILD_ROWS_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS_CHILD_ROWS_ROWS_COLUMNS 
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS_CHILD_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS_CHILD_ROWS_ROWS
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS_CHILD_ROWS_ROWS_COLUMNS LIMIT 100

////////////////////////////////////////////////////////////////////////////

-- MAXI_HLTH_UWR 

--valid: basicDetailAttribute,communicationDetailsAdditionTab.mail,communicationDetailsAdditionTab.sms,endorsementDetails,endorsementHistoryReport,memberDetailsTab.gradedSiDetails,memberDetailsTab.memberData,memberDetailsTabs.memberStatusHistory,memberDetailsTabs.policyAndClaimHistory,memberRiderDetails,members.FollowUpReport.attributes,additionalTest,members.benefits.attributes,members.medicalrating,members.medicalrating.CTMT.attributes,members.medicalrating.decisions,members.medicalrating.digitallabreports,exclusions,members.party.contactDetails,members.party.partyDetails,members.ppcPackage,members.questionnaire,requirementDetails.rows.childRows,requirementDetails.rows.columns,viewCollections,viewCollectionsAdditionalDetails

-- newly added : requirementDetails.rows.childRows.rows.columns,basicDetailAttribute.multisetAttribute.attributes,members.memberDetails.multisetAttribute.attributes,members.requirementDetails.rows.childRows.rows.columns,members.requirementDetails.rows.columns,paymentInfo,policyPaymentCycleDetails.paymentCycleDetails.paymentCycle,premiumCalculationDetails,premiumDetails.premiumDetails,proposerAddress.contactDetails,receiptDetailsList,relations.party.contactDetails,relations.party.partyDetails

--invalid: 
-- reason = "[]" : communicationdetails,documentdetails,followUpdetails,members.medicalDetails,members.medicalDigitization,notesdetails,policyPaymentCycleDetails.paymentDetails,renewaldetails,relations.relationAttribute


-- check:


SELECT renewaldetails FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA WHERE ARRAY_SIZE(renewaldetails) > 0 limit 100

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA limit 100

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_METADATA WHERE KEY_TYPE = 'VARIANT'


UPDATE BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_METADATA SET KEY_TYPE = 'VARCHAR,VARIANT' WHERE KEY_PATH = 'basicDetailAttribute.multisetAttribute' LIMIT 1;

SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA WHERE ARRAY_SIZE(TRY_PARSE_JSON("COMMUNICATIONDETAILS")) > 0 OR ARRAY_SIZE(TRY_PARSE_JSON("DOCUMENTDETAILS")) > 0 OR ARRAY_SIZE(TRY_PARSE_JSON("FOLLOW_UPDETAILS")) > 0;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_COMMUNICATION_DETAILS_ADDITION_TAB LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_COMMUNICATION_DETAILS_ADDITION_TAB_MAIL LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_COMMUNICATION_DETAILS_ADDITION_TAB_SMS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_ENDORSEMENT_DETAILS LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_ENDORSEMENT_HISTORY_REPORT LIMIT 1;
SELECT MEMBER_DETAILS FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS  WHERE ARRAY_SIZE(TRY_PARSE_JSON("MEDICAL_DETAILS")) > 0 OR ARRAY_SIZE(TRY_PARSE_JSON("MEDICAL_DIGITIZATION")) > 0 ;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS_MULTISET_ATTRIBUTE LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS_MULTISET_ATTRIBUTE_ATTRIBUTES LIMIT 10;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_BENEFITS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_BENEFITS_ATTRIBUTES LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_FOLLOW_UP_REPORT LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_FOLLOW_UP_REPORT_ATTRIBUTES LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_CTMT LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_CTMT_ATTRIBUTES LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_DECISIONS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_DIGITALLABREPORTS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PARTY LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PARTY_CONTACT_DETAILS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PARTY_PARTY_DETAILS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PPC_PACKAGE LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PPC_PACKAG_E LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_QUESTIONNAIRE LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TAB LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TABS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TABS_MEMBER_STATUS_HISTORY LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TABS_POLICY_AND_CLAIM_HISTORY LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TAB_GRADED_SI_DETAILS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_DETAILS_TAB_MEMBER_DATA LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBER_RIDER_DETAILS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS_ROWS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS_ROWS_COLUMNS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_COLUMNS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_VIEW_COLLECTIONS LIMIT 1;
SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_VIEW_COLLECTIONS_ADDITIONAL_DETAILS LIMIT 1;




///////////////////////////////////////////////////////////////////////////////////////////

-- old 

-- CREATE OR REPLACE  TABLE BAGIC_PREPROD_CURATED_DB.UTILS.TEST_1 AS
--                 (SELECT *
--                 FROM BAGIC_PROD_STAGING_DB.MAXI_RAW.MAXI_HLTH_UWR
--                 WHERE DATA:proposalNumber IS NOT NULL
--                 limit 1000);


-- SELECT * FROM BAGIC_PROD_STAGING_DB.MAXI_RAW.MAXI_HLTH_UWR where date(inc_job_created_at) = '2026-04-06' AND DATA:viewCollections != 'null'
        
-- CALL EMPOWER_DB.MAXI_RAW.MAXI_RAW_METADATA_TABLE_PROC(
--                 'BAGIC_PROD_STAGING_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW', 'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'DATA', 'FRO', '0'
--         );
        
-- SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_METADATA WHERE KEY_path LIKE '%[%' KEY_TYPE != 'VARIANT';

-- -- VARINAT KEYS : 
-- CommunicationDetailsAdditiontab,basicdetailAttribute.multisetAttribute.attributes,communicationDetails,documentDetails,endorsementDetails,endorsementHistoryReport,followUpDetails,memberDetailsTab.gradesSIDetails,memberDetailsTab.memberData,memberDetailsTabs.PolicyandClaimHistory,memberDetailsTabs.memberStatusHistory,memberRiderDetails,members.FollowUpReport.attributes,members.benefits.attributes,members.medicalDetails,members.medicalDigitization,members.medicalrating,members.memberDetails.multisetAttribute.attributes,members.party.contactDetails,members.party.partyDetails,members.questionnaire,members.requirementDetails.rows.childRows.rows.columns,members.requirementDetails.rows.columns,notesDetails,policyPaymentCycleDetails.paymentCycleDetails.paymentCycle,policyPaymentCycleDetails.paymentDetails,premiumCalculationDetails,premiumDetails,premiumDetails.premiumDetails.proposerAddress,proposerAddress.contactDetails,receiptDetailsList,relations.party,relations.relationAttribute,renewalDetails,requirementDetails.rows.childRows.rows.columns,requirementDetails.rows.columns,viewCollectionsAdditionalDeatails

-- -- TO BE : members["PPC PACKAGE"]

-- CALL BAGIC_PREPROD_CURATED_DB.UTILS.MAXI_RAW_FLATTEN_VARIANT_TABLE_PROC_TEST2(
--                 'BAGIC_PROD_STAGING_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW',
--                 'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW',
--                 'DATA', 'members."PPC PACKAGE"', 'INC_JOB_CREATED_AT,INC_JOB_ID,FILE_NAME,FILE_TIMESTAMP',
--                 'proposalNumber', 'MAXI_HLTH_UWR_VW',
--                 1, 'FRO', FALSE, '', 'null'
--             )

-- SELECT  * FROM BAGIC_PROD_mirror_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_metadata WHERE KEY_NAME LIKE '%PPC';

-- SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA;

-- SELECT * FROM BAGIC_PROD_mirror_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_metadata LIMIT WHERE KEY_path LIKE '%"' and key_type !='VARIANT'


-- --- NEED TO TEST

-- SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_VIEW_COLLECTIONs;

-- SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS_PPC_PACKAGE;

-- CALL BAGIC_PREPROD_CURATED_DB.UTILS.MAXI_RAW_FLATTEN_VARIANT_TABLE_PROC_test('BAGIC_PROD_MIRROR_DB','MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA', 'BAGIC_PROD_MIRROR_DB','MAXI_RAW','members."PPC PACKAGE"','','inc_job_created_at, inc_job_id, file_name, file_timestamp, foreign_key, root_hash, t.key_hash as parent_key_hash, t.record_hash as parent_record_hash', NULL, 'MAXI_HLTH_UWR_VW', TRUE, 'FRO', '1', '', 'null')

-- SELECT  * FROM BAGIC_PROD_mirror_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_metadata;
-- SELECT * FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.MAXI_HLTH_UWR_VW_DATA_MEMBERS;

-- CALL BAGIC_PREPROD_CURATED_DB.UTILS.MAXI_RAW_FLATTEN_VARIANT_TABLE_PROC_test('BAGIC_PROD_MIRROR_DB','MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS', 'BAGIC_PROD_MIRROR_DB','MAXI_RAW','ppc_packag_e','','inc_job_created_at, inc_job_id, file_name, file_timestamp, foreign_key, root_hash, t.key_hash as parent_key_hash, t.record_hash as parent_record_hash', NULL, 'MAXI_HLTH_UWR_VW', TRUE, 'FRO', '1', '', 'null')

--   ppc_packag_e


            
