{{ config(materialized='view') }}

-- Staging model for source table BJAZ_T_CKYC_PERSONAL_DTLS (Partner + KYC scope).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, DATE/TIMESTAMP ->
-- TIMESTAMP_NTZ. Key columns (hub-key components) -> canonical trimmed VARCHAR
-- regardless of native type, for stable hashing -- the baseline's own convention.

with source as (

    select
    "CKYC_PERSONAL_DTLS_ID"::number as ckyc_personal_dtls_id,
    nullif(trim("CONSTI_TYPE"::varchar), '') as consti_type,
    nullif(trim("ACC_TYPE"::varchar), '') as acc_type,
    nullif(trim("CKYC_NO"::varchar), '') as ckyc_no,
    nullif(trim("PREFIX"::varchar), '') as prefix,
    nullif(trim("FNAME"::varchar), '') as fname,
    nullif(trim("MNAME"::varchar), '') as mname,
    nullif(trim("LNAME"::varchar), '') as lname,
    nullif(trim("FULLNAME"::varchar), '') as fullname,
    nullif(trim("MAIDEN_PREFIX"::varchar), '') as maiden_prefix,
    nullif(trim("MAIDEN_FNAME"::varchar), '') as maiden_fname,
    nullif(trim("MAIDEN_MNAME"::varchar), '') as maiden_mname,
    nullif(trim("MAIDEN_LNAME"::varchar), '') as maiden_lname,
    nullif(trim("MAIDEN_FULLNAME"::varchar), '') as maiden_fullname,
    nullif(trim("FATHERSPOUSE_FLAG"::varchar), '') as fatherspouse_flag,
    nullif(trim("FATHER_PREFIX"::varchar), '') as father_prefix,
    nullif(trim("FATHER_FNAME"::varchar), '') as father_fname,
    nullif(trim("FATHER_MNAME"::varchar), '') as father_mname,
    nullif(trim("FATHER_LNAME"::varchar), '') as father_lname,
    nullif(trim("FATHER_FULLNAME"::varchar), '') as father_fullname,
    nullif(trim("MOTHER_PREFIX"::varchar), '') as mother_prefix,
    nullif(trim("MOTHER_FNAME"::varchar), '') as mother_fname,
    nullif(trim("MOTHER_MNAME"::varchar), '') as mother_mname,
    nullif(trim("MOTHER_LNAME"::varchar), '') as mother_lname,
    nullif(trim("MOTHER_FULLNAME"::varchar), '') as mother_fullname,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("MARITAL_STATUS"::varchar), '') as marital_status,
    nullif(trim("NATIONALITY"::varchar), '') as nationality,
    nullif(trim("OCCUPATION"::varchar), '') as occupation,
    nullif(trim("DOB"::varchar), '') as dob,
    nullif(trim("RESI_STATUS"::varchar), '') as resi_status,
    nullif(trim("JURI_FLAG"::varchar), '') as juri_flag,
    nullif(trim("JURI_RESI"::varchar), '') as juri_resi,
    nullif(trim("TAX_NUM"::varchar), '') as tax_num,
    nullif(trim("BIRTH_COUNTRY"::varchar), '') as birth_country,
    nullif(trim("BIRTH_PLACE"::varchar), '') as birth_place,
    nullif(trim("PERM_TYPE"::varchar), '') as perm_type,
    nullif(trim("PERM_LINE1"::varchar), '') as perm_line1,
    nullif(trim("PERM_LINE2"::varchar), '') as perm_line2,
    nullif(trim("PERM_LINE3"::varchar), '') as perm_line3,
    nullif(trim("PERM_CITY"::varchar), '') as perm_city,
    nullif(trim("PERM_DIST"::varchar), '') as perm_dist,
    nullif(trim("PERM_STATE"::varchar), '') as perm_state,
    nullif(trim("PERM_COUNTRY"::varchar), '') as perm_country,
    nullif(trim("PERM_PIN"::varchar), '') as perm_pin,
    nullif(trim("PERM_POA"::varchar), '') as perm_poa,
    nullif(trim("PERM_POAOTHERS"::varchar), '') as perm_poaothers,
    nullif(trim("PERM_CORRES_SAMEFLAG"::varchar), '') as perm_corres_sameflag,
    nullif(trim("CORRES_LINE1"::varchar), '') as corres_line1,
    nullif(trim("CORRES_LINE2"::varchar), '') as corres_line2,
    nullif(trim("CORRES_LINE3"::varchar), '') as corres_line3,
    nullif(trim("CORRES_CITY"::varchar), '') as corres_city,
    nullif(trim("CORRES_DIST"::varchar), '') as corres_dist,
    nullif(trim("CORRES_STATE"::varchar), '') as corres_state,
    nullif(trim("CORRES_COUNTRY"::varchar), '') as corres_country,
    nullif(trim("CORRES_PIN"::varchar), '') as corres_pin,
    nullif(trim("CORRES_POA"::varchar), '') as corres_poa,
    nullif(trim("JURI_SAME_FLAG"::varchar), '') as juri_same_flag,
    nullif(trim("JURI_LINE1"::varchar), '') as juri_line1,
    nullif(trim("JURI_LINE2"::varchar), '') as juri_line2,
    nullif(trim("JURI_LINE3"::varchar), '') as juri_line3,
    nullif(trim("JURI_CITY"::varchar), '') as juri_city,
    nullif(trim("JURI_DIST"::varchar), '') as juri_dist,
    nullif(trim("JURI_STATE"::varchar), '') as juri_state,
    nullif(trim("JURI_COUNTRY"::varchar), '') as juri_country,
    nullif(trim("RESI_STD_CODE"::varchar), '') as resi_std_code,
    nullif(trim("RESI_TEL_NUM"::varchar), '') as resi_tel_num,
    nullif(trim("OFF_STD_CODE"::varchar), '') as off_std_code,
    nullif(trim("OFF_TEL_NUM"::varchar), '') as off_tel_num,
    nullif(trim("MOB_CODE"::varchar), '') as mob_code,
    nullif(trim("MOB_NUM"::varchar), '') as mob_num,
    nullif(trim("FAX_CODE"::varchar), '') as fax_code,
    nullif(trim("FAX_NO"::varchar), '') as fax_no,
    nullif(trim("EMAIL"::varchar), '') as email,
    nullif(trim("REMARKS"::varchar), '') as remarks,
    nullif(trim("DEC_DATE"::varchar), '') as dec_date,
    nullif(trim("DEC_PLACE"::varchar), '') as dec_place,
    nullif(trim("DOC_SUB"::varchar), '') as doc_sub,
    nullif(trim("NUM_IDENTITY"::varchar), '') as num_identity,
    nullif(trim("NUM_RELATED"::varchar), '') as num_related,
    nullif(trim("NUM_LOCALADDRESS"::varchar), '') as num_localaddress,
    nullif(trim("NUM_IMAGES"::varchar), '') as num_images,
    nullif(trim("NAME_UPDATE_FLAG"::varchar), '') as name_update_flag,
    nullif(trim("PERSONAL_UPDATE_FLAG"::varchar), '') as personal_update_flag,
    nullif(trim("ADDRESS_UPDATE_FLAG"::varchar), '') as address_update_flag,
    nullif(trim("CONTACT_UPDATE_FLAG"::varchar), '') as contact_update_flag,
    nullif(trim("REMARKS_UPDATE_FLAG"::varchar), '') as remarks_update_flag,
    nullif(trim("KYC_UPDATE_FLAG"::varchar), '') as kyc_update_flag,
    nullif(trim("IDENTITY_UPDATE_FLAG"::varchar), '') as identity_update_flag,
    nullif(trim("RELPERSON_UPDATE_FLAG"::varchar), '') as relperson_update_flag,
    nullif(trim("IMAGE_UPDATE_FLAG"::varchar), '') as image_update_flag,
    nullif(trim("CONSTI_TPE_OTHERS"::varchar), '') as consti_tpe_others,
    nullif(trim("PLACE_INC"::varchar), '') as place_inc,
    nullif(trim("COUN_INC"::varchar), '') as coun_inc,
    nullif(trim("TIN_GST"::varchar), '') as tin_gst,
    nullif(trim("TIN_COUN"::varchar), '') as tin_coun,
    nullif(trim("PAN"::varchar), '') as pan,
    nullif(trim("MOB_CODE1"::varchar), '') as mob_code1,
    nullif(trim("MOB_NUM1"::varchar), '') as mob_num1,
    nullif(trim("MOB_CODE2"::varchar), '') as mob_code2,
    nullif(trim("MOB_NUM2"::varchar), '') as mob_num2,
    nullif(trim("IPV_FLAG"::varchar), '') as ipv_flag,
    nullif(trim("EMAIL2"::varchar), '') as email2,
    nullif(trim("DIS_FLAG"::varchar), '') as dis_flag,
    nullif(trim("DIS_TYPE"::varchar), '') as dis_type,
    nullif(trim("DIS_PERCENT"::varchar), '') as dis_percent,
    nullif(trim("DIS_UDID_NUMBER"::varchar), '') as dis_udid_number,
    "INC_JOB_UPDATED_AT"::timestamp_ntz as inc_job_updated_at
    from {{ source('partner_test_raw', 'BJAZ_T_CKYC_PERSONAL_DTLS') }}

)

select * from source
