{{ config(materialized='view') }}

-- Source 1: BJAZ_CLM_SUPP_EXTN (has 40 payload columns, missing 6 from hospital_master)
SELECT
    PARTY_HKEY, HASHDIFF,
    BAGIC_LOCATION, CLAIM_NEAR_ME_FLAG, CLASS, COMP_TYPE,
    NULL AS CONTACT_PERSON_DESIGNATION,
    CONTACT_PERSON_NAME, CON_EXPERTISE, COVERED_AREA, DEALER_CODE,
    DEDUCTIBLE_EXEMPT,
    NULL AS DIAGNO_YN,
    NULL AS EMPANEL_DATE,
    EW_WHITE_GOODS_FLG, EXP_LOB_ENGINEERING_FLG, EXP_LOB_FIRE_FLG,
    EXP_LOB_LOSS_PROFIT_FLG, EXP_LOB_MARINE_HULL_FLG, EXP_LOB_MARIN_CARGO_FLG,
    EXP_LOB_MISCELL_FLG, EXP_LOB_MOTOR_FLG, EXP_LOB_WORKMAN_COMP_FLG,
    GRADE,
    NULL AS HOSP_SPEC_TYPE,
    INVOICE_PATTERN, IRN_FLAG, JW_FLAG, JW_ID, LVS_FLAG, MOU_STATUS,
    NULL AS NETWORK_TYPE,
    NO_TOWING_VEHICLE, ON_DUTY_FLAG, OPERATION_PLACE, ORIGIN_COMP, ORIGIN_CONT,
    OTHER_BAGIC_BUSINESS, OWNRSHIP_DEPT, PRIORITY,
    NULL AS PRIORITY_FLG,
    SPEC_REPAIRER, SUPP_OWNERSHIP, SUPP_SCOPE, TOWING_VEHICLE,
    WORKSHOP_CATEGORY, WORKSHOP_CLASS, WORKSHOP_NAME,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_rolesat_bjaz_clm_supp_extn__lnk_role_provider') }}

UNION ALL

-- Source 2: BJAZ_HM_HOSPITAL_MASTER (has 7 payload columns, missing ~39 from clm_supp)
SELECT
    PARTY_HKEY, HASHDIFF,
    NULL AS BAGIC_LOCATION, NULL AS CLAIM_NEAR_ME_FLAG, NULL AS CLASS, NULL AS COMP_TYPE,
    CONTACT_PERSON_DESIGNATION,
    CONTACT_PERSON_NAME, NULL AS CON_EXPERTISE, NULL AS COVERED_AREA, NULL AS DEALER_CODE,
    NULL AS DEDUCTIBLE_EXEMPT,
    DIAGNO_YN,
    EMPANEL_DATE,
    NULL AS EW_WHITE_GOODS_FLG, NULL AS EXP_LOB_ENGINEERING_FLG, NULL AS EXP_LOB_FIRE_FLG,
    NULL AS EXP_LOB_LOSS_PROFIT_FLG, NULL AS EXP_LOB_MARINE_HULL_FLG, NULL AS EXP_LOB_MARIN_CARGO_FLG,
    NULL AS EXP_LOB_MISCELL_FLG, NULL AS EXP_LOB_MOTOR_FLG, NULL AS EXP_LOB_WORKMAN_COMP_FLG,
    NULL AS GRADE,
    HOSP_SPEC_TYPE,
    NULL AS INVOICE_PATTERN, NULL AS IRN_FLAG, NULL AS JW_FLAG, NULL AS JW_ID, NULL AS LVS_FLAG, NULL AS MOU_STATUS,
    NETWORK_TYPE,
    NULL AS NO_TOWING_VEHICLE, NULL AS ON_DUTY_FLAG, NULL AS OPERATION_PLACE, NULL AS ORIGIN_COMP, NULL AS ORIGIN_CONT,
    NULL AS OTHER_BAGIC_BUSINESS, NULL AS OWNRSHIP_DEPT, NULL AS PRIORITY,
    PRIORITY_FLG,
    NULL AS SPEC_REPAIRER, NULL AS SUPP_OWNERSHIP, NULL AS SUPP_SCOPE, NULL AS TOWING_VEHICLE,
    NULL AS WORKSHOP_CATEGORY, NULL AS WORKSHOP_CLASS, NULL AS WORKSHOP_NAME,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_rolesat_bjaz_hm_hospital_master__lnk_role_provider') }}
