{{ config(materialized='view') }}

SELECT LOCATION_HKEY, HASHDIFF, ADDRESS_LINE4, ADDRESS_LINE5, NULL AS CARE_OF_NAME, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_cp_add_hist__location') }}
UNION ALL
SELECT LOCATION_HKEY, HASHDIFF, NULL AS ADDRESS_LINE4, NULL AS ADDRESS_LINE5, CARE_OF_NAME, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_bjaz_cp_part_hist__location') }}
UNION ALL
SELECT LOCATION_HKEY, HASHDIFF, ADDRESS_LINE4, ADDRESS_LINE5, NULL AS CARE_OF_NAME, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_cp_addresses__location') }}
UNION ALL
SELECT LOCATION_HKEY, HASHDIFF, NULL AS ADDRESS_LINE4, NULL AS ADDRESS_LINE5, CARE_OF_NAME, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_aug_cp_partners__location') }}
