{{ config(materialized='table') }}

-- Source 1: AZBJ_PARTNER_EXTN (4 cols: ALTERNATEEMAILADDRESS, ALTERNATEMOBILENUMBER, LANDLINENUMBER, PREFERREDCONTACTTIME)
SELECT PARTY_HKEY, HASHDIFF, ALTERNATEEMAILADDRESS, ALTERNATEMOBILENUMBER, NULL AS EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_azbj_partner_extn__common_contact') }}
UNION ALL
-- Source 2: BJAZ_AZBJ_PART_EXT_HIST (3 cols: ALTERNATEEMAILADDRESS, LANDLINENUMBER, PREFERREDCONTACTTIME)
SELECT PARTY_HKEY, HASHDIFF, ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, NULL AS EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_azbj_part_ext_hist__common_contact') }}
UNION ALL
-- Source 3: BJAZ_CLM_SUPP_EXTN (4 cols: EMAILADDRESS, LANDLINENUMBER, MOBILENUMBER, STDCODE)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_clm_supp_extn__common_contact') }}
UNION ALL
-- Source 4: BJAZ_CP_PART_HIST (3 cols: EMAILADDRESS, FAXNUMBER, LANDLINENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_cp_part_hist__common_contact') }}
UNION ALL
-- Source 5: BJAZ_CTNGY_GC_MEM_DATA (1 col: LANDLINENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, NULL AS EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_gc_mem_data__common_contact') }}
UNION ALL
-- Source 6: BJAZ_CTNGY_PA_MEM_DTLS (4 cols: EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, MOBILENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_pa_mem_dtls__common_contact') }}
UNION ALL
-- Source 7: BJAZ_HM_HOSPITAL_MASTER (4 cols: EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, STDCODE)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hm_hospital_master__common_contact') }}
UNION ALL
-- Source 8: BJAZ_HM_MEMBER_DTLS (2 cols: EMAILADDRESS, LANDLINENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hm_member_dtls__common_contact') }}
UNION ALL
-- Source 9: BJAZ_SH_MEM_DTLS_EXTN (1 col: EMAILADDRESS)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, NULL AS FAXNUMBER, NULL AS LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_sh_mem_dtls_extn__common_contact') }}
UNION ALL
-- Source 10: CLM_SUPPLIERS (1 col: LANDLINENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, NULL AS EMAILADDRESS, NULL AS FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_clm_suppliers__common_contact') }}
UNION ALL
-- Source 11: CP_PARTNERS (3 cols: EMAILADDRESS, FAXNUMBER, LANDLINENUMBER)
SELECT PARTY_HKEY, HASHDIFF, NULL AS ALTERNATEEMAILADDRESS, NULL AS ALTERNATEMOBILENUMBER, EMAILADDRESS, FAXNUMBER, LANDLINENUMBER, NULL AS MOBILENUMBER, NULL AS PREFERREDCONTACTTIME, NULL AS STDCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_cp_partners__common_contact') }}
