-- Staging model for source table BJAZ_HM_MEMBER_DTLS (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    nullif(trim("ACTION_CODE"::varchar), '') as action_code,
    "VERSION_NO"::number as version_no,
    "OBJECT_ID"::number as object_id,
    nullif(trim("TOP_INDICATOR"::varchar), '') as top_indicator,
    "PREVIOUS_VERSION"::number as previous_version,
    "REVERSING_VERSION"::number as reversing_version,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    nullif(trim("POLICY_REF"::varchar), '') as policy_ref,
    "MEMBER_ID"::number as member_id,
    nullif(trim("HAT_EMPCODE"::varchar), '') as hat_empcode,
    nullif(trim("CO_EMPNUMBER"::varchar), '') as co_empnumber,
    "SUMINSURED"::number as suminsured,
    "BONUS_SI"::number as bonus_si,
    "PREMIUM"::number as premium,
    nullif(trim("ADDRESS"::varchar), '') as address,
    nullif(trim("PIN"::varchar), '') as pin,
    nullif(trim("PHONE_NO"::varchar), '') as phone_no,
    nullif(trim("MEMBER_STATUS"::varchar), '') as member_status,
    nullif(trim("ID_CARD_NO"::varchar), '') as id_card_no,
    nullif(trim("MEMBER_NAME"::varchar), '') as member_name,
    "DOB"::timestamp_ntz as dob,
    "AGE"::number as age,
    nullif(trim("RELATION"::varchar), '') as relation,
    nullif(trim("EMAIL_ID"::varchar), '') as email_id,
    nullif(trim("OCCUPATION"::varchar), '') as occupation,
    "TERM_START_DATE"::timestamp_ntz as term_start_date,
    nullif(trim("DESIGNATION"::varchar), '') as designation,
    "TERM_END_DATE"::timestamp_ntz as term_end_date,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    nullif(trim("BANK_AC_NO"::varchar), '') as bank_ac_no,
    nullif(trim("MICR_CODE"::varchar), '') as micr_code,
    "PROCESS_DATE"::timestamp_ntz as process_date,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("ENDORSEMENT_NO"::varchar), '') as endorsement_no,
    "ENDORSEMENT_DATE"::timestamp_ntz as endorsement_date,
    nullif(trim("BANK_NAME"::varchar), '') as bank_name,
    "UPDATED_ON"::timestamp_ntz as updated_on,
    "DELETE_FLAG"::number as delete_flag,
    nullif(trim("GRADE"::varchar), '') as grade,
    nullif(trim("USER_NAME"::varchar), '') as user_name,
    nullif(trim("RISK_CLASS"::varchar), '') as risk_class,
    nullif(trim("ADD_ENDORSEMENT_NO"::varchar), '') as add_endorsement_no,
    nullif(trim("DEL_ENDORSEMENT_NO"::varchar), '') as del_endorsement_no,
    nullif(trim("REFUND_PREMIUM"::varchar), '') as refund_premium,
    "DATA_RECEIVED_DATE"::timestamp_ntz as data_received_date,
    nullif(trim("OLD_TABLE_NAME"::varchar), '') as old_table_name,
    "LOAD_RATE"::number as load_rate,
    "LOAD_AMT"::number as load_amt,
    "CUMM_BONUS_PER"::number as cumm_bonus_per,
    "CUMM_BONUS"::number as cumm_bonus,
    "GROSS_INCOME"::number as gross_income,
    "HC_NO_OF_DAYS"::number as hc_no_of_days,
    nullif(trim("ASSIGNEE_NAME"::varchar), '') as assignee_name,
    nullif(trim("UPDATED_BY"::varchar), '') as updated_by,
    "MEMBER_FLAG"::number as member_flag,
    nullif(trim("PLAN_NAME"::varchar), '') as plan_name,
    nullif(trim("CITY"::varchar), '') as city,
    nullif(trim("STATE"::varchar), '') as state,
    nullif(trim(to_varchar("PRODUCT_CODE")), '') as product_code,
    "CLAIM_COUNT"::number as claim_count,
    "CTNY_INFOVIEW_FLAG"::number as ctny_infoview_flag,
    "CTNY_MASTER_CONTRACT_ID"::number as ctny_master_contract_id,
    nullif(trim("OLD_MEMBER_NO"::varchar), '') as old_member_no,
    "DATE_SENT_TO_VENDOR"::timestamp_ntz as date_sent_to_vendor,
    nullif(trim("EMPLOYEE_LOCATION"::varchar), '') as employee_location,
    nullif(trim("MONTHLY_SALARY"::varchar), '') as monthly_salary,
    nullif(trim("VIP_FLG"::varchar), '') as vip_flg,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date
    from {{ source('partner_raw', 'BJAZ_HM_MEMBER_DTLS') }}

)

select * from source
