-- Staging model for source table BJAZ_HCF_MEMBER_DTLS (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    nullif(trim("ACTION_CODE"::varchar), '') as action_code,
    "VERSION_NO"::number as version_no,
    "OBJECT_ID"::number as object_id,
    nullif(trim("TOP_INDICATOR"::varchar), '') as top_indicator,
    "PREVIOUS_VERSION"::number as previous_version,
    "REVERSING_VERSION"::number as reversing_version,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    "MEMBER_NO"::number as member_no,
    nullif(trim("RELATION"::varchar), '') as relation,
    nullif(trim("INSURED_NAME"::varchar), '') as insured_name,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    "DATE_OF_BIRTH"::timestamp_ntz as date_of_birth,
    "AGE"::number as age,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("ASSIGNEE"::varchar), '') as assignee,
    nullif(trim("ASSIGNEE_RELATION"::varchar), '') as assignee_relation,
    nullif(trim("MEMBER_OCCUPATION"::varchar), '') as member_occupation,
    "MONTHLY_INCOME"::number as monthly_income,
    nullif(trim("PREEXIST_DICEASE"::varchar), '') as preexist_dicease,
    nullif(trim("MED_REPORT_RECEIVED"::varchar), '') as med_report_received,
    nullif(trim("REPORTS_NORMAL"::varchar), '') as reports_normal,
    nullif(trim("SPECIAL_CONDITIONS"::varchar), '') as special_conditions,
    nullif(trim("SI_PLAN"::varchar), '') as si_plan,
    "SUM_INSURED"::number as sum_insured,
    nullif(trim("HOSP_CASH"::varchar), '') as hosp_cash,
    nullif(trim("CRITICAL_ILLNESS"::varchar), '') as critical_illness,
    nullif(trim("PERSONAL_ACC"::varchar), '') as personal_acc,
    "LOAD_PER"::number as load_per,
    nullif(trim("LOADING_REASON"::varchar), '') as loading_reason,
    "PREMIUM"::number as premium,
    nullif(trim("SMOKER_FLAG"::varchar), '') as smoker_flag,
    nullif(trim("ASTHMA_FLAG"::varchar), '') as asthma_flag,
    nullif(trim("HOLESTEROL_FLAG"::varchar), '') as holesterol_flag,
    nullif(trim("HEART_FLAG"::varchar), '') as heart_flag,
    nullif(trim("HIPERTENSION_FLAG"::varchar), '') as hipertension_flag,
    nullif(trim("DIABETES_FLAG"::varchar), '') as diabetes_flag,
    nullif(trim("HEIGHT_FLAG"::varchar), '') as height_flag,
    nullif(trim("WEIGHT_FLAG"::varchar), '') as weight_flag,
    nullif(trim("AGE_PROOF_FLAG"::varchar), '') as age_proof_flag,
    nullif(trim("MED_EXAM_FLAG"::varchar), '') as med_exam_flag,
    nullif(trim("COMPANY_NAME"::varchar), '') as company_name,
    nullif(trim(to_varchar("POLICY_NUMBER")), '') as policy_number,
    "PREVIOUS_SI"::number as previous_si,
    "FROM_DATE"::timestamp_ntz as from_date,
    "TO_DATE"::timestamp_ntz as to_date,
    "CUMULATIVE_BNOUZ_PER"::number as cumulative_bnouz_per,
    "CUMULATIVE_AMT"::number as cumulative_amt,
    "PREV_POLICY_SINCE"::timestamp_ntz as prev_policy_since,
    nullif(trim("CONCURRENT_POLICY_DETAILS"::varchar), '') as concurrent_policy_details,
    nullif(trim("DECEASE_TREATMENT_DTLS"::varchar), '') as decease_treatment_dtls,
    nullif(trim("CLAIM_DTLS"::varchar), '') as claim_dtls,
    nullif(trim("OTHER_REMARKS"::varchar), '') as other_remarks,
    nullif(trim("ANCILIARY"::varchar), '') as anciliary,
    nullif(trim("OBESITY_FLAG"::varchar), '') as obesity_flag,
    nullif(trim("BMI_FLAG"::varchar), '') as bmi_flag,
    nullif(trim("OTHER_RISK_FLAG"::varchar), '') as other_risk_flag,
    nullif(trim("HYPERLIPIDE_FLAG"::varchar), '') as hyperlipide_flag,
    "OBESITY_LOAD"::number as obesity_load,
    "BMI_LOAD"::number as bmi_load,
    "HYPERTENS_LOAD"::number as hypertens_load,
    "DIABETES_LOAD"::number as diabetes_load,
    "HYPERLIPIDEMIA_LOAD"::number as hyperlipidemia_load,
    "OTHER_RISK_LOAD"::number as other_risk_load,
    nullif(trim("DIABETES_TYPE"::varchar), '') as diabetes_type,
    "LOADSUM_AMT"::number as loadsum_amt,
    "ADON_PREMIUM"::number as adon_premium,
    "FLOAT_PREMIUM"::number as float_premium,
    "FLOAT_ADDON"::number as float_addon,
    nullif(trim("PARAM1"::varchar), '') as param1,
    nullif(trim("PARAM2"::varchar), '') as param2,
    nullif(trim("PARAM3"::varchar), '') as param3,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date
    from {{ source('partner_raw', 'BJAZ_HCF_MEMBER_DTLS') }}

)

select * from source
