-- Staging model for source table BJAZ_CTNGY_PA_MEM_DTLS (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    nullif(trim("ACTION_CODE"::varchar), '') as action_code,
    "VERSION_NO"::number as version_no,
    "OBJECT_ID"::number as object_id,
    nullif(trim("TOP_INDICATOR"::varchar), '') as top_indicator,
    "PREVIOUS_VERSION"::number as previous_version,
    "REVERSING_VERSION"::number as reversing_version,
    nullif(trim("CONTRACT_ID"::varchar), '') as contract_id,
    nullif(trim("ASSIGNE_ADDRESS"::varchar), '') as assigne_address,
    nullif(trim("ASSIGNEE_NAME"::varchar), '') as assignee_name,
    "BASIC_SI"::number as basic_si,
    "WIDER_SI"::number as wider_si,
    "COMPREHENSIVE_SI"::number as comprehensive_si,
    nullif(trim("ASSIGNEE_RELATION"::varchar), '') as assignee_relation,
    nullif(trim("REMARK1"::varchar), '') as remark1,
    nullif(trim("COMMENTS"::varchar), '') as comments,
    nullif(trim("EIA_NO"::varchar), '') as eia_no,
    nullif(trim("REMARK4"::varchar), '') as remark4,
    nullif(trim("SCHEME_CODE"::varchar), '') as scheme_code,
    "SCHEME_VERSION"::number as scheme_version,
    "SECTION_CODE"::number as section_code,
    nullif(trim("SR_NO"::varchar), '') as sr_no,
    nullif(trim("PARTNER_ID"::varchar), '') as partner_id,
    nullif(trim("MEMBER_NAME"::varchar), '') as member_name,
    "AGE"::number as age,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("MEM_ADDRESS"::varchar), '') as mem_address,
    "DOB"::timestamp_ntz as dob,
    nullif(trim("MIDDLE_NAME"::varchar), '') as middle_name,
    nullif(trim("LAST_NAME"::varchar), '') as last_name,
    nullif(trim("ADDRESSEE"::varchar), '') as addressee,
    nullif(trim("HOUSE_NO"::varchar), '') as house_no,
    nullif(trim("STREET_NAME"::varchar), '') as street_name,
    nullif(trim("CITY"::varchar), '') as city,
    "PIN_CODE"::number as pin_code,
    nullif(trim("STATE"::varchar), '') as state,
    nullif(trim("TELEPHONE_NO"::varchar), '') as telephone_no,
    nullif(trim("EMAIL_ID"::varchar), '') as email_id,
    nullif(trim("FAX"::varchar), '') as fax,
    "MOBILE_NO"::number as mobile_no,
    nullif(trim("ME"::varchar), '') as me,
    nullif(trim("HCB"::varchar), '') as hcb,
    nullif(trim("CEB"::varchar), '') as ceb,
    nullif(trim("ADDITONAL_COVERAGES"::varchar), '') as additonal_coverages,
    nullif(trim("EXLCUSIONS"::varchar), '') as exlcusions,
    nullif(trim("PASSPORT_NUMBER"::varchar), '') as passport_number,
    nullif(trim("BANK_RM_CODE"::varchar), '') as bank_rm_code,
    nullif(trim("BAGIC_RM_CODE"::varchar), '') as bagic_rm_code,
    nullif(trim("LOAN_ACCOUNT_NO"::varchar), '') as loan_account_no,
    nullif(trim("BANK_CUST_ID"::varchar), '') as bank_cust_id,
    nullif(trim("CA_NO"::varchar), '') as ca_no,
    "CA_DATE"::timestamp_ntz as ca_date,
    "CA_AMT"::number as ca_amt,
    nullif(trim("PREVIOUS_POLICY_DETAILS"::varchar), '') as previous_policy_details,
    nullif(trim("UPLOADED_BY"::varchar), '') as uploaded_by,
    "UPLOADED_ON"::timestamp_ntz as uploaded_on,
    "MEMBER_REF_NUMBER"::number as member_ref_number,
    nullif(trim("BANK_ACCOUNT_NUMBER"::varchar), '') as bank_account_number,
    nullif(trim("PAN_CARD_NO"::varchar), '') as pan_card_no,
    nullif(trim("AADHAR_CARD_NO"::varchar), '') as aadhar_card_no,
    nullif(trim("PRINTED_PMPOL_YN"::varchar), '') as printed_pmpol_yn,
    nullif(trim("PMPOL_PDF_NAME"::varchar), '') as pmpol_pdf_name,
    nullif(trim("PMPOL_FTP_FOLDER_NAME"::varchar), '') as pmpol_ftp_folder_name,
    "PM_POL_ENROLMENT_DATE"::timestamp_ntz as pm_pol_enrolment_date,
    nullif(trim("PLAN"::varchar), '') as plan,
    nullif(trim("PRE_EXIST_DISEASE"::varchar), '') as pre_exist_disease,
    "MEMBER_RISK_INCEPTION_DATE"::timestamp_ntz as member_risk_inception_date,
    "MEMBER_RISK_EXPIRY_DATE"::timestamp_ntz as member_risk_expiry_date,
    "BASE_PREMIUM"::number as base_premium,
    "SERVICE_TAX"::number as service_tax,
    "GROSS_PREMIUM"::number as gross_premium,
    nullif(trim("FAMILY_FLAGGING"::varchar), '') as family_flagging,
    nullif(trim("RELATION"::varchar), '') as relation,
    nullif(trim("BANK_REF_NO_1"::varchar), '') as bank_ref_no_1,
    nullif(trim("BANK_REF_NO_2"::varchar), '') as bank_ref_no_2,
    "EDU_CESS"::number as edu_cess,
    nullif(trim("MAIL_FLAG"::varchar), '') as mail_flag,
    "SB_TAX"::number as sb_tax,
    "KKC"::number as kkc,
    "CESS1"::number as cess1,
    "CESS2"::number as cess2,
    "CESS3"::number as cess3,
    nullif(trim("TAX_CODE"::varchar), '') as tax_code,
    nullif(trim("SERTAX_DESC"::varchar), '') as sertax_desc,
    nullif(trim("EDUCESS_DESC"::varchar), '') as educess_desc,
    nullif(trim("SBCESS_DESC"::varchar), '') as sbcess_desc,
    nullif(trim("KKCCESS_DESC"::varchar), '') as kkccess_desc,
    nullif(trim("CESS1_DESC"::varchar), '') as cess1_desc,
    nullif(trim("CESS2_DESC"::varchar), '') as cess2_desc,
    nullif(trim("CESS3_DESC"::varchar), '') as cess3_desc,
    "SGST"::number as sgst,
    "UTGST"::number as utgst,
    "CGST"::number as cgst,
    "IGST"::number as igst,
    "NCC"::number as ncc,
    nullif(trim("SGST_DESC"::varchar), '') as sgst_desc,
    nullif(trim("UTGST_DESC"::varchar), '') as utgst_desc,
    nullif(trim("CGST_DESC"::varchar), '') as cgst_desc,
    nullif(trim("IGST_DESC"::varchar), '') as igst_desc,
    nullif(trim("NCC_DESC"::varchar), '') as ncc_desc,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date,
    "INC_JOB_UPDATED_AT"::timestamp_ntz as inc_job_updated_at
    from {{ source('partner_test_raw', 'BJAZ_CTNGY_PA_MEM_DTLS') }}

)

select * from source
