-- Staging model for source table BJAZ_CLM_SUPP_EXTN (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    nullif(trim(to_varchar("SUPP_ID")), '') as supp_id,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    nullif(trim(to_varchar("LOC_CODE")), '') as loc_code,
    "FEES"::number as fees,
    nullif(trim("LICENSE_NO"::varchar), '') as license_no,
    "EXPIRY_DATE"::timestamp_ntz as expiry_date,
    nullif(trim("GRADE"::varchar), '') as grade,
    nullif(trim("CLASS"::varchar), '') as class,
    nullif(trim("MOBILE_NO"::varchar), '') as mobile_no,
    nullif(trim("IMD_CODE"::varchar), '') as imd_code,
    nullif(trim("SUB_IMD_CODE"::varchar), '') as sub_imd_code,
    nullif(trim("DEALER_CODE"::varchar), '') as dealer_code,
    nullif(trim("STD_CODE"::varchar), '') as std_code,
    nullif(trim("PAN_NO"::varchar), '') as pan_no,
    nullif(trim("MOU_STATUS"::varchar), '') as mou_status,
    nullif(trim("TOWING_VEHICLE"::varchar), '') as towing_vehicle,
    "NO_TOWING_VEHICLE"::number as no_towing_vehicle,
    "COVERED_AREA"::number as covered_area,
    nullif(trim("WORKSHOP_CATEGORY"::varchar), '') as workshop_category,
    nullif(trim("MFG_CO_NAME"::varchar), '') as mfg_co_name,
    nullif(trim("CONTACT_PERSON_NAME"::varchar), '') as contact_person_name,
    nullif(trim("CONTACT_PERSON_MOB1"::varchar), '') as contact_person_mob1,
    nullif(trim("CONTACT_PERSON_MOB2"::varchar), '') as contact_person_mob2,
    nullif(trim("SPEC_REPAIRER"::varchar), '') as spec_repairer,
    nullif(trim("SURVEYOR_CATEGORY"::varchar), '') as surveyor_category,
    nullif(trim("SURVEYOR_LICENSE_NO"::varchar), '') as surveyor_license_no,
    nullif(trim("BAR_ASSOCIATION_NAME"::varchar), '') as bar_association_name,
    nullif(trim("ENROLMENT_NO"::varchar), '') as enrolment_no,
    nullif(trim("COVERED_COURT_LOC"::varchar), '') as covered_court_loc,
    nullif(trim("SUPP_BANK_NAME"::varchar), '') as supp_bank_name,
    nullif(trim("SUPP_BANK_ACC_NO"::varchar), '') as supp_bank_acc_no,
    nullif(trim("SUR_MODULE_LOGIN"::varchar), '') as sur_module_login,
    nullif(trim("OWNERS_NAME"::varchar), '') as owners_name,
    nullif(trim("OWNERS_MIDDLE_NAME"::varchar), '') as owners_middle_name,
    nullif(trim("OWNERS_SUR_NAME"::varchar), '') as owners_sur_name,
    nullif(trim("OWNERS_FULL_NAME"::varchar), '') as owners_full_name,
    nullif(trim("ORIGIN_COMP"::varchar), '') as origin_comp,
    nullif(trim("COMP_TYPE"::varchar), '') as comp_type,
    nullif(trim("CO_ORD_ADDRESS1"::varchar), '') as co_ord_address1,
    nullif(trim("CO_ORD_ADDRESS2"::varchar), '') as co_ord_address2,
    nullif(trim("ORIGIN_CONT"::varchar), '') as origin_cont,
    nullif(trim("PARENT_CO_NAME"::varchar), '') as parent_co_name,
    nullif(trim("PARENT_CO_ADD_LINE1"::varchar), '') as parent_co_add_line1,
    nullif(trim("PARENT_CO_ADD_LINE2"::varchar), '') as parent_co_add_line2,
    nullif(trim("PARENT_CO_ADD_LINE3"::varchar), '') as parent_co_add_line3,
    nullif(trim("ESTABLISH_YEAR"::varchar), '') as establish_year,
    nullif(trim("ANN_TURNOVER"::varchar), '') as ann_turnover,
    nullif(trim("CON_EXPERTISE"::varchar), '') as con_expertise,
    nullif(trim("OPERATION_PLACE"::varchar), '') as operation_place,
    nullif(trim("OTHER_BAGIC_BUSINESS"::varchar), '') as other_bagic_business,
    nullif(trim("BAGIC_LOCATION"::varchar), '') as bagic_location,
    nullif(trim("WORKSHOP_NAME"::varchar), '') as workshop_name,
    nullif(trim("WORKSHOP_CLASS"::varchar), '') as workshop_class,
    nullif(trim("PAN_STATUS"::varchar), '') as pan_status,
    "PAN_ACK_DT"::timestamp_ntz as pan_ack_dt,
    nullif(trim("SUPP_OWNERSHIP"::varchar), '') as supp_ownership,
    nullif(trim("SUPP_SCOPE"::varchar), '') as supp_scope,
    nullif(trim("PAN_APP_NO"::varchar), '') as pan_app_no,
    "PRIORITY"::number as priority,
    nullif(trim("EMAIL_ID"::varchar), '') as email_id,
    nullif(trim("EW_WHITE_GOODS_FLG"::varchar), '') as ew_white_goods_flg,
    nullif(trim("COUNTRY"::varchar), '') as country,
    nullif(trim("COUNTRY_CODE"::varchar), '') as country_code,
    nullif(trim("REMARKS"::varchar), '') as remarks,
    "LAST_EDIT_DATE"::timestamp_ntz as last_edit_date,
    nullif(trim("LAST_EDIT_BY_USER"::varchar), '') as last_edit_by_user,
    "SUR_LICENSE_EXP_DATE"::timestamp_ntz as sur_license_exp_date,
    nullif(trim("EXP_LOB_FIRE_FLG"::varchar), '') as exp_lob_fire_flg,
    nullif(trim("EXP_LOB_MARIN_CARGO_FLG"::varchar), '') as exp_lob_marin_cargo_flg,
    nullif(trim("EXP_LOB_MOTOR_FLG"::varchar), '') as exp_lob_motor_flg,
    nullif(trim("EXP_LOB_MISCELL_FLG"::varchar), '') as exp_lob_miscell_flg,
    nullif(trim("EXP_LOB_MARINE_HULL_FLG"::varchar), '') as exp_lob_marine_hull_flg,
    nullif(trim("EXP_LOB_ENGINEERING_FLG"::varchar), '') as exp_lob_engineering_flg,
    nullif(trim("EXP_LOB_LOSS_PROFIT_FLG"::varchar), '') as exp_lob_loss_profit_flg,
    nullif(trim("EXP_LOB_WORKMAN_COMP_FLG"::varchar), '') as exp_lob_workman_comp_flg,
    nullif(trim("EMPCODE"::varchar), '') as empcode,
    nullif(trim("TAXPAYER_TYPE"::varchar), '') as taxpayer_type,
    nullif(trim("TCS_STATUS"::varchar), '') as tcs_status,
    nullif(trim("TAN_NUMBER"::varchar), '') as tan_number,
    nullif(trim("IRDA_LICENSE"::varchar), '') as irda_license,
    nullif(trim("LVS_FLAG"::varchar), '') as lvs_flag,
    nullif(trim("IRN_FLAG"::varchar), '') as irn_flag,
    nullif(trim("TWO_YR_ITR_FLAG"::varchar), '') as two_yr_itr_flag,
    nullif(trim("ADHAAR_PAN_LINK_FLAG"::varchar), '') as adhaar_pan_link_flag,
    nullif(trim("MSME_CLASS"::varchar), '') as msme_class,
    nullif(trim("BILLING_STATE"::varchar), '') as billing_state,
    nullif(trim(to_varchar("BILLING_LOC")), '') as billing_loc,
    nullif(trim("IIISLA_MEM_NO"::varchar), '') as iiisla_mem_no,
    nullif(trim("IIISLA_MEM_STATUS"::varchar), '') as iiisla_mem_status,
    nullif(trim("SUPP_EMAIL"::varchar), '') as supp_email,
    "SUPP_MOBILE"::number as supp_mobile,
    nullif(trim("OWNRSHIP_DEPT"::varchar), '') as ownrship_dept,
    nullif(trim("RMK_IF_ANY"::varchar), '') as rmk_if_any,
    nullif(trim("LAWYER_TYPE"::varchar), '') as lawyer_type,
    "MRG_ANNIVERSIRY"::timestamp_ntz as mrg_anniversiry,
    nullif(trim("BAGIC_OFFICE_ADDRESS"::varchar), '') as bagic_office_address,
    "DATE_OF_JOINING"::timestamp_ntz as date_of_joining,
    "YR_EXPERIENCE"::number as yr_experience,
    "NO_OF_BRIEFS"::number as no_of_briefs,
    "NO_OF_CONSUMER"::number as no_of_consumer,
    "NO_OF_JUNIOR"::number as no_of_junior,
    "NO_OF_WC"::number as no_of_wc,
    "NO_OF_MACT"::number as no_of_mact,
    "NO_OF_COMPANIES"::number as no_of_companies,
    nullif(trim("ACD_QUALIFICATION"::varchar), '') as acd_qualification,
    nullif(trim("INTERNET_ACCESS"::varchar), '') as internet_access,
    nullif(trim("ACCESS_ONLINE_JOURNAL"::varchar), '') as access_online_journal,
    nullif(trim("AVAILABILITY_LIBRARY"::varchar), '') as availability_library,
    nullif(trim("PHONE_DETAILS"::varchar), '') as phone_details,
    nullif(trim(to_varchar("LOCATION_CODE")), '') as location_code,
    nullif(trim("TP_MIGRATION_YN"::varchar), '') as tp_migration_yn,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date,
    nullif(trim("INVOICE_PATTERN"::varchar), '') as invoice_pattern,
    nullif(trim("DEDUCTIBLE_EXEMPT"::varchar), '') as deductible_exempt,
    nullif(trim("ON_DUTY_FLAG"::varchar), '') as on_duty_flag,
    nullif(trim("CLAIM_NEAR_ME_FLAG"::varchar), '') as claim_near_me_flag,
    "JW_ID"::number as jw_id,
    nullif(trim("JW_FLAG"::varchar), '') as jw_flag,
    "DUTY_FLAG_UPDATE_DATE"::timestamp_ntz as duty_flag_update_date,
    nullif(trim("ACKNOWLEDGEMENT_FLAG"::varchar), '') as acknowledgement_flag,
    nullif(trim("OD_MIGRATION_YN"::varchar), '') as od_migration_yn,
    "OD_MIGRATION_DATE"::timestamp_ntz as od_migration_date
    from {{ source('partner_raw', 'BJAZ_CLM_SUPP_EXTN') }}

)

select * from source
