-- Staging model for source table BJAZ_EC_MEM_DTLS_EXTN (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    nullif(trim("ACTION_CODE"::varchar), '') as action_code,
    "VERSION_NO"::number as version_no,
    "OBJECT_ID"::number as object_id,
    nullif(trim("TOP_INDICATOR"::varchar), '') as top_indicator,
    "PREVIOUS_VERSION"::number as previous_version,
    "REVERSING_VERSION"::number as reversing_version,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    "EFFETIVE_DATE"::timestamp_ntz as effetive_date,
    nullif(trim("COMMON_PARAM2"::varchar), '') as common_param2,
    nullif(trim("SMOKER_YN"::varchar), '') as smoker_yn,
    nullif(trim("POLICY_REF"::varchar), '') as policy_ref,
    "MEMBER_NO"::number as member_no,
    nullif(trim("NAME"::varchar), '') as name,
    "DATE_OF_BIRTH"::timestamp_ntz as date_of_birth,
    "AGE"::number as age,
    nullif(trim("GENDER"::varchar), '') as gender,
    nullif(trim("RELATION"::varchar), '') as relation,
    "GROSS_INCOME"::number as gross_income,
    nullif(trim("OCCUPATION"::varchar), '') as occupation,
    "SUM_INSURED"::number as sum_insured,
    "PREMIUM"::number as premium,
    nullif(trim("DISEASE_DTLS"::varchar), '') as disease_dtls,
    nullif(trim("PREV_POLICY_DTLS"::varchar), '') as prev_policy_dtls,
    nullif(trim("ASSIGNEE"::varchar), '') as assignee,
    nullif(trim("STATUS"::varchar), '') as status,
    nullif(trim("DIABETES_YN"::varchar), '') as diabetes_yn,
    nullif(trim("HYPERTENSION_YN"::varchar), '') as hypertension_yn,
    nullif(trim("ASTHMA_YN"::varchar), '') as asthma_yn,
    nullif(trim("MEDICAL_CHECKUP"::varchar), '') as medical_checkup,
    nullif(trim("MEDICAL_REPORT"::varchar), '') as medical_report,
    nullif(trim("AGE_PROOF"::varchar), '') as age_proof,
    nullif(trim(to_varchar("PARTNER_ID")), '') as partner_id,
    nullif(trim("FIRST_POLICY_REF"::varchar), '') as first_policy_ref,
    "INCEPTION_DATE"::timestamp_ntz as inception_date,
    nullif(trim("PREV_COMPANY_NAME"::varchar), '') as prev_company_name,
    "PREV_SUM_INSURED"::number as prev_sum_insured,
    nullif(trim("PERV_POL_EXP_DATE"::varchar), '') as perv_pol_exp_date,
    "DEDUCTIBLE_AMT"::number as deductible_amt,
    nullif(trim("CON_POLICY_REF"::varchar), '') as con_policy_ref,
    nullif(trim("CON_COMPANY"::varchar), '') as con_company,
    "CON_EXP_DATE"::timestamp_ntz as con_exp_date,
    "CON_SI"::number as con_si,
    "CON_DEDUCTABLE"::number as con_deductable,
    nullif(trim("COMMON_PARAM1"::varchar), '') as common_param1,
    "EXPIRY_DATE"::timestamp_ntz as expiry_date,
    "HEIGHT_CM"::number as height_cm,
    "WEIGHT_KG"::number as weight_kg,
    "PRE_POL_NCB_PER"::number as pre_pol_ncb_per,
    "CLAIM_RECEIVED"::number as claim_received,
    nullif(trim("CLAIMED_FOR"::varchar), '') as claimed_for,
    "HLTH_INS_POL_YRS"::number as hlth_ins_pol_yrs,
    nullif(trim("SMOKE_CONSUMP"::varchar), '') as smoke_consump,
    nullif(trim("PREGNANT_YN"::varchar), '') as pregnant_yn,
    "PREGNANT_MONTHS"::number as pregnant_months,
    nullif(trim("FMLY_HLTH_COMPLAINS"::varchar), '') as fmly_hlth_complains,
    nullif(trim("ILLNESS_DURATION"::varchar), '') as illness_duration,
    nullif(trim("PAST_4YR_ILLNESS"::varchar), '') as past_4yr_illness,
    nullif(trim("PAST_4YR_TREATMENT"::varchar), '') as past_4yr_treatment,
    "PAST_4YR_TREAT_DATE"::timestamp_ntz as past_4yr_treat_date,
    nullif(trim("PRIOR_4YR_ILLNESS"::varchar), '') as prior_4yr_illness,
    nullif(trim("PRIOR_4YR_TREATMENT"::varchar), '') as prior_4yr_treatment,
    "PRIOR_4YR_TREAT_DATE"::timestamp_ntz as prior_4yr_treat_date,
    nullif(trim("PROPOSAL_REJECT_DTLS"::varchar), '') as proposal_reject_dtls,
    nullif(trim("NOMINEE_RLTN"::varchar), '') as nominee_rltn,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date,
    "INC_JOB_UPDATED_AT"::timestamp_ntz as inc_job_updated_at
    from {{ source('partner_raw', 'BJAZ_EC_MEM_DTLS_EXTN') }}

)

select * from source
