-- HEALTH CLAIM VIEWS (MAXI_HLTH_CLM)
-- Total CLM Views: 36

--1 
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_POLICY_HISTORY_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--2
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_POLICY_CLAIM_HISTORY_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--3
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_AUTHORIZATION_REMARKS_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--4
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_ADJUST', 'name', 'value'
);

--5
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_COPAY_DETAILS_ATTRIBUTES', 'name', 'value'
);

--6
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PARTYDETAILS', 'name', 'value'
);

--7
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_CLAIM_PAYMENT_DETAIL_ATTRIBUTES', 'name', 'value'
);

--8
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_PAYMENT_PAYMENT_CYCLE_PAYMENT_CYCLE_DETAILS', 'name', 'value'
);

--9
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE_ATTRIBUTES', 'name', 'value'
);

--10
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIM_RESERVE_HISTORY_ATTRIBUTES', 'name', 'value'
);

--11
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMBENEFITLIMIT', 'name', 'value'
);

--12
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--13
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--14
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMINWD_DOCUMENTS_ROWS_COLUMNS', 'name', 'value'
);

--15
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMTRANSITION_ATTRIBUTES', 'name', 'value'
);

--16
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_DOCUMENTS_DOCUMENT', 'name', 'value'
);

--17
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_FOLLOWUP_ATTRIBUTES', 'name', 'value'
);

--18
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_COVER_SET_ATTRIBUTE', 'name', 'value'
);

--19
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--20
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_LIST_OF_COVERS_ENTITY_HEADS_ENTITY_GRID_ROWS_ROW_ATTRIBUTES', 'name', 'value'
);

--21
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_NOTES_ATTRIBUTES', 'name', 'value'
);

--22
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PACKAGEANDSERVICE', 'name', 'value'
);

--23
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PREVIOUSINSURANCEDETAIL', 'name', 'value'
);

--24
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_PREVIOUSINSURANCEDETAILS', 'name', 'value'
);

--25
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS_CHILD_ROWS_ROWS_COLUMNS', 'name', 'value'
);

--26
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_QUERY_DETAILS_ROWS_COLUMNS', 'name', 'value'
);

--27
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_RELATION_ATTRIBUTE', 'name', 'value'
);

--28
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS_CHILD_ROWS_ROWS_COLUMNS', 'name', 'value'
);

--29
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_REQUIREMENTS_ROWS_COLUMNS', 'name', 'value'
);

--30
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_PENAL_INTEREST_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--31
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_POLICY_HISTORY', 'name', 'value'
);

--32
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_POLICY_CLAIM_HISTORY', 'name', 'value'
);

--33
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_AUTHORIZATION_REMARKS', 'name', 'value'
);

--34
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_CLAIMDETAIL_ATTRIBUTE', 'name', 'value'
);

--35
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_PENAL_INTEREST', 'name', 'value'
);

--36
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_CLM_VW_DATA_CLAIM_DETAIL_RELATIONS_PARTY_PARTY_DETAILS_ATTRIBUTES', 'name', 'value'
);


-- HEALTH POLICY/UNDERWRITING VIEWS (MAXI_HLTH_UWR)
-- Total UWR Views: 24

--1
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--2
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_BASIC_DETAIL_ATTRIBUTE', 'name', 'value'
);

--3
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_FOLLOW_UP_REPORT', 'name', 'value'
);

--4
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_ADDITIONAL_TEST', 'name', 'value'
);

--5
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_BENEFITS_ATTRIBUTES', 'name', 'value'
);

--6
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_CTMT_ATTRIBUTES', 'name', 'value'
);

--7
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_DECISIONS', 'name', 'value'
);

--8
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEDICALRATING_EXCLUSIONS', 'name', 'value'
);

--9
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS_MULTISET_ATTRIBUTE_ATTRIBUTES', 'name', 'value'
);

--10
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS', 'name', 'value'
);

--11
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_PARTY_PARTY_DETAILS', 'name', 'value'
);

--12
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_PPC_PACKAGE', 'name', 'value'
);

--13
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_PPC_PACKAG_E', 'name', 'value'
);

--14
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_QUESTIONNAIRE', 'name', 'value'
);

--15
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS_ROWS_COLUMNS', 'name', 'value'
);

--16
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_COLUMNS', 'name', 'value'
);

--17
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS_ROWS_COLUMNS', 'name', 'value'
);

--18
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_REQUIREMENT_DETAILS_ROWS_COLUMNS', 'name', 'value'
);

--19
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_VIEW_COLLECTIONS_ADDITIONAL_DETAILS', 'name', 'value'
);

--20
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_REQUIREMENT_DETAILS_ROWS_COLUMNS', 'name', 'value'
);

--21
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_REQUIREMENT_DETAILS_ROWS_CHILD_ROWS_ROWS_COLUMNS', 'name', 'value'
);

--22 (NOT FLATTENED - COMMENTED OUT)
-- CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
--     'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'premiumDetails.premiumDetails', 'name', 'value'
-- );

--23
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'PAYMENT_INFO', 'name', 'value'
);

--24
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'policyPaymentCycleDetails', 'name', 'value'
);
