-- TRAVEL_CLAIM
--1 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--2 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_ATTRIBUTE_PROPERTIES', 'PARAMETER_NAME', 'PARAMETER_VALUE'
);
--3 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_COVER_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_NAME'
);
--4 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_PAYMENT_PAYMENTPROPERTY', 'PARAMETERNAME', 'PARAMETERVALUE'
);
--5 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--6 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_CLM_VW_DATA_CLAIM_DETAILS_CLAIM_RISK_RISK_ATTRIBUTE_PROPERTIES', 'PARAMETER_NAME', 'PARAMETER_VALUE'
);

--TRAVEL POLICY

SELECT PA FROM BAGIC_PROD_MIRROR_DB.MAXI_RAW.

--1 COPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--2 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_COVER_DETAILS_COVER_PROPERTY_SIMPLE_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--3 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--4 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--5 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_MEMBER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--6 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--7 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_INSURED_DETAILS_RISK_PROPERTY_SIMPLE_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--8 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_OFFICE_DETAILS_OFFICE_ADDRESS_ADDRESS_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--9 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
-- 10 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_POLICY_PROPERTY_SIMPLE_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
-- 11 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_ADDRESS_ADDRESS_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--12 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--13 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_POLICY_DETAILS_PROPOSER_DETAILS_PARTY_PROPERTY_SIMPLE_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--14 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--15 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_POLICY_PROPERTY_RULE_LIST', 'PARAM_NAME', 'PARAM_VALUE'
);
--16 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_MULTI_SET_PROPERTY_INPUT_MULTI_SET_DETAIL_INPUT_PROPERTY', 'PARAM_NAME', 'PARAM_VALUE'
);
--17 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_COVER_RISK_COVER_PROPERTY_RULE_LIST', 'PARAM_NAME', 'PARAM_VALUE'
);
--18 COMPLETED
CALL EMPOWER_DB.UTILS.MAXI_RAW_PIVOT_VIEW_PROC_V2(
    'BAGIC_PROD_MIRROR_DB', 'MAXI_RAW', 'NONHLTH_TRV_UWR_VW_DATA_QUOTE_PARAM_DETAILS_RISK_LIST_RISK_PROPERTY_RULE_LIST', 'PARAM_NAME', 'PARAM_VALUE'
);
