{{ config(materialized='view') }}

-- MAXIMUS PARTNER layer-1 cast for BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY_PIVOT_VW_2_1.

with source as (

    select
    nullif(trim(to_varchar("ACCOUNT_CODE")), '') as account_code,
    nullif(trim(to_varchar("ACCOUNT_HOLDER_NAME")), '') as account_holder_name,
    nullif(trim(to_varchar("ACCOUNT_NUMBER")), '') as account_number,
    nullif(trim(to_varchar("ACCOUNT_TYPE")), '') as account_type,
    nullif(trim(to_varchar("ACC_CODE_CR")), '') as acc_code_cr,
    nullif(trim(to_varchar("ACC_CODE_DR")), '') as acc_code_dr,
    nullif(trim(to_varchar("APPROVEDREJECTED_BY")), '') as approvedrejected_by,
    nullif(trim(to_varchar("APPROVEDREJECTED_DATE")), '') as approvedrejected_date,
    try_to_number(to_varchar("APP_EXPENSE_LIMIT")) as app_expense_limit,
    nullif(trim(to_varchar("AVIATION")), '') as aviation,
    try_to_number(to_varchar("AVL_CREDIT_LIMIT")) as avl_credit_limit,
    nullif(trim(to_varchar("BANK_ACCOUNT_NUMBER")), '') as bank_account_number,
    nullif(trim(to_varchar("BANK_BRANCH_NAME")), '') as bank_branch_name,
    nullif(trim(to_varchar("BANK_NAME")), '') as bank_name,
    nullif(trim(to_varchar("CERTIFICATE_ISSUE_DATE")), '') as certificate_issue_date,
    nullif(trim(to_varchar("CERTIFICATE_TYPE")), '') as certificate_type,
    nullif(trim(to_varchar("COMPANY")), '') as company,
    nullif(trim(to_varchar("CONFIRM_BANK_ACCOUNT_NUMBER")), '') as confirm_bank_account_number,
    nullif(trim(to_varchar("CREDIT_CARD_NUMBER")), '') as credit_card_number,
    nullif(trim(to_varchar("CREDIT_CARD_TYPE")), '') as credit_card_type,
    nullif(trim(to_varchar("CREDIT_INSURANCE")), '') as credit_insurance,
    try_to_number(to_varchar("CREDIT_LIMIT")) as credit_limit,
    nullif(trim(to_varchar("CROP_INSURANCE")), '') as crop_insurance,
    nullif(trim(to_varchar("EFFECTIVE_DATE")), '') as effective_date,
    nullif(trim(to_varchar("EMAIL_ID")), '') as email_id,
    nullif(trim(to_varchar("END_DATE")), '') as end_date,
    nullif(trim(to_varchar("ENGINEERING")), '') as engineering,
    nullif(trim(to_varchar("EXPIRY_DATE")), '') as expiry_date,
    nullif(trim(to_varchar("FIRE")), '') as fire,
    nullif(trim(to_varchar("FROM_INCOME")), '') as from_income,
    nullif(trim(to_varchar("GATEWAY_NAME")), '') as gateway_name,
    nullif(trim(to_varchar("HEALTH")), '') as health,
    nullif(trim(to_varchar("IFSC")), '') as ifsc,
    nullif(trim(to_varchar("LIABILITY")), '') as liability,
    try_to_number(to_varchar("MANDATE_AMOUNT")) as mandate_amount,
    nullif(trim(to_varchar("MANDATE_REGISTERED_ON")), '') as mandate_registered_on,
    nullif(trim(to_varchar("MANDATE_TYPE")), '') as mandate_type,
    nullif(trim(to_varchar("MARINE_CARGO")), '') as marine_cargo,
    nullif(trim(to_varchar("MARINE_HULL")), '') as marine_hull,
    nullif(trim(to_varchar("MICR")), '') as micr,
    nullif(trim(to_varchar("MISCELLANEOUS")), '') as miscellaneous,
    nullif(trim(to_varchar("MOBILE_NO")), '') as mobile_no,
    nullif(trim(to_varchar("MOTOR")), '') as motor,
    nullif(trim(to_varchar("NAME_AS_PER_BANK_AC")), '') as name_as_per_bank_ac,
    nullif(trim(to_varchar("NAME_OF_THE_BANK")), '') as name_of_the_bank,
    nullif(trim(to_varchar("NEFT_STATUS")), '') as neft_status,
    nullif(trim(to_varchar("OVERSEAS_MEDICAL")), '') as overseas_medical,
    nullif(trim(to_varchar("PASSPORT_EXPIRY_DATE")), '') as passport_expiry_date,
    nullif(trim(to_varchar("PASSPORT_FILE_NO")), '') as passport_file_no,
    nullif(trim(to_varchar("PASSPORT_ISSUE_COUNTRY")), '') as passport_issue_country,
    nullif(trim(to_varchar("PASSPORT_ISSUE_DATE")), '') as passport_issue_date,
    nullif(trim(to_varchar("PASSPORT_NUMBER")), '') as passport_number,
    nullif(trim(to_varchar("PAYEE_NAME_AS_PER_BANK_RECORD")), '') as payee_name_as_per_bank_record,
    nullif(trim(to_varchar("PAYEE_TYPE")), '') as payee_type,
    nullif(trim(to_varchar("PAYMENT_PLAN_NAME")), '') as payment_plan_name,
    nullif(trim(to_varchar("PAYMENT_PLAN_TYPE")), '') as payment_plan_type,
    nullif(trim(to_varchar("PENNYDROPLESS_FLAG")), '') as pennydropless_flag,
    nullif(trim(to_varchar("PERSONAL_ACCIDENT")), '') as personal_accident,
    nullif(trim(to_varchar("PRIMARY_SECONDARY")), '') as primary_secondary,
    nullif(trim(to_varchar("PROPERTY")), '') as property,
    nullif(trim(to_varchar("REMARKS")), '') as remarks,
    nullif(trim(to_varchar("RURAL")), '') as rural,
    nullif(trim(to_varchar("SECTION_CODE")), '') as section_code,
    nullif(trim(to_varchar("STAKE_CODE")), '') as stake_code,
    nullif(trim(to_varchar("START_DATE")), '') as start_date,
    nullif(trim(to_varchar("STATUS")), '') as status,
    nullif(trim(to_varchar("TAX_TO_DEDUCT")), '') as tax_to_deduct,
    nullif(trim(to_varchar("TDS_CERTIFICATE_NO")), '') as tds_certificate_no,
    try_to_number(to_varchar("TDS_RATE")) as tds_rate,
    nullif(trim(to_varchar("TDS_SECTION_CODE")), '') as tds_section_code,
    try_to_number(to_varchar("TEMP_CREDIT_LIMIT")) as temp_credit_limit,
    nullif(trim(to_varchar("TEMP_CR_LIMIT_EXP_DATE")), '') as temp_cr_limit_exp_date,
    nullif(trim(to_varchar("TEMP_CR_LIMIT_START_DATE")), '') as temp_cr_limit_start_date,
    nullif(trim(to_varchar("TO_INCOME")), '') as to_income,
    nullif(trim(to_varchar("TRAVEL")), '') as travel,
    nullif(trim(to_varchar("UMRN_NO")), '') as umrn_no,
    nullif(trim(to_varchar("USER_ID")), '') as user_id,
    nullif(trim(to_varchar("WEATHER_INSURANCE")), '') as weather_insurance,
    nullif(trim(to_varchar("WITH_EFFECTIVE_FROM")), '') as with_effective_from,
    nullif(trim(to_varchar("WORKMENS_COMPENSATION")), '') as workmens_compensation,
    nullif(trim(to_varchar("FOREIGN_KEY")), '') as foreign_key,
    nullif(trim(to_varchar("KEY_HASH")), '') as key_hash,
    nullif(trim(to_varchar("PARENT_KEY_HASH")), '') as parent_key_hash
    from {{ source('maximus_partner', 'BUSINESS_PARTNERS_VW_DATA_PARTY_DETAIL_PARTY_PROPERTY_MULTI_SET_PROPERTY_MULTI_SET_DETAIL_PROPERTY_PIVOT_VW_2_1') }}

)

select * from source
