name: 'bagic_ontology'
version: '1.0.0'

profile: 'demo_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bagic_ontology:
    +pre-hook:
      - "{% if target.name == 'dev' %}INSERT INTO BAGIC_PREPROD_CURATED_DB.UTILS.MAXI_RAW_DBT_MODEL_RUN_LOG (model_name, status, run_id, run_start_timestamp, materialization, schema_name, target_table) SELECT '{{ this.name }}', 'RUNNING', '{{ invocation_id }}', '{{ run_started_at }}'::TIMESTAMP_NTZ, '{{ config.get(\"materialized\", \"view\") }}', '{{ this.schema }}', '{{ this.database }}.{{ this.schema }}.{{ this.name }}'{% endif %}"
    +post-hook:
      - "{% if target.name == 'dev' %}UPDATE BAGIC_PREPROD_CURATED_DB.UTILS.MAXI_RAW_DBT_MODEL_RUN_LOG SET status = 'SUCCESS' WHERE model_name = '{{ this.name }}' AND run_id = '{{ invocation_id }}' AND status = 'RUNNING'{% endif %}"
    staging:
      +materialized: view
      +schema: BGIL_DEV_DATA_MODEL
      partner:
        +materialized: view
        +schema: BGIL_DEV_DATA_MODEL
        +tags: ["partner", "partner_stg"]
      travel:
        +materialized: view
        +schema: BGIL_DEV_DATA_MODEL
        +tags: ["travel", "travel_stg"]
      health:
        +materialized: view
        +schema: BGIL_DEV_DATA_MODEL
        +tags: ["health", "health_stg"]
    raw_vault:
      hubs:
        +schema: BGIL_DEV_DATA_MODEL
        +materialized: incremental
        +incremental_strategy: merge
        +tags: ["hubs"]
      links:
        +schema: BGIL_DEV_DATA_MODEL
        +materialized: incremental
        +incremental_strategy: merge
        +tags: ["links"]
      satellites:
        +schema: BGIL_DEV_DATA_MODEL
        +materialized: incremental
        +incremental_strategy: merge
        partner:
          +tags: ["partner", "partner_satellite"]
        travel:
          +tags: ["travel", "travel_satellite"]
        health:
          +tags: ["health", "health_satellite"]

# satellite:
#       raw_stage:
#         +materialized: view
#         +schema: UTILS
#       stage:
#         +materialized: view
#         +schema: UTILS
#       raw_vault:
#         +materialized: incremental
#         +schema: UTILS
#     hubs:
#       raw_stage:
#         +materialized: view
#         +schema: UTILS
#       stage:
#         +materialized: view
#         +schema: UTILS
#       raw_vault:
#         +materialized: incremental
#         +schema: UTILS
#     links:
#       raw_stage:BAGIC_PREPROD_CURATED_DB.UTILS.STGG_PARTNER_ADDRESS
#         +materialized: view
#         +schema: MAXI_STG
#       stage:
#         +materialized: view
#         +schema: MAXI_STG
#       raw_vault:
#         +materialized: incremental
#         +schema: MAXI_RAW_VAULT
      
      
