CREATE OR REPLACE PROCEDURE TRANSACTIONAL.BJAZ_CLIMATESAFE_CR_LOAD("MIRROR_DB" VARCHAR(16777216), "F_DATE" DATE DEFAULT CURRENT_DATE(), "T_DATE" DATE DEFAULT CURRENT_DATE())
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
v_sqltext varchar;

BEGIN

v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_DIM'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_DIM
      SELECT c_claim_id_sk,
       c_cause_of_loss,
       c_claim_no,
       DECODE (UPPER (C_CLAIM_STATUS), ''''OPEN'''', ''''OPEN'''', ''''CLOSED'''') C_CLAIM_STATUS,
       C_KIND_OF_LOSS,
       c_accident_loc,
       TO_DATE(TO_CHAR(TO_DATE(C_LOSS_DATE,''''YYYY-MM-DD''''),''''DD-MM-YYYY''''),''''DD-MM-YYYY'''') AS C_LOSS_DATE,
       c_loss_time,
       TO_date(TO_CHAR(TO_date(C_INTI_DATE,''''YYYY-MM-DD''''),''''DD-MON-YYYY'''')) AS C_INTI_DATE,
       c_regn_date,
       c_app_date,
       c_sur_app_date,
       c_sur_rep_date,
       TO_date(TO_CHAR(TO_date(C_CHQ_ISS_DATE,''''YYYY-MM-DD''''),''''DD-MON-YYYY'''')) AS C_CHQ_ISS_DATE,
       TO_date(TO_CHAR(TO_date(C_CLO_DATE,''''YYYY-MM-DD''''),''''DD-MON-YYYY'''')) AS C_CLO_DATE ,
       c_sur_name,
       c_sur_lic_no,
       c_rep_name,
       c_bill_date,
       c_dri_lic_no,
       c_off_loc_id,
       c_parts_claimed,
       c_name_of_in1,
       c_name_of_in2,
       c_name_of_in3,
       c_name_of_in4,
       c_name_of_in5,
       c_adv_name,
        c_claim_type,
       c_comments,
       c_paid_flag,
       c_policy_grain,
       c_claim_regd_by,
       TO_DATE(TO_CHAR(TO_DATE(C_LAST_REOPEN_DATE,''''YYYY-MM-DD''''),''''DD-MM-YYYY''''),''''DD-MM-YYYY'''') AS C_LAST_REOPEN_DATE,
       c_reopen_flag,
       c_cons_forum_flag,
       c_ombsman_flag,
       c_ligitation_flag,
       c_recpt_psr_date,
       c_recpt_fsr_date,
       c_all_doc_date,
       NVL (c_court_flag, ''''Normal Claim'''') c_court_flag,
       c_special_comments,
       TO_DATE(TO_CHAR(TO_DATE(C_FIRST_REOPEN_DATE,''''YYYY-MM-DD''''),''''DD-MM-YYYY''''),''''DD-MM-YYYY'''') AS C_FIRST_REOPEN_DATE,
       c_mrn_transporter_name,
       c_invoice_no,
       c_settlemnt_type,
       c_delay_reason,
       c_emeditek_claim_no,
       c_rfa_date,
       c_event_code,
       c_tpa_status,
       c_invoice_date,
       c_fsr_psr_status,
       c_place_of_loss,
       c_landmark,
       c_area,
       c_state,
       c_city,
       c_pincode,
       c_journey_from,
       c_journey_to,
       c_consignee_name,
       c_consigner_name,
       c_survey_location,
       c_goods_details,
       c_next_rvw_date,
       c_last_rvw_remarks,
       c_last_rvw_date,
       c_fplm_flag,
       A.C_claim_id c_claim_id,
       c_reopen_remark,
       c_reopen_by,
       base_sum_insured,
       addl_excess,
       voluntary_excess,
       compulsory_excess,
       expense_app_date,
       TO_date(TO_CHAR(TO_date(LOSS_APP_DATE,''''YYYY-MM-DD''''),''''DD-MON-YYYY'''')) AS LOSS_APP_DATE ,
       net_assessed_amount,
       depreciation_amount,
       c_portal_flag
  FROM BAGIC_PROD_MIRROR_DB.CLIMATESAFE.ODS_CLAIM_DIM a
 WHERE   TOP_INDICATOR=''''Y'''';'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext :=''MERGE INTO TRANSACTIONAL.ODS_CLAIM_DIM ocd
        USING (SELECT c_cause_of_loss,
                      c_claim_no,
                      c_claim_status,
                      c_kind_of_loss,
                      c_accident_loc,
                      DATE_TRUNC (''''day'''',c_loss_date) c_loss_date,
                      c_loss_time,
                      DATE_TRUNC (''''day'''',c_inti_date) c_inti_date,
                      DATE_TRUNC (''''day'''',c_regn_date) c_regn_date,
                      c_app_date,
                      c_sur_app_date,
                      c_sur_rep_date,
                      c_chq_iss_date,
                      c_clo_date,
                      c_sur_name,
                      c_sur_lic_no,
                      c_rep_name,
                      c_bill_date,
                      c_dri_lic_no,
                      c_off_loc_id,
                      c_parts_claimed,
                      c_name_of_in1,
                      c_name_of_in2,
                      c_name_of_in3,
                      c_name_of_in4,
                      c_name_of_in5,
                      c_adv_name,
                      c_claim_type,
                      c_comments,
                      c_paid_flag,
                      c_policy_grain,
                      c_claim_regd_by,
                      c_last_reopen_date,
                      c_reopen_flag,
                      c_cons_forum_flag,
                      c_ombsman_flag,
                      c_ligitation_flag,
                      c_recpt_psr_date,
                      c_recpt_fsr_date,
                      c_all_doc_date,
                      c_court_flag,
                      c_special_comments,
                      c_first_reopen_date,
                      c_mrn_transporter_name,
                      c_invoice_no,
                      c_settlemnt_type,
                      c_delay_reason,
                      c_emeditek_claim_no,
                      c_rfa_date,
                      c_event_code,
                      c_tpa_status,
                      c_invoice_date,
                      c_fsr_psr_status,
                      c_place_of_loss,
                      c_landmark,
                      c_area,
                      c_state,
                      c_city,
                      c_pincode,
                      c_journey_from,
                      c_journey_to,
                      c_consignee_name,
                      c_consigner_name,
                      c_survey_location,
                      c_goods_details,
                      c_next_rvw_date,
                      c_last_rvw_remarks,
                      c_last_rvw_date,
                      c_fplm_flag,
                      c_claim_id,
                      c_reopen_remark,
                      c_reopen_by,
                      base_sum_insured,
                      addl_excess,
                      voluntary_excess,
                      compulsory_excess,
                      expense_app_date,
                      loss_app_date,
                      net_assessed_amount,
                      depreciation_amount,
                      c_portal_flag
                 FROM INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_DIM) mocd
           ON (ocd.c_claim_no = mocd.c_claim_no)
   WHEN MATCHED
   THEN
      UPDATE SET ocd.c_cause_of_loss = mocd.c_cause_of_loss,
                 ocd.c_claim_status = mocd.c_claim_status,
                 ocd.c_kind_of_loss = mocd.c_kind_of_loss,
                 ocd.c_accident_loc = mocd.c_accident_loc,
                 ocd.c_loss_date = mocd.c_loss_date,
                 ocd.c_loss_time = mocd.c_loss_time,
                 ocd.c_inti_date = mocd.c_inti_date,
                 --ocd.c_regn_date=mocd.c_regn_date,
                 ocd.c_app_date = mocd.c_app_date,
                 ocd.c_sur_app_date = mocd.c_sur_app_date,
                 ocd.c_sur_rep_date = mocd.c_sur_rep_date,
                 ocd.c_chq_iss_date = mocd.c_chq_iss_date,
                 ocd.c_clo_date = mocd.c_clo_date,
                 ocd.c_sur_name = mocd.c_sur_name,
                 ocd.c_sur_lic_no = mocd.c_sur_lic_no,
                 ocd.c_rep_name = mocd.c_rep_name,
                 ocd.c_bill_date = mocd.c_bill_date,
                 ocd.c_dri_lic_no = mocd.c_dri_lic_no,
                 ocd.c_off_loc_id = mocd.c_off_loc_id,
                 ocd.c_parts_claimed = mocd.c_parts_claimed,
                 ocd.c_name_of_in1 = mocd.c_name_of_in1,
                 ocd.c_name_of_in2 = mocd.c_name_of_in2,
                 ocd.c_name_of_in3 = mocd.c_name_of_in3,
                 ocd.c_name_of_in4 = mocd.c_name_of_in4,
                 ocd.c_name_of_in5 = mocd.c_name_of_in5,
                 ocd.c_adv_name = mocd.c_adv_name,
                 ocd.c_claim_type = mocd.c_claim_type,
                 ocd.c_comments = mocd.c_comments,
                 ocd.c_paid_flag = mocd.c_paid_flag,
                 ocd.c_policy_grain = mocd.c_policy_grain,
                 ocd.c_claim_regd_by = mocd.c_claim_regd_by,
                 ocd.c_last_reopen_date = mocd.c_last_reopen_date,
                 ocd.c_reopen_flag = mocd.c_reopen_flag,
                 ocd.c_cons_forum_flag = mocd.c_cons_forum_flag,
                 ocd.c_ombsman_flag = mocd.c_ombsman_flag,
                 ocd.c_ligitation_flag = mocd.c_ligitation_flag,
                 ocd.c_recpt_psr_date = mocd.c_recpt_psr_date,
                 ocd.c_recpt_fsr_date = mocd.c_recpt_fsr_date,
                 ocd.c_all_doc_date = mocd.c_all_doc_date,
                 ocd.c_court_flag = mocd.c_court_flag,
                 ocd.c_special_comments = mocd.c_special_comments,
                 ocd.c_first_reopen_date = mocd.c_first_reopen_date,
                 ocd.c_mrn_transporter_name = mocd.c_mrn_transporter_name,
                 ocd.c_invoice_no = mocd.c_invoice_no,
                 ocd.c_settlemnt_type = mocd.c_settlemnt_type,
                 ocd.c_delay_reason = mocd.c_delay_reason,
                 ocd.c_emeditek_claim_no = mocd.c_emeditek_claim_no,
                 ocd.c_rfa_date = mocd.c_rfa_date,
                 ocd.c_event_code = mocd.c_event_code,
                 ocd.c_tpa_status = mocd.c_tpa_status,
                 ocd.c_invoice_date = mocd.c_invoice_date,
                 ocd.c_fsr_psr_status = mocd.c_fsr_psr_status,
                 ocd.c_place_of_loss = mocd.c_place_of_loss,
                 ocd.c_landmark = mocd.c_landmark,
                 ocd.c_area = mocd.c_area,
                 ocd.c_state = mocd.c_state,
                 ocd.c_city = mocd.c_city,
                 ocd.c_pincode = mocd.c_pincode,
                 ocd.c_journey_from = mocd.c_journey_from,
                 ocd.c_journey_to = mocd.c_journey_to,
                 ocd.c_consignee_name = mocd.c_consignee_name,
                 ocd.c_consigner_name = mocd.c_consigner_name,
                 ocd.c_survey_location = mocd.c_survey_location,
                 ocd.c_goods_details = mocd.c_goods_details,
                 ocd.c_next_rvw_date = mocd.c_next_rvw_date,
                 ocd.c_last_rvw_remarks = mocd.c_last_rvw_remarks,
                 ocd.c_last_rvw_date = mocd.c_last_rvw_date,
                 ocd.c_fplm_flag = mocd.c_fplm_flag,
                 ocd.c_claim_id = mocd.c_claim_id,
                 ocd.c_reopen_remark = mocd.c_reopen_remark,
                 ocd.c_reopen_by = mocd.c_reopen_by,
                 ocd.base_sum_insured = mocd.base_sum_insured,
                 ocd.addl_excess = mocd.addl_excess,
                 ocd.voluntary_excess = mocd.voluntary_excess,
                 ocd.compulsory_excess = mocd.compulsory_excess,
                 ocd.expense_app_date = mocd.expense_app_date,
                 ocd.loss_app_date = mocd.loss_app_date,
                 ocd.net_assessed_amount = mocd.net_assessed_amount,
                 ocd.depreciation_amount = mocd.depreciation_amount,
                 ocd.c_portal_flag = mocd.c_portal_flag,
                 ocd.ETL_REFRESH_AT = CURRENT_TIMESTAMP()
   WHEN NOT MATCHED
   THEN
      INSERT     (c_claim_id_sk,
                  c_cause_of_loss,
                  c_claim_no,
                  c_claim_status,
                  c_kind_of_loss,
                  c_accident_loc,
                  c_loss_date,
                  c_loss_time,
                  c_inti_date,
                  c_regn_date,
                  c_app_date,
                  c_sur_app_date,
                  c_sur_rep_date,
                  c_chq_iss_date,
                  c_clo_date,
                  c_sur_name,
                  c_sur_lic_no,
                  c_rep_name,
                  c_bill_date,
                  c_dri_lic_no,
                  c_off_loc_id,
                  c_parts_claimed,
                  c_name_of_in1,
                  c_name_of_in2,
                  c_name_of_in3,
                  c_name_of_in4,
                  c_name_of_in5,
                  c_adv_name,
                  c_claim_type,
                  c_comments,
                  c_paid_flag,
                  c_policy_grain,
                  c_claim_regd_by,
                  c_last_reopen_date,
                  c_reopen_flag,
                  c_cons_forum_flag,
                  c_ombsman_flag,
                  c_ligitation_flag,
                  c_recpt_psr_date,
                  c_recpt_fsr_date,
                  c_all_doc_date,
                  c_court_flag,
                  c_special_comments,
                  c_first_reopen_date,
                  c_mrn_transporter_name,
                  c_invoice_no,
                  c_settlemnt_type,
                  c_delay_reason,
                  c_emeditek_claim_no,
                  c_rfa_date,
                  c_event_code,
                  c_tpa_status,
                  c_invoice_date,
                  c_fsr_psr_status,
                  c_place_of_loss,
                  c_landmark,
                  c_area,
                  c_state,
                  c_city,
                  c_pincode,
                  c_journey_from,
                  c_journey_to,
                  c_consignee_name,
                  c_consigner_name,
                  c_survey_location,
                  c_goods_details,
                  c_next_rvw_date,
                  c_last_rvw_remarks,
                  c_last_rvw_date,
                  c_fplm_flag,
                  c_claim_id,
                  c_reopen_remark,
                  c_reopen_by,
                  base_sum_insured,
                  addl_excess,
                  voluntary_excess,
                  compulsory_excess,
                  expense_app_date,
                  loss_app_date,
                  net_assessed_amount,
                  depreciation_amount,
                  c_portal_flag)
          VALUES (UTILS.CLAIM_SURROGATE_KEY.NEXTVAL,
                  mocd.c_cause_of_loss,
                  mocd.c_claim_no,
                  mocd.c_claim_status,
                  mocd.c_kind_of_loss,
                  mocd.c_accident_loc,
                  mocd.c_loss_date,
                  mocd.c_loss_time,
                  mocd.c_inti_date,
                  mocd.c_regn_date,
                  mocd.c_app_date,
                  mocd.c_sur_app_date,
                  mocd.c_sur_rep_date,
                  mocd.c_chq_iss_date,
                  mocd.c_clo_date,
                  mocd.c_sur_name,
                  mocd.c_sur_lic_no,
                  mocd.c_rep_name,
                  mocd.c_bill_date,
                  mocd.c_dri_lic_no,
                  mocd.c_off_loc_id,
                  mocd.c_parts_claimed,
                  mocd.c_name_of_in1,
                  mocd.c_name_of_in2,
                  mocd.c_name_of_in3,
                  mocd.c_name_of_in4,
                  mocd.c_name_of_in5,
                  mocd.c_adv_name,
                  mocd.c_claim_type,
                  mocd.c_comments,
                  mocd.c_paid_flag,
                  mocd.c_policy_grain,
                  mocd.c_claim_regd_by,
                  mocd.c_last_reopen_date,
                  mocd.c_reopen_flag,
                  mocd.c_cons_forum_flag,
                  mocd.c_ombsman_flag,
                  mocd.c_ligitation_flag,
                  mocd.c_recpt_psr_date,
                  mocd.c_recpt_fsr_date,
                  mocd.c_all_doc_date,
                  mocd.c_court_flag,
                  mocd.c_special_comments,
                  mocd.c_first_reopen_date,
                  mocd.c_mrn_transporter_name,
                  mocd.c_invoice_no,
                  mocd.c_settlemnt_type,
                  mocd.c_delay_reason,
                  mocd.c_emeditek_claim_no,
                  mocd.c_rfa_date,
                  mocd.c_event_code,
                  mocd.c_tpa_status,
                  mocd.c_invoice_date,
                  mocd.c_fsr_psr_status,
                  mocd.c_place_of_loss,
                  mocd.c_landmark,
                  mocd.c_area,
                  mocd.c_state,
                  mocd.c_city,
                  mocd.c_pincode,
                  mocd.c_journey_from,
                  mocd.c_journey_to,
                  mocd.c_consignee_name,
                  mocd.c_consigner_name,
                  mocd.c_survey_location,
                  mocd.c_goods_details,
                  mocd.c_next_rvw_date,
                  mocd.c_last_rvw_remarks,
                  mocd.c_last_rvw_date,
                  mocd.c_fplm_flag,
                  mocd.c_claim_id,
                  mocd.c_reopen_remark,
                  mocd.c_reopen_by,
                  mocd.base_sum_insured,
                  mocd.addl_excess,
                  mocd.voluntary_excess,
                  mocd.compulsory_excess,
                  mocd.expense_app_date,
                  mocd.loss_app_date,
                  mocd.net_assessed_amount,
                  mocd.depreciation_amount,
                  mocd.c_portal_flag)'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''UPDATE TRANSACTIONAL.ods_claim_dim
      SET MAXIMUS_FLAG = ''''C''''
    WHERE c_claIM_NO IN (SELECT C_CLAIM_NO FROM INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_DIM)'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_FACT_MV'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_FACT_MV
      SELECT c.c_claim_id_sk,
             d.p_policy_no_sk,
             company_code,
             b.t_date_id_sk,
             cc_cc_claimtype_id_sk,
             r_reserve_type_id_sk r_reserve_type_id,
			 paid_claim,
			 reserve_amount,
			 salvage_amount,
			 recovery_amount,
			 service_tax,
			 net_paid,
             NVL(net_tax,0)AS net_tax
        FROM BAGIC_PROD_MIRROR_DB.CLIMATESAFE.ODS_CLAIM_FACT_MV a,
             TRANSACTIONAL.ODS_TIME_DIM b,
             TRANSACTIONAL.ods_claim_dim c,
             TRANSACTIONAL.ods_policy_dim d,
             TRANSACTIONAL.ODS_RESERVE_DIM e
       WHERE
            b.t_date_desc = DATE_TRUNC(''''DAY'''',a.trans_date)
			AND  c.c_claim_no = a.c_claim_no
			 AND a.pai_policy_number = d.p_policy_number
			 AND UPPER (NVL (a.r_reserve_type, ''''X'''')) = UPPER (NVL (e.r_reserve_type, ''''Y''''))
			 AND P_CURRENT_INDICATOR = 1
			 AND DATE_TRUNC(''''DAY'''',trans_date) = DATE_TRUNC(''''DAY'''', CURRENT_DATE() - 1)  '';
 EXECUTE IMMEDIATE v_sqltext;

 v_sqltext := ''INSERT INTO TRANSACTIONAL.ODS_claim_fact_mv
                 (
                c_claim_id_sk,
                p_policy_no_sk,
                company_code,
                t_date_id_sk,
                cc_cc_claimtype_id_sk,
                r_reserve_type_id,
                paid_claim,
                reserve_amount,
                salvage_amount,
                recovery_amount,
                service_tax,
                net_paid,
                net_tax,
                MAXIMUS_FLAG,
                RECOVERY_INITIATED,
                RECOVERY_DONE,
                RECOVERY_PENDING
                )
  SELECT c_claim_id_sk,
         p_policy_no_sk,
         company_code,
         t_date_id_sk,
         1 cc_cc_claimtype_id_sk,
         r_reserve_type_id,
         SUM (paid_claim) paid_claim,
         SUM (reserve_amount) reserve_amount,
         SUM (salvage_amount) salvage_amount,
         SUM (recovery_amount) recovery_amount,
         SUM (service_tax) service_tax,
         SUM (net_paid) net_paid,
         SUM (net_tax) net_tax,
         ''''C'''',
         NULL RECOVERY_INITIATED,
         NULL RECOVERY_DONE,
         NULL RECOVERY_PENDING
    FROM INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_FACT_MV
GROUP BY c_claim_id_sk,
         p_policy_no_sk,
         company_code,
         t_date_id_sk,
         cc_cc_claimtype_id_sk,
         r_reserve_type_id'';
EXECUTE IMMEDIATE v_sqltext;


 v_sqltext := ''INSERT INTO INTERMEDIATE.rpt_CLIMATESAFE_cr_bkp
      SELECT c_claim_id_sk,
             p_policy_no_sk,
             company_code,
             t_date_id_sk,
             cc_cc_claimtype_id_sk,
             r_reserve_type_id,
             paid_claim,
             reserve_amount,
             salvage_amount,
             recovery_amount,
             service_tax,
             net_paid,
             net_tax,
             CURRENT_DATE() load_date
        FROM INTERMEDIATE.STG_CLIMATESAFE_ODS_CLAIM_FACT_MV'';
 EXECUTE IMMEDIATE v_sqltext;



EXECUTE IMMEDIATE ''COMMIT'';
    RETURN ''Procedure executed successfully'';

EXCEPTION
    WHEN OTHER THEN
         EXECUTE IMMEDIATE ''ROLLBACK'';
         RAISE ;
         RETURN ''Error occurred: '' || SQLERRM || ''\\n'' || ''SQL: '' || ''\\n'' || v_sqltext;

END;
';