CREATE OR REPLACE PROCEDURE TRANSACTIONAL.WRK_DOCUMENT_LIST_PRC("MIRROR_DB" VARCHAR(16777216), "F_DATE" DATE DEFAULT CURRENT_DATE(), "T_DATE" DATE DEFAULT CURRENT_DATE())
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
v_sqltext varchar;
BEGIN

v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_NON_MOTOR_DOC_LIST_STG'';

EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT
         INTO  INTERMEDIATE.WRK_NON_MOTOR_DOC_LIST_STG
      SELECT
            A.FIELD_9 AS CLAIM_NO, REPLACE(B.NAME,''''�'''',''''¿'''') DOCUMENTNAME, B.CREATEDDATETIME
        FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.DDT_4 A,
             ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.PDBDOCUMENT B,
             ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.PDBDOCUMENTCONTENT C,
             ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.PDBFOLDER D,
             TRANSACTIONAL.MV_CLAIM_REGISTER E,
             --INTERMEDIATE.WRK_NM_PRODUCT_LIST F
             PROD_DWH_MIGRATED_DB.PROD.WRK_NM_PRODUCT_LIST F
       WHERE     A.FOLDDOCINDEX = C.PARENTFOLDERINDEX
             AND C.DOCUMENTINDEX = B.DOCUMENTINDEX
             AND C.PARENTFOLDERINDEX = FOLDERINDEX
             AND D.DATADEFINITIONINDEX = 4
             AND A.FIELD_9 = C_CLAIM_NO
             AND E.P_PRODUCT_ID = F.P_PRODUCT_ID
             AND TOP_INDICATOR = ''''Y''''
             AND UTILS.MY_TRIM (A.FIELD_9) IS NOT NULL
      MINUS
      SELECT CLAIM_NO, REPLACE(DOCUMENTNAME,''''�'''',''''¿''''), CREATEDDATETIME FROM INTERMEDIATE.WRK_NON_MOTOR_DOCUMENT_LIST'';

EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.WRK_NON_MOTOR_DOCUMENT_LIST
      SELECT * FROM INTERMEDIATE.WRK_NON_MOTOR_DOC_LIST_STG'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''UPDATE TRANSACTIONAL.MV_CLAIM_REGISTER C
      SET DOC_UPLOAD_FLAG = ''''Y''''
    WHERE EXISTS
             (SELECT 1
                FROM INTERMEDIATE.WRK_NON_MOTOR_DOC_LIST_STG A
               WHERE A.CLAIM_NO = C.C_CLAIM_NO)'';
EXECUTE IMMEDIATE v_sqltext;

EXECUTE IMMEDIATE ''COMMIT'';
    RETURN ''Procedure executed successfully'';

EXCEPTION
    WHEN OTHER THEN
        EXECUTE IMMEDIATE ''ROLLBACK'';
        RAISE ;
        RETURN ''Error occurred: '' || SQLERRM || ''\\\\n'' || ''SQL: '' || ''\\\\n'' || v_sqltext;

END;
';