CREATE OR REPLACE PROCEDURE TRANSACTIONAL.WRK_EVENT_CODE_UPDATE_PRC("MIRROR_DB" VARCHAR(16777216), "F_DATE" DATE DEFAULT CURRENT_DATE(), "T_DATE" DATE DEFAULT CURRENT_DATE())
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '

DECLARE
v_sqltext varchar;

BEGIN

v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_EVENT_DATA'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''insert  into  INTERMEDIATE.WRK_EVENT_DATA
      SELECT CLM_REF, event_code
        FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_WB_CLM_BASE_MOT_EXT A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
       WHERE     A.CLAIM_ID = B.CLAIM_ID
             AND DATE_TRUNC(''''DAY'''', TO_DATE(UPDATED_ON)) >= DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')) - 3
      UNION ALL
      SELECT  CLM_REF, event_code
        FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_CLM_BASE_MOT_EXT A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
       WHERE     A.CLAIM_ID = B.CLAIM_ID
             AND DATE_TRUNC(''''DAY'''', TO_DATE(NVL (UPDATED_ON, NOTIFICATION_DATE))) >=
                    DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')) - 3'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''DELETE FROM INTERMEDIATE.WRK_EVENT_DATA
    WHERE CLM_REF IN (SELECT CLM_REF
                        FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_HM_CLM_REGISTER A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
                       WHERE A.CLAIM_ID = B.CLAIM_ID)'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_EVENT_DATA_1'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT
      INTO  INTERMEDIATE.WRK_EVENT_DATA_1
SELECT CLM_REF, C.EVENT_CODE, EVENT_DESC
  FROM INTERMEDIATE.WRK_EVENT_DATA A,
       (SELECT DISTINCT EVENT_CODE, EVENT_DESC FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_CLM_EVENTS) C,
       TRANSACTIONAL.ODS_CLAIM_DIM D
 WHERE     A.EVENT_CODE = C.EVENT_CODE
       AND A.CLM_REF = D.C_CLAIM_NO
       AND NVL (EVENT_DESC, ''''XYZ'''') <> NVL (C_EVENT_CODE, ''''XYZ'''')'';
EXECUTE IMMEDIATE v_sqltext;

BEGIN

v_sqltext := ''MERGE INTO TRANSACTIONAL.ODS_CLAIM_DIM A
        USING (SELECT distinct CLM_REF, C.EVENT_CODE, EVENT_DESC
                 FROM INTERMEDIATE.WRK_EVENT_DATA A,
                      (SELECT DISTINCT EVENT_CODE, EVENT_DESC
                         FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_CLM_EVENTS) C,
                      TRANSACTIONAL.ODS_CLAIM_DIM D
                WHERE     A.EVENT_CODE = C.EVENT_CODE
                      AND A.CLM_REF = D.C_CLAIM_NO
                      AND NVL (EVENT_DESC, ''''XYZ'''') <>
                             NVL (C_EVENT_CODE, ''''XYZ''''))
           ON (CLM_REF = A.C_CLAIM_NO)
   WHEN MATCHED
   THEN
      UPDATE SET C_EVENT_CODE = EVENT_DESC, ETL_REFRESH_AT = CURRENT_TIMESTAMP()'';
EXECUTE IMMEDIATE v_sqltext;

END;

BEGIN

v_sqltext := ''MERGE INTO TRANSACTIONAL.ODS_CLAIM_DIM A
        USING (SELECT CLM_REF, CATASTROPHE_EVENT, CATASTROPHE_REMARK
                 FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_HM_CLM_REGISTER A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
                WHERE     A.CLAIM_ID = B.CLAIM_ID
                      AND DATE_TRUNC(''''DAY'''', TO_DATE(UPDATED_ON)) >= DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')) - 2
                      AND (   NVL (CATASTROPHE_EVENT, ''''NA'''') <> ''''NA''''
                           OR NVL (CATASTROPHE_REMARK, ''''NA'''') <> ''''NA''''))
           ON (CLM_REF = A.C_CLAIM_NO)
   WHEN MATCHED
   THEN
      UPDATE SET
         C_CAUSE_OF_LOSS = CATASTROPHE_EVENT,
         C_EVENT_CODE = CATASTROPHE_REMARK, ETL_REFRESH_AT = CURRENT_TIMESTAMP()'';
EXECUTE IMMEDIATE v_sqltext;


END;

v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_EVENT_CODE_ADD'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''insert  into  INTERMEDIATE.WRK_EVENT_CODE_ADD
      SELECT
            CLM_REF
        FROM PROD_DWH_MIGRATED_DB.STAGE.BJAZ_GEN_CLM_LOADER_LOG_MV a
       WHERE     CLM_REF IS NOT NULL
             AND DATE_TRUNC(''''DAY'''', UPLOAD_DATE) > DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')) - 5
             AND UPLOAD_REMARKS LIKE ''''Event Code%'''''';
EXECUTE IMMEDIATE v_sqltext;

BEGIN

v_sqltext := ''MERGE INTO TRANSACTIONAL.ODS_CLAIM_DIM A
        USING (SELECT DISTINCT
                     C_CLAIM_NO CLM_REF, C.EVENT_CODE, EVENT_DESC
                 FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_WB_CLM_BASE_MOT_EXT A,
                      (SELECT DISTINCT EVENT_CODE, EVENT_DESC
                         FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_CLM_EVENTS) C,
                      TRANSACTIONAL.ODS_CLAIM_DIM D
                WHERE     A.CLAIM_ID = D.C_CLAIM_ID
                      AND A.EVENT_CODE = C.EVENT_CODE
                      AND C_CLAIM_NO IN (SELECT * FROM INTERMEDIATE.WRK_EVENT_CODE_ADD))
           ON (CLM_REF = A.C_CLAIM_NO)
   WHEN MATCHED
   THEN
      UPDATE SET C_EVENT_CODE = EVENT_DESC, ETL_REFRESH_AT = CURRENT_TIMESTAMP()'';
EXECUTE IMMEDIATE v_sqltext;

END;

v_sqltext := ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_EVENT_UPDATE'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''insert  into INTERMEDIATE.WRK_EVENT_UPDATE
      SELECT C_CLAIM_NO
        FROM TRANSACTIONAL.WRK_EVENT_HIST
       WHERE     OLD_EVENT_CODE IS NOT NULL
             AND NEW_EVENT_CODE IS NULL
             AND DATE_TRUNC(''''DAY'''', CHANGE_DATE) = DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || ''''''))
      MINUS
      SELECT CLM_REF
        FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_HM_CLM_REGISTER A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
       WHERE     A.CLAIM_ID = B.CLAIM_ID
             AND CLM_REF IN
                    (SELECT C_CLAIM_NO
                       FROM TRANSACTIONAL.WRK_EVENT_HIST
                      WHERE     OLD_EVENT_CODE IS NOT NULL
                            AND NEW_EVENT_CODE IS NULL
                          and DATE_TRUNC(''''DAY'''', CHANGE_DATE) = DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')))'';
EXECUTE IMMEDIATE v_sqltext;

BEGIN

v_sqltext := ''UPDATE TRANSACTIONAL.ODS_CLAIM_DIM as target
            SET C_EVENT_CODE = src.EVENT_DESC, ETL_REFRESH_AT = CURRENT_TIMESTAMP()
FROM (SELECT
                DISTINCT C_CLAIM_NO CLM_REF, C.EVENT_CODE, EVENT_DESC
            FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_WB_CLM_BASE_MOT_EXT A,
                 ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_CLM_EVENTS C,
                 TRANSACTIONAL.ODS_CLAIM_DIM D
           WHERE     A.CLAIM_ID = D.C_CLAIM_ID
                 AND A.EVENT_CODE = C.EVENT_CODE
                 AND C_CLAIM_NO IN (SELECT * FROM INTERMEDIATE.WRK_EVENT_UPDATE)) AS src
WHERE C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;

END;

v_sqltext := ''UPDATE TRANSACTIONAL.ODS_CLAIM_DIM as target
            SET C_CAUSE_OF_LOSS = src.CATASTROPHE_EVENT,
             C_EVENT_CODE = src.CATASTROPHE_REMARK, ETL_REFRESH_AT = CURRENT_TIMESTAMP()
FROM (SELECT CLM_REF, CATASTROPHE_EVENT, CATASTROPHE_REMARK
            FROM ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.BJAZ_HM_CLM_REGISTER A, ''|| MIRROR_DB ||''.OPUS_GG_DWHSTAGE.CLM_BASES B
           WHERE     A.CLAIM_ID = B.CLAIM_ID
                 AND (   NVL (CATASTROPHE_EVENT, ''''NA'''') <> ''''NA''''
                      OR NVL (CATASTROPHE_REMARK, ''''NA'''') <> ''''NA'''')
                 AND CLM_REF IN

(SELECT C_CLAIM_NO
   FROM TRANSACTIONAL.WRK_EVENT_HIST
  WHERE     OLD_EVENT_CODE IS NOT NULL
        AND NEW_EVENT_CODE IS NULL
        AND DATE_TRUNC(''''DAY'''', CHANGE_DATE) = DATE_TRUNC(''''DAY'''', TO_DATE('''''' || T_DATE || '''''')))) AS src
WHERE C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''DELETE FROM TRANSACTIONAL.WRK_EVENT_HIST WHERE OLD_EVENT_CODE IS NULL
AND NEW_EVENT_CODE IS NULL'';
EXECUTE IMMEDIATE v_sqltext;

EXECUTE IMMEDIATE ''COMMIT'';
    RETURN ''Procedure executed successfully'';

EXCEPTION
    WHEN OTHER THEN
        EXECUTE IMMEDIATE ''ROLLBACK'';
        RAISE ;
        RETURN ''Error occurred: '' || SQLERRM || ''\\n'' || ''SQL: '' || ''\\n'' || v_sqltext;

END;
';