CREATE OR REPLACE PROCEDURE TRANSACTIONAL.WRK_RFA_DETAIL_UPDATE("MIRROR_DB" VARCHAR(16777216), "F_DATE" DATE DEFAULT CURRENT_DATE(), "T_DATE" DATE DEFAULT CURRENT_DATE())
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
v_sqltext VARCHAR;

BEGIN
v_sqltext :=  ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.wrk_rfa_date'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.wrk_rfa_date
      SELECT DISTINCT CLAIM_ID
        FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_TRANS
       WHERE DATE_TRUNC(''''DAY'''', TRANS_DATE) >= DATE_TRUNC(''''DAY'''', TO_DATE(''''''|| T_DATE || '''''')) - 3
      UNION
      SELECT CLAIM_ID
        FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.BJAZ_GEN_CLM_APPROVAL
       WHERE DATE_TRUNC(''''DAY'''', TRANS_DATE) >= DATE_TRUNC(''''DAY'''', TO_DATE(''''''|| T_DATE || '''''')) - 3'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext :=  ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_RFA_DATE_FINAL'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.WRK_RFA_DATE_FINAL
    SELECT CLM_REF,
            MIN (B.TRANS_DATE) MIN_RFA_DATE,
            MAX (B.TRANS_DATE) MAX_REF_DATE
       FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_BASES A, '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_TRANS B, PROD_DWH_MIGRATED_DB.PROD.ODS_RESERVE_DIM C, INTERMEDIATE.WRK_RFA_DATE d
      WHERE     A.CLAIM_ID = B.CLAIM_ID
      and    A.CLAIM_ID = D.CLAIM_ID
            AND SF_TOTAL_TYPE = R_RESERVE_TYPE
            AND B.CLM_STATUS = ''''AP''''
            AND R_RESERVE_GROUP_DESC <> ''''Expense''''
   GROUP BY CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''UPDATE TRANSACTIONAL.MV_CLAIM_REGISTER AS target
SET MIN_RFA_DATE = src.MIN_RFA_DATE,
    MAX_RFA_DATE = src.MAX_REF_DATE
from ( SELECT * FROM INTERMEDIATE.WRK_RFA_DATE_FINAL) AS src
WHERE target.C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext :=  ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_RFA_NAME'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''INSERT INTO INTERMEDIATE.WRK_RFA_NAME
     SELECT
        CLM_REF, MAX (ASSIGNEE) ASSIGNEE, DATE_TRUNC(''''DAY'''', TO_DATE(''''''|| T_DATE || ''''''))
    FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_BASES A,
         '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_TRANS B,
         PROD_DWH_MIGRATED_DB.PROD.ODS_RESERVE_DIM C,
         INTERMEDIATE.wrk_rfa_date D
   WHERE     A.CLAIM_ID = B.CLAIM_ID
         AND SF_TOTAL_TYPE = R_RESERVE_TYPE
         AND B.CLM_STATUS = ''''AP''''
         AND R_RESERVE_GROUP_DESC <> ''''Expense''''
         AND A.CLAIM_ID = d.CLAIM_ID
         AND (TRANS_NO) IN
                (SELECT MAX (TRANS_NO)
                   FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_TRANS C
                  WHERE A.CLAIM_ID = C.CLAIM_ID AND C.CLM_STATUS = ''''AP'''')
GROUP BY CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''UPDATE TRANSACTIONAL.MV_CLAIM_REGISTER AS target
SET RFA_RAISED_BY = src.ASSIGNEE
FROM (SELECT * FROM INTERMEDIATE.WRK_RFA_NAME) AS src
WHERE target.C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext :=  ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_USER_NAME'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''INSERT INTO INTERMEDIATE.WRK_USER_NAME
      SELECT CLM_REF, USER_NAME
        FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.BJAZ_GEN_CLM_APPROVAL A, PROD_DWH_MIGRATED_DB.PROD.ODS_RESERVE_DIM C
       WHERE     TRANS_DATE = DATE_TRUNC(''''DAY'''', TO_DATE(''''''|| T_DATE || '''''')) - 2
             AND SF_TOTAL_TYPE = R_RESERVE_TYPE
             AND R_RESERVE_GROUP_DESC <> ''''Expense''''
             AND PAY_APP_NO IN
                    (SELECT MAX (PAY_APP_NO)
                       FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.BJAZ_GEN_CLM_APPROVAL X, PROD_DWH_MIGRATED_DB.PROD.ODS_RESERVE_DIM Y
                      WHERE     SF_TOTAL_TYPE = R_RESERVE_TYPE
                            AND R_RESERVE_GROUP_DESC <> ''''Expense''''
                            AND X.CLM_REF = A.CLM_REF
                            AND X.TRANS_DATE = A.TRANS_DATE)'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''UPDATE TRANSACTIONAL.MV_CLAIM_REGISTER AS target
SET RFA_APPROVED_BY = src.USER_NAME
from
(SELECT * FROM INTERMEDIATE.WRK_USER_NAME) AS src
WHERE target.C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;


/*  */
/* v_sqltext :=  ''EXIT WHEN C%NOTFOUND''; */
-- END LOOP;

v_sqltext :=  ''TRUNCATE TABLE IF EXISTS INTERMEDIATE.WRK_RESONSILBE'';
EXECUTE IMMEDIATE v_sqltext;

v_sqltext := ''INSERT INTO INTERMEDIATE.WRK_RESONSILBE
        SELECT CLM_REF, RESPONSIBLE
          FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.BJAZ_GEN_CLM_RESP A, '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.CLM_BASES B
         WHERE     A.CLAIM_ID = B.CLAIM_ID
               AND B.CLAIM_ID IN
                      (SELECT CLAIM_ID FROM INTERMEDIATE.WRK_RFA_DATE
                       UNION
                       SELECT CLAIM_ID
                         FROM '' || MIRROR_DB || ''.OPUS_GG_DWHSTAGE.BJAZ_GEN_CLM_RESP
                        WHERE DATE_TRUNC(''''DAY'''', CHANGED_DATE) >= DATE_TRUNC(''''DAY'''', TO_DATE(''''''|| T_DATE || '''''')) - 3)
               AND TOP_INDICATOR = ''''Y''''
      GROUP BY CLM_REF, RESPONSIBLE'';
EXECUTE IMMEDIATE v_sqltext;


v_sqltext := ''UPDATE TRANSACTIONAL.MV_CLAIM_REGISTER AS target
SET ASSIGNED_OWNER_NAME = src.RESPONSIBLE
from
(SELECT * FROM INTERMEDIATE.WRK_RESONSILBE) as src
WHERE target.C_CLAIM_NO = src.CLM_REF'';
EXECUTE IMMEDIATE v_sqltext;


EXECUTE IMMEDIATE ''COMMIT'';
	RETURN ''Procedure executed successfully'';

	EXCEPTION
		WHEN OTHER THEN
			EXECUTE IMMEDIATE ''ROLLBACK'';
			RAISE ;
			RETURN ''Error occurred: '' || SQLERRM || ''\\\\\\\\n'' || ''SQL: '' || ''\\\\\\\\n'' || v_sqltext;



END;
';