{{ config(materialized='incremental') }}

-- AUGMENTED (unconfirmed) sat() for SAT_AUG_POLICY (HUB_POLICY grain).
-- 22 contributing table(s), union (no attribute merge attempted --
-- these columns were never analysed for cross-table overlap, unlike standard-model
-- satellites). NOT part of the canonical data_v4.js model. Needs mapper review before
-- being treated as equivalent to a standard-model satellite -- see docs.

{%- set yaml_metadata -%}
source_model:
  - 'stg2_aug_ba_hcp_dt_premium__policy'
  - 'stg2_aug_ba_hcp_prime_rider_dtls__policy'
  - 'stg2_aug_ba_hcp_prod_8439_clh_loader__policy'
  - 'stg2_aug_bgil_gmc_final_instl_data__policy'
  - 'stg2_aug_bjaz_gpg_pol_dtls__policy'
  - 'stg2_aug_bjaz_grp_hlt_dtls__policy'
  - 'stg2_aug_bjaz_hc_part_extn__policy'
  - 'stg2_aug_bjaz_hg_pol_dtls__policy'
  - 'stg2_aug_bjaz_hm_hcm_extract__policy'
  - 'stg2_aug_hlth_bjaz_hm_member_dtls__policy'
  - 'stg2_aug_bjaz_ihg_mem_dtls_extn__policy'
  - 'stg2_aug_bjaz_pmjay_prmbook_dtls__policy'
  - 'stg2_aug_bjaz_remedinet_claim_details__policy'
  - 'stg2_aug_ba_hcp_port_wordings__policy'
  - 'stg2_aug_ba_hcp_prod_8428_gpg_loader__policy'
  - 'stg2_aug_ba_hcp_prod_8432_ecp_loader__policy'
  - 'stg2_aug_bjaz_ecard_pol_dtls_config__policy'
  - 'stg2_aug_hlth_bjaz_ec_mem_dtls_extn__policy'
  - 'stg2_aug_bjaz_grp_hlt_maternity_dtls__policy'
  - 'stg2_aug_bjaz_hcf_member_dtls__policy'
  - 'stg2_aug_hlth_bjaz_hlt_ensure_mem_dtls__policy'
  - 'stg2_aug_hlth_bjaz_sh_mem_dtls_extn__policy'
src_pk: 'POLICY_HK'
src_payload:
  - 'CLAIMS_ANALYSIS_DATE'
  - 'CLAIMS_ANALYSIS_DATE_GPG'
  - 'CLAIMS_OUTSTANDING_ASON_DATE'
  - 'CLAIMS_PAID_ASON_DATE'
  - 'CLAIMS_REVIEW_CLAUSE'
  - 'CLAIM_REVIEW_PER'
  - 'CLM_LOAD'
  - 'CLM_PYD_IN2YRS_PRE_EXPIRY'
  - 'CONTINUITY_GUIDELINE'
  - 'CON_COMPANY'
  - 'CON_DEDUCTABLE'
  - 'CON_EXP_DATE'
  - 'COPAY_TYPE'
  - 'CRC_REVIEW_PERIOD'
  - 'DISCOUNT_DESC'
  - 'ELIGIBLE_DAYS'
  - 'EMI_OPTED'
  - 'EMI_PAYMNT_MAND'
  - 'EMI_YN'
  - 'FINAL_PAYABLE'
  - 'FIRST_POLICY_NUMBER'
  - 'FIRST_POLICY_REF'
  - 'FIRST_POL_INCEPTION_DATE'
  - 'FULL_YR_NET_PREM'
  - 'INCEPTION_WINPRD'
  - 'INSP_PRM_PAYED_EXP_STAX'
  - 'INST_BASE_HALF_YR_AMT'
  - 'INST_BASE_MONTHLY_AMT'
  - 'INST_BASE_QURTRLY_AMT'
  - 'INST_BASE_YRLY_AMT'
  - 'INST_NET_HALF_YR_AMT'
  - 'INST_NET_MONTHLY_AMT'
  - 'INST_NET_QURTRLY_AMT'
  - 'INST_NET_YRLY_AMT'
  - 'INST_TOT_HALF_YR_AMT'
  - 'INST_TOT_MONTHLY_AMT'
  - 'INST_TOT_QURTRLY_AMT'
  - 'INST_TOT_YRLY_AMT'
  - 'LOAD_AMT'
  - 'MD_FIRST_POLICY_INCEPTION_DATE'
  - 'MD_PREV_COMP_ADDRESS'
  - 'MD_PREV_EXPIRY_DATE'
  - 'MEMBER_COUNT_EXPIRING'
  - 'MEMBER_CO_PAY'
  - 'NON_NETWORK_CO_PAY'
  - 'OTHER_OPAYMENT_DTLS'
  - 'PATIENT_PAID_AMOUNT'
  - 'PERV_POL_EXP_DATE'
  - 'PER_FAMILY_PRM'
  - 'PLC_EMI_INR'
  - 'PLC_RE_INSURANCE'
  - 'POLICY_ISSUANCE_CONFIRMATION'
  - 'POL_VERSION_NO'
  - 'PORT_REASON'
  - 'PREMIUM_ADDITION'
  - 'PREVIOUS_FROM_DATE'
  - 'PREVIOUS_TO_DATE'
  - 'PREV_POLICY_EXPIRY'
  - 'PREV_POLICY_EXP_DATE'
  - 'PREV_POLICY_SINCE'
  - 'PRM_IN2YRS_OFEXPIRY'
  - 'PRORATA_PREMIUM'
  - 'REFUND_PER_ANNUALLY'
  - 'ROOM_RENT_DIFF_CO_PAY'
  - 'SERVICE_TAX_EXEMPTION_AMT'
  - 'TOTAL_CLAIM'
  - 'UTGST_AMT'
  - 'UTIZATION_CORPORATE'
src_hashdiff: 'HASHDIFF'
src_ldts: 'LOAD_DATETIME'
src_source: 'RECORD_SOURCE'
{%- endset -%}

{% set metadata_dict = fromyaml(yaml_metadata) %}

{{ automate_dv.sat(src_pk=metadata_dict['src_pk'],
                    src_payload=metadata_dict['src_payload'],
                    src_hashdiff=metadata_dict['src_hashdiff'],
                    src_ldts=metadata_dict['src_ldts'],
                    src_source=metadata_dict['src_source'],
                    source_model=metadata_dict['source_model']) }}
