-- Staging model for source table BA_HCP_DT_MEM (Partner LOB).
-- Casting: TEXT/VARCHAR2/CHAR -> trimmed VARCHAR, NUMBER -> NUMBER, TIMESTAMP/DATE -> TIMESTAMP_NTZ.
-- Key columns (hub-key components) -> canonical trimmed VARCHAR regardless of native type,
-- for stable hashing -- same convention as the Health LOB build.

with source as (

    select
    "COL34"::timestamp_ntz as col34,
    nullif(trim("COL71"::varchar), '') as col71,
    nullif(trim("COL59"::varchar), '') as col59,
    nullif(trim("COL46"::varchar), '') as col46,
    nullif(trim("COL47"::varchar), '') as col47,
    nullif(trim("COL48"::varchar), '') as col48,
    nullif(trim("COL49"::varchar), '') as col49,
    nullif(trim("COL50"::varchar), '') as col50,
    nullif(trim("COL51"::varchar), '') as col51,
    nullif(trim("COL52"::varchar), '') as col52,
    nullif(trim("COL53"::varchar), '') as col53,
    nullif(trim("COL54"::varchar), '') as col54,
    nullif(trim("COL55"::varchar), '') as col55,
    nullif(trim("COL56"::varchar), '') as col56,
    nullif(trim("COL57"::varchar), '') as col57,
    nullif(trim("COL58"::varchar), '') as col58,
    nullif(trim("COL60"::varchar), '') as col60,
    "PREM_BASE_COVER"::number as prem_base_cover,
    "COL1"::number as col1,
    "COL2"::number as col2,
    "COL3"::number as col3,
    "COL4"::number as col4,
    "COL5"::number as col5,
    "COL6"::number as col6,
    "COL7"::number as col7,
    "COL8"::number as col8,
    "COL9"::number as col9,
    "COL10"::number as col10,
    "COL11"::number as col11,
    "COL12"::number as col12,
    "COL13"::number as col13,
    "COL14"::number as col14,
    nullif(trim("COL92"::varchar), '') as col92,
    nullif(trim("COL93"::varchar), '') as col93,
    nullif(trim("COL94"::varchar), '') as col94,
    nullif(trim("COL95"::varchar), '') as col95,
    nullif(trim("COL96"::varchar), '') as col96,
    nullif(trim("COL97"::varchar), '') as col97,
    nullif(trim("COL98"::varchar), '') as col98,
    nullif(trim("COL99"::varchar), '') as col99,
    nullif(trim("COL100"::varchar), '') as col100,
    "GG_CHANGE_DATE"::timestamp_ntz as gg_change_date,
    nullif(trim("ACTION_CODE"::varchar), '') as action_code,
    "VERSION_NO"::number as version_no,
    "OBJECT_ID"::number as object_id,
    nullif(trim("TOP_INDICATOR"::varchar), '') as top_indicator,
    "PREVIOUS_VERSION"::number as previous_version,
    "REVERSING_VERSION"::number as reversing_version,
    nullif(trim(to_varchar("CONTRACT_ID")), '') as contract_id,
    "HCP_SEQNO"::number as hcp_seqno,
    "MEM_SEQNO"::number as mem_seqno,
    nullif(trim("MEM_ADD_FLAG"::varchar), '') as mem_add_flag,
    nullif(trim("MEM_STATUS"::varchar), '') as mem_status,
    nullif(trim("USER_ID"::varchar), '') as user_id,
    "ENTRY_DATE"::timestamp_ntz as entry_date,
    nullif(trim(to_varchar("PART_ID")), '') as part_id,
    nullif(trim("MEMBER_NAME"::varchar), '') as member_name,
    "COL15"::number as col15,
    "COL16"::number as col16,
    "COL17"::number as col17,
    "COL18"::number as col18,
    "COL19"::number as col19,
    "COL20"::number as col20,
    "COL21"::timestamp_ntz as col21,
    "COL22"::timestamp_ntz as col22,
    "COL23"::timestamp_ntz as col23,
    "COL24"::timestamp_ntz as col24,
    "COL25"::timestamp_ntz as col25,
    "COL26"::timestamp_ntz as col26,
    "COL27"::timestamp_ntz as col27,
    "COL28"::timestamp_ntz as col28,
    "COL29"::timestamp_ntz as col29,
    "COL30"::timestamp_ntz as col30,
    nullif(trim("COL77"::varchar), '') as col77,
    nullif(trim("COL78"::varchar), '') as col78,
    nullif(trim("COL79"::varchar), '') as col79,
    nullif(trim("COL80"::varchar), '') as col80,
    nullif(trim("COL81"::varchar), '') as col81,
    nullif(trim("COL82"::varchar), '') as col82,
    nullif(trim("COL83"::varchar), '') as col83,
    nullif(trim("COL84"::varchar), '') as col84,
    nullif(trim("COL85"::varchar), '') as col85,
    nullif(trim("COL86"::varchar), '') as col86,
    nullif(trim("COL87"::varchar), '') as col87,
    nullif(trim("COL88"::varchar), '') as col88,
    nullif(trim("COL89"::varchar), '') as col89,
    nullif(trim("COL90"::varchar), '') as col90,
    nullif(trim("COL91"::varchar), '') as col91,
    "COL31"::timestamp_ntz as col31,
    "COL32"::timestamp_ntz as col32,
    "COL33"::timestamp_ntz as col33,
    "COL35"::timestamp_ntz as col35,
    "COL36"::timestamp_ntz as col36,
    "COL37"::timestamp_ntz as col37,
    "COL38"::timestamp_ntz as col38,
    "COL39"::timestamp_ntz as col39,
    "COL40"::timestamp_ntz as col40,
    nullif(trim("COL41"::varchar), '') as col41,
    nullif(trim("COL42"::varchar), '') as col42,
    nullif(trim("COL43"::varchar), '') as col43,
    nullif(trim("COL44"::varchar), '') as col44,
    nullif(trim("COL45"::varchar), '') as col45,
    nullif(trim("COL61"::varchar), '') as col61,
    nullif(trim("COL62"::varchar), '') as col62,
    nullif(trim("COL63"::varchar), '') as col63,
    nullif(trim("COL64"::varchar), '') as col64,
    nullif(trim("COL65"::varchar), '') as col65,
    nullif(trim("COL66"::varchar), '') as col66,
    nullif(trim("COL67"::varchar), '') as col67,
    nullif(trim("COL68"::varchar), '') as col68,
    nullif(trim("COL69"::varchar), '') as col69,
    nullif(trim("COL70"::varchar), '') as col70,
    nullif(trim("COL72"::varchar), '') as col72,
    nullif(trim("COL73"::varchar), '') as col73,
    nullif(trim("COL74"::varchar), '') as col74,
    nullif(trim("COL75"::varchar), '') as col75,
    nullif(trim("COL76"::varchar), '') as col76
    from {{ source('partner_raw', 'BA_HCP_DT_MEM') }}

)

select * from source
