{{
    config(
        materialized='view'
    )
}}

-- Staging: MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS_MULTISET_ATTRIBUTE_ATTRIBUTES_PIVOT_VW_2_1
-- Source: raw_health_policy

WITH source AS (
    SELECT *
    FROM {{ source('raw_health_policy', 'MAXI_HLTH_UWR_VW_DATA_MEMBERS_MEMBER_DETAILS_MULTISET_ATTRIBUTE_ATTRIBUTES_PIVOT_VW_2_1') }}
),

staged AS (
    SELECT
        -- Keys
        FOREIGN_KEY,

        -- Business columns
        TO_DATE,
        SPIRITS_CONSUMPTION_PER_WEEK,
        ELIGIBILITY_PARAMETER,
        NO_OF_KM_RUN,
        DATE_OF_BIRTH,
        MEDICATION_DOSAGE,
        POLICY_RISK_EXPIRY_DATE,
        NOMINEE_DATE_OF_BIRTH,
        APPLICABLE_FOR_OTHER_MEMBER,
        ICD_CODE,
        TYPE_OF_POLICY,
        APPLICABLE_LEVEL,
        OTHER_TYPE_OF_LOAN,
        EMPLOYEE_ID,
        WINE_CONSUMPTION_PER_WEEK,
        LOAN_TENURE_IN_YEARS,
        DISCOUNT_RATE,
        NUMBER_OF_CLAIMS_LODGED,
        SANCTIONED_LOAN_AMOUNT,
        SL_NUMBER,
        CLAIM_RECEIVED_AMOUNT,
        DISCOUNT_LOADING_TYPE,
        GROSS_INCOME,
        SUM_INSURED_IN_PREVIOUS_POLICY,
        EXEMPTED_INCOME,
        APPOINTEE_NAME,
        PLAN_OF_POLICY,
        IF_OTHERS_PLEASE_SPECIFY,
        LOADING_RATE,
        MEDIUS_ANSWER,
        PERCENTAGE,
        DISCOUNT_LOADING_TYPE_POLICY,
        AGE,
        QUESTION_ID,
        NET_PREMIUM,
        MEDICATIONS_DURATION,
        NAME_OF_MARATHON,
        PARTY_NAME,
        RELATIONSHIP_OF_APPOINTEE_WITH_THE_NOMINEE,
        INSURER_CODE,
        INSURER,
        EMAIL_ID,
        PROPOSED_SUM_INSURED,
        GENDER,
        FINANCIAL_NAME,
        TOTAL_INCOME,
        LOADING_DISCOUNT_REASON_POLICY,
        MEMBER_CODE,
        DISCOUNT_AND_LOADING_REASON,
        ELIGIBLE_SUM_INSURED,
        POLICY_STATUS,
        NOMINEE_,
        QUESTION_TEXT,
        POLICY_NO,
        BANK_BRANCH_ADDRESS,
        OTHER_BAGIC_POLICY_NUMBER,
        CUMULATIVE_BONUS_IN_PREVIOUS_POLICY,
        LOAN_ACCOUNT_NUMBER,
        NO_CLAIM_BONUS,
        EMI,
        NOMINEE_NAME,
        CLAIMED_FOR,
        TYPE_OF_LOAN,
        REMARKS,
        PRODUCT_NAME,
        RELATIONSHIP_WITH_PROPOSER,
        PROPOSER_NAME,
        DISCOUNT_LOADING_RATE,
        PREVIOUS_POLICY_START_DATE,
        FROM_DATE,
        ICD_DESCRIPTION,
        NAME_ADDRESS_OF_INSURANCE_COMPANY,
        INTERNATIONAL_SUM_INSURED_IN_PREVIOUS_POLICY,
        LOADING_WAIVE_OFF,
        PREVIOUS_POLICY_EXPIRY_DATE,
        TYPE_OF_PREVIOUS_INSURANCE,
        ADDRESS_OF_NOMINEE,
        PREVIOUS_POLICYPROPOSAL_NUMBER,
        MEDIUSNAME,
        CONTINUITY_INDICATOR_APPROVED,
        DATE,
        BEER_CONSUMPTION_PER_WEEK,
        DATE_FIT,

        -- Metadata
        INC_JOB_CREATED_AT,
        REC_REFRESH_AT,
        CURRENT_TIMESTAMP() AS load_dt_tm,
        'MAXIMUS' AS record_source

    FROM source src
)

SELECT * FROM staged