name: 'travel_dv'
version: '1.0.0'
config-version: 2

profile: 'travel_dv'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  travel_raw_database: RAW
  travel_raw_schema: GG_DWHSTAGE

models:
  travel_dv:
    staging:
      travel:
        +materialized: view
        +schema: stg_travel
    automate_dv:
      standard:
        +schema: std_automate_dv_travel
        stitched:
          +materialized: view
        staging:
          +materialized: view
        hubs:
          +materialized: incremental
        links:
          +materialized: incremental
        satellites:
          +materialized: incremental
        references:
          +materialized: view
      augmented:
        +schema: aug_automate_dv_travel
        staging:
          +materialized: view
        satellites:
          +materialized: incremental
