CREATE OR REPLACE PROCEDURE BAGIC_DEV_CURATED_DB.TRANSACTIONAL.R_TBR_UPDATE_RS("MIRROR_DB" VARCHAR(16777215), "SYS_DATE" DATE DEFAULT CURRENT_DATE())
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
 
 
DECLARE
v_sqltext VARCHAR;
 
BEGIN
 
 
V_SQLTEXT := ''UPDATE TRANSACTIONAL.ODS_RENEWAL_DTLS A
SET
A.R_PROCESS_DATE = I.PROCESS_DATE,
A.R_TBR_SPECIAL_DISCOUNT = I.SPECIAL_DISCOUNT,
A.R_TBR_SPECIAL_DISCOUNT_RATE = I.SPECIAL_DISCOUNT_RATE,
A.R_TBR_BASIC_OD_RATE = I.BASIC_OD_RATE,
A.R_TBR_FAMILY_DISCOUNT = I.FAMILY_DISCOUNT,
A.R_TBR_COMMERCIAL_DISC_RATE = I.COMMERCIAL_DISC_RATE,
A.R_TBR_COMMERCIAL_DISC_AMOUNT = I.COMMERCIAL_DISC_AMOUNT,
A.R_TBR_ADD_LOAD_RATE = I.ADD_LOAD_RATE,
A.R_TBR_ADD_LOAD_AMT = I.ADD_LOAD_AMT,
A.R_TBR_NCB_RATE = I.NCB_RATE,
A.R_TBR_NET_PREMIUM = I.NEW_NET_PREMIUM,
A.R_TBR_GROSS_PREMIUM = I.NEW_GROSS_PREMIUM,
A.R_TBR_TERRORISM_PREMIUM = I.NEW_TERRORISM_PREMIUM,
A.R_TBR_EDU_CESS = I.NEW_EDU_CESS,
A.R_TBR_STATUS = I.RN_STATUS,
A.R_TBR_SERVICE_TAX = I.NEW_SERVICE_TAX,
A.R_TBR_SUM_INSURED = I.SUM_INSURED,
A.R_TBR_FLAG_FOR_IDV = I.FLAG_FOR_IDV,
A.R_TBR_PRICE_MASTER_CITY = I.PRICE_MASTER_CITY,
A.R_TBR_EX_SHOWRM_PRICE = I.EX_SHOWROOM_PRICE,
A.R_TBR_DEPRICATE_RATE = I.DEPRICATE_RATE,
A.R_REGISTRATION_DATE = I.REGISTRATION_DATE,
A.R_TBR_ADD_EXCESS = I.ADD_EXCESS,
A.R_TBR_VOL_EXCESS = I.VOL_EXCESS,
A.R_TBR_VEHICLE_AGE = I.VEHICLE_AGE,
A.R_TBR_VEHICLE_CODE = I.VEHICLE_CODE,
A.R_TBR_QC_STATUS = I.QC_STATUS,
A.R_TBR_REMARKS = I.REMARKS,
A.R_TBR_ADDON_PKG_PREM = I.ADDON_PKG_PREM,
A.R_TBR_ADDON_PKG_ID = I.ADDON_PKG_ID,
A.R_TBR_ADDON_PKG_DISC = I.ADDON_PKG_DISC,
A.R_TBR_DRIVE_ASUR_PREM = I.DRIVE_ASUR_PREM,
A.R_TBR_NEW_VEHICLE_CODES = I.NEW_VEHICLE_CODES,
A.R_TBR_GC_OLD_PLAN_ID = I.GC_OLD_PLAN_ID,
A.R_TBR_GC_NEW_PLAN_ID = I.GC_NEW_PLAN_ID,
A.R_TBR_GC_PLAN_SI = I.GC_PLAN_SI,
A.R_TBR_GC_CB_RATE = I.GC_CB_RATE,
A.R_TBR_GC_CB_AMOUNT = I.GC_CB_AMOUNT,
A.R_TBR_OD_PREM_1ST = I.TOTAL_OD_PREM_1ST,
A.R_TBR_LEGAL_LIABILITY_DRIVER =I.LEGAL_LIABILITY_TO_DRIVER,
A.R_TBR_PA_COVER_TO_PASSENGERS =I.PA_COVER_TO_PASSENGERS,
A.R_TBR_PA_COVER_TO_PASNGR_SI =I.PA_COVER_TO_PASSENGERS_SI,
A.R_TBR_AH_SUM_INSURED = I.AH_SUM_INSURED,
A.R_TBR_AH_ADDON_PREMIUM = I.AH_ADDON_PREMIUM,
A.R_TBR_COMMENTS = I.COMMENTS,
A.R_TBR_TARIFF_IND = I.R_TBR_TARIFF_IND,
A.R_TBR_SHORT_POLICY_YN = I.R_TBR_SHORT_POLICY_YN,
A.R_TBR_BASIC_OD_PREM_1801 = I.R_TBR_BASIC_OD_PREM_1801,
A.R_TBR_BASIC_OD_PREM_1818 = I.R_TBR_BASIC_OD_PREM_1818,
A.R_TBR_ELECACC_IEV = I.R_TBR_ELECACC_IEV,
A.R_TBR_NON_ELEC_IEV = I.R_TBR_NON_ELEC_IEV,
--A.R_PROFITABLE_FLAG = I.PROFITABLE_FLAG, COMMENT BY SUJIT ON 23APR24
A.R_REMAPPED_LOCATION = I.R_REMAPPED_LOCATION,
A.R_REMAPPED_IMD_CODE = I.R_REMAPPED_IMD_CODE,
A.R_REMAPPED_SUB_IMD = I.R_REMAPPED_SUB_IMD,
A.R_STAGE = ''''ST_8_TBR_UPD'''',
A.R_LAST_EDIT = current_timestamp::timestamp,
A.R_TBR_TERM_END_DATE = I.R_TBR_TERM_END_DATE,
A.R_TBR_PART_NAME = I.R_TBR_PART_NAME,
A.R_TBR_ADDRESS_LINE5 = I.R_TBR_ADDRESS_LINE5,
A.R_TBR_VERTICAL_SEGMENT = I.R_TBR_VERTICAL_SEGMENT,
A.R_TBR_VEHICLE_MAKE = I.R_TBR_VEHICLE_MAKE,
A.R_TBR_VEHICLE_MODEL = I.R_TBR_VEHICLE_MODEL,
A.R_TBR_VEHICLE_SUBTYPE = I.R_TBR_VEHICLE_SUBTYPE,
A.R_TBR_CONTRACT_STATUS = I.R_TBR_CONTRACT_STATUS,
A.R_TBR_PRODUCT_CODE = I.R_TBR_PRODUCT_CODE,
A.R_TBR_ENHN_SUM_INSURED = I.ENHANCED_SUM_INSURED,
A.R_TBR_ENHN_GROSS_PREMIUM = I.ENHANCED_GROSS_PREMIUM,
A.R_TBR_ENHN_NET_PREMIUM = I.ENHANCED_NET_PREMIUM,
A.R_TBR_TAX_DESC = SUBSTR(I.R_TBR_TAX_DESC,1,99),------ADD BY VP 20JAN2018
A.R_TBR_SWB_KKC_AMT = I.R_TBR_SWB_KKC_AMT,
A.R_TBR_SYS_CALC_IDV=I.R_TBR_SYS_CALC_IDV,
A.R_TBR_COMM_DISC_AMT_1ST=I.R_TBR_COMM_DISC_AMT_1ST,
A.R_TBR_COMM_DISC_RATE_1ST=I.R_TBR_COMM_DISC_RATE_1ST,
--A.R_TBR_WEB_USERID=I.WEB_USERID,
A.R_TBR_OD_PREMIUM=I.OD_PREMIUM
 
FROM (SELECT *
FROM
intermediate.ODS_PREMIUM_RENEWAL1
 
) I
WHERE A.R_POLICY_REF = I.POLICY_REF
AND
NOT EXISTS (SELECT 1 FROM INTERMEDIATE.ODS_REN_MAXIMUS_PRODUCT_DIM WHERE PRODUCT=R_PRODUCT_ID AND NVL(MASTER_POLICY_NO,''''KGF'''')=NVL(R_MASTER_POLICY_NO,''''KGF'''') )''; ---ADDED BY VP AND SANKET -- 27AUG-2021 EXCLUDE MAXIMUS
 
EXECUTE IMMEDIATE V_SQLTEXT;
 
 
 
EXECUTE IMMEDIATE ''COMMIT'';
    RETURN ''Procedure executed successfully'';
 
EXCEPTION
    WHEN OTHER THEN
         EXECUTE IMMEDIATE ''ROLLBACK'';
         --RAISE ;
         RETURN ''Error occurred: '' || SQLERRM || ''\\n'' || ''SQL: '' || ''\\n'' || v_sqltext;
 
 
END;
';
