{{ config(materialized='view') }}

SELECT PARTY_HKEY, HASHDIFF, NULL AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, NULL AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_pa_mem_dtls__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, PREVIOUSINSURERNAME::VARCHAR AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, PREVIOUSSUMINSURED::VARCHAR AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ec_mem_dtls_extn__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, CONTINUITYINDICATOR::VARCHAR AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, PREVIOUSSUMINSURED::VARCHAR AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hcf_member_dtls__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, NULL AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hc_part_extn__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, CONTINUITYINDICATOR::VARCHAR AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, PREVIOUSINSURERNAME::VARCHAR AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, PREVIOUSSUMINSURED::VARCHAR AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hlt_ensure_mem_dtls__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, NULL AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_pa_detl_extn__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, PREVIOUSSUMINSURED::VARCHAR AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_sh_mem_dtls_extn__party_vehicle_prior_insurance') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, CONTINUITYINDICATOR::VARCHAR AS CONTINUITYINDICATOR, NULL AS PREVIOUSEXPIRYDATE, NULL AS PREVIOUSINSURERNAME, PREVIOUSPOLICYNUMBER::VARCHAR AS PREVIOUSPOLICYNUMBER, PREVIOUSSUMINSURED::VARCHAR AS PREVIOUSSUMINSURED, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_spp_member_dtls__party_vehicle_prior_insurance') }}
