{{ config(materialized='view') }}

SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, EIANUMBER::VARCHAR AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_azbj_partner_extn__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, EIANUMBER::VARCHAR AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_azbj_part_ext_hist__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, GSTTAXPAYERTYPE::VARCHAR AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, PANNUMBER::VARCHAR AS PANNUMBER, NULL AS PASSPORTNUMBER, TANNUMBER::VARCHAR AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_clm_supp_extn__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, VATREGISTRATIONNUMBER::VARCHAR AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_cp_part_hist__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, PASSPORTNUMBER::VARCHAR AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_ff_dtls_extn__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, AADHAARNUMBER::VARCHAR AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, EIANUMBER::VARCHAR AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, PANNUMBER::VARCHAR AS PANNUMBER, PASSPORTNUMBER::VARCHAR AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_pa_mem_dtls__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, AGEPROOFTYPE::VARCHAR AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ec_mem_dtls_extn__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, AGEPROOFTYPE::VARCHAR AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hcf_member_dtls__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, AGEPROOFTYPE::VARCHAR AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hlt_ensure_mem_dtls__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hm_hospital_master__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, GSTIN::VARCHAR AS GSTIN, GSTREGISTRATIONSTATUS::VARCHAR AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, PANNUMBER::VARCHAR AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_intermediary__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, GSTIN::VARCHAR AS GSTIN, GSTREGISTRATIONSTATUS::VARCHAR AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, PANNUMBER::VARCHAR AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_intermediary_hist__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, NULL AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, PASSPORTNUMBER::VARCHAR AS PASSPORTNUMBER, NULL AS TANNUMBER, NULL AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_starpkg_ff_dtls__party_identification') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS AADHAARNUMBER, NULL AS AGEPROOFTYPE, NULL AS EIANUMBER, NULL AS GSTIN, NULL AS GSTREGISTRATIONSTATUS, NULL AS GSTTAXPAYERTYPE, IDENTIFICATIONNUMBER::VARCHAR AS IDENTIFICATIONNUMBER, NULL AS PANNUMBER, NULL AS PASSPORTNUMBER, NULL AS TANNUMBER, VATREGISTRATIONNUMBER::VARCHAR AS VATREGISTRATIONNUMBER, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_cp_partners__party_identification') }}
