{{ config(materialized='view') }}

SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, EMPLOYEEID, NULL AS LOCATIONREFERENCE, NULL AS MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_azbj_partner_extn__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, EMPLOYEEID, NULL AS LOCATIONREFERENCE, NULL AS MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_azbj_part_ext_hist__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, EMPLOYEEID, NULL AS LOCATIONREFERENCE, NULL AS MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_clm_supp_extn__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, NULL AS MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_pa_mem_dtls__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ec_mem_dtls_extn__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hcf_member_dtls__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hlt_ensure_mem_dtls__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, DESIGNATIONBAND, EMPLOYEEID, LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hm_member_dtls__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_pa_detl_extn__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_sh_mem_dtls_extn__party_group_census') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, NULL AS ACTIVEINDICATOR, NULL AS DESIGNATIONBAND, NULL AS EMPLOYEEID, NULL AS LOCATIONREFERENCE, MEMBERREFERENCE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_spp_member_dtls__party_group_census') }}
