{{ config(materialized='view') }}

SELECT PARTY_HKEY, HASHDIFF, ACCOUNTNUMBERMASKED, NULL AS BANKCODE, NULL AS BANKNAME, IFSCCODE, MICRCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_azbj_partner_extn__party_banking') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, ACCOUNTNUMBERMASKED, NULL AS BANKCODE, NULL AS BANKNAME, IFSCCODE, MICRCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_azbj_part_ext_hist__party_banking') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, ACCOUNTNUMBERMASKED, NULL AS BANKCODE, BANKNAME, NULL AS IFSCCODE, NULL AS MICRCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_clm_supp_extn__party_banking') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, ACCOUNTNUMBERMASKED, BANKCODE, NULL AS BANKNAME, NULL AS IFSCCODE, NULL AS MICRCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_ctngy_pa_mem_dtls__party_banking') }}
UNION ALL
SELECT PARTY_HKEY, HASHDIFF, ACCOUNTNUMBERMASKED, NULL AS BANKCODE, BANKNAME, NULL AS IFSCCODE, MICRCODE, LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_sat_bjaz_hm_member_dtls__party_banking') }}
