{{ config(materialized='view') }}

-- Source 1: BJAZ_HM_HOSPITAL_MASTER
SELECT
    PARTY_HKEY, HASHDIFF,
    EMPANELMENT_DATE,
    NULL AS EMPANELMENT_STATUS,
    NETWORK_INDICATOR,
    PREFERRED_PROVIDER_INDICATOR,
    PROVIDER_TYPE,
    NULL AS RE_EMPANELMENT_DUE_DATE,
    SPECIALISATION,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_rolesat_bjaz_hm_hospital_master__lnk_role_provider') }}

UNION ALL

-- Source 2: CLM_SUPPLIERS
SELECT
    PARTY_HKEY, HASHDIFF,
    EMPANELMENT_DATE,
    EMPANELMENT_STATUS,
    NULL AS NETWORK_INDICATOR,
    NULL AS PREFERRED_PROVIDER_INDICATOR,
    PROVIDER_TYPE,
    RE_EMPANELMENT_DUE_DATE,
    NULL AS SPECIALISATION,
    LOAD_DATETIME, RECORD_SOURCE
FROM {{ ref('stg2_rolesat_clm_suppliers__lnk_role_provider') }}
